### ISSUE TITLE
Actual type of BlockHeader model difficulty field in the api

### ISSUE THREAD

**Issue by ivanovs-4** [ergoplatform/ergo#1002]
The specification (openapi.yaml) says that the field type "difficulty" of the BlockHeader model is int32. In fact, the node returns a string with a number in the response of the handle `/blocks/{headerId}`

https://github.com/ergoplatform/ergo/blob/2ada64922e605bfecccddcbec91af1af52e591b9/src/main/resources/api/openapi.yaml#L793

**Comment by jozanek** [comment]
This issue has already been fixed, please close it @ivanovs-4 (cc @kushti)

**Comment by abebeos** [comment]
@jellymlg , @glasgowm148 , issue is closable (fixed within #1683)
