### ISSUE TITLE
Fix unstable "concurrent applyModifier() and proofsForTransactions()" test

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1023]
The test is failing sometimes with :

 - concurrent applyModifier() and proofsForTransactions() *** FAILED ***

[info]   java.lang.Error: Calculated proofHash is not equal to the declared one
[info]   at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$2(UtxoState.scala:121)
[info]   at scala.util.Success.$anonfun$map$1(Try.scala:255)
[info]   at scala.util.Success.map(Try.scala:213)
[info]   at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$1(UtxoState.scala:111)
[info]   at scala.util.Success.flatMap(Try.scala:251)
[info]   at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:110)
[info]   at org.ergoplatform.nodeView.state.UtxoStateSpecification.$anonfun$new$31(UtxoStateSpecification.scala:199)
[info]   at org.ergoplatform.nodeView.state.UtxoStateSpecification.$anonfun$new$31$adapted(UtxoStateSpecification.scala:198)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:941)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:941)

**Comment by abebeos** [comment]
@kushti , is this one and the related #1387 still relevant?

**Comment by abebeos** [comment]
My understanding is that this bug is 5 years old:

- https://github.com/ergoplatform/ergo/issues/289

Do you want this still to be fixed, or does the ergo foundation not care about fixing bugs in the ergo code-base?

I totally do not understand.

**Comment by kushti** [comment]
Probably the same bug. To the moment no one (so me and @knizhnik  at least) was able to reproduce it. There is dirty re-calculation workaround during block validation now, with it things look okay (nodes do not stuck at least). Would be good to find a reason and fix it, but again, first we need to reproduce it somehow (and it is not concurrent access but some modifications in the tree persist after rollback)

**Comment by abebeos** [comment]
I reproduced it, but have stopped work as no one replies on this repo,. #1972/#1973

**Comment by stenolog** [comment]
> Probably the same bug.
from above: https://github.com/ergoplatform/ergo/issues/1023#issuecomment-1504200048

>Probably related to #1023 ( #1025 ), but initial investigation

^ you wrote within https://github.com/ergoplatform/ergo/issues/1387#issue-917172969
You know how those sporadic bugs are: "probably", "maybe", frustration, all-nighters with zero progress etc., "investigate in this direction, that direction (trial&error)", some luck at some point. 
I see i1387 ($2000) more as an budget-extension for  i1023 ($500).
Reaching the tiny fix was hell (though I'm now better prepared for the next sporadic bug).

Those 2 issues are in no case "duplicates". They were filed issues, with applied bounties.

In a real decentralized/automated setting, they would have been simply payed out without discussion.

I received bounty for #1387, but this here was not payed out, which I believe is not fair.

**Comment by kushti** [comment]
Those bugs have the same reason so clearly duplicates.

**Comment by stenolog** [comment]
> Those bugs have the same reason

after(!) I worked my ass off to uncover this (I spent much time on both issues), it's easy to say for you.

Totally unfair.
