### ISSUE TITLE
Error in generating transaction without inputsRaw.

### ISSUE THREAD

**Issue by mehranagh20** [ergoplatform/ergo#1024]
Sometimes generating transaction without specifying inputsRaw will fail with an error message:
>  No enough boxes to assemble a transaction for ...

The same transaction will be generated if you specify boxes to be used!

**Comment by kushti** [comment]
@mehranagh20 any context ? Transaction assembler can fail even if it is possible to create a transactions, but such an issue would be VERY rare. More probably, this problem is caused by some other component.

**Comment by kushti** [comment]
@mehranagh20 Probably caused by node restart? Then I know this bug probably

**Comment by mehranagh20** [comment]
Node restart may be the case. I'm not getting the same error again to give you more context, unfortunately.
