### ISSUE TITLE
More efficient hash code for Array[Byte]

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo#1037]
### Problem
Some classes override hashCode as part of equality implementation.
If that hash code involve calling hashCode on Array[Byte] that is inefficient (see url below)
This should probably be first confirmed with benchmarking, but sound reasonable.

### Solution
The solution is simple [alternative](
https://github.com/ergoplatform/ergo/blob/0ca1369dc789207f47bc7f9e3e77b1201882b907/avldb/src/main/java/scorex/ByteUtils.java#L26)

**Comment by kushti** [comment]
@aslesarenko pretty confusing description, where should we use this alternative, to start with ?

**Comment by aslesarenko** [comment]
`java.util.Arrays.hashCode`  is used in ExtendedPublicKey and ExtendedSecretKey, however those are not performance hotspots.
