### ISSUE TITLE
Implement get transaction by id and get unspent boxes by address

### ISSUE THREAD

**Issue by scalahub** [ergoplatform/ergo#1050]
This will require two types of indexing: transaction by id and UTXOs (boxes) by address.
Suggested approach to use two flags, one for each type index.

**Comment by kushti** [comment]
Such indexes would be heavy, and so should be optional (like in Bitcoin Core, see -txindex=1 flag there)

**Comment by jozanek** [comment]
This issue has been already fixed.

**Comment by abebeos** [comment]
@jellymlg , @glasgowm148 , issue fixed within #1859, please close.
