### ISSUE TITLE
Ergo Explorer can't find my wallet address

### ISSUE THREAD

**Issue by travek** [ergoplatform/ergo#1058]
Hello!

I setup an ergo node v 3.2.1. It's current status as shown on 
http://127.0.0.1:9052/panel/
is Active synchronization.
On the tap Wallet of the Panel I got my wallet address. I copied it and paste to the Explorer (https://explorer.ergoplatform.com/). Explorer is showing an error:
_Unrecognized search pattern. Please try searching by entering address, block hash or transaction hash_
How is this happen ? An how I can see my wallet address in the explorer ?

**Comment by travek** [comment]
I also checked address in swagger. Method /utils/address/{address} returned that the address is Valid.
But still Explorer shows only an issue:
Unrecognized search pattern. Please try searching by entering address, block hash or transaction hash

**Comment by oskin1** [comment]
Can you provide the failing request example?
Search by address is supported and working fine so far.

**Comment by kushti** [comment]
@travek see ^ , please provide an example

**Comment by travek** [comment]
https://explorer.ergoplatform.com/en/search?query=9gSmatcPjFnCi6oUhZpTdwEtUe2FWz2n3kaYqwrLTaDauqqRFG7

**Comment by oskin1** [comment]
https://api.ergoplatform.com/addresses/9gSmatcPjFnCi6oUhZpTdwEtUe2FWz2n3kaYqwrLTaDauqqRFG7

There is no such address in the blockchain. Do you really have transactions with it?
Note, address generation doesn't imply the networks knows about it.

**Comment by travek** [comment]
@oskin1 
Thanks and clear. I have no transactions so far.
