### ISSUE TITLE
Node synchronization question/issue

### ISSUE THREAD

**Issue by travek** [ergoplatform/ergo#1074]
Hello!
Currently I'm running Ergo node v 3.2.2. My panel interface is always showing node status = Active synchronization.
How can I understand that  the node is catcjing up the network and finally I will be synchronized ?
How to check what is my node current synch block ?

**Comment by kushti** [comment]
In case of synced node, panel will show "Node is synced" and block height: 

![node-synced](https://user-images.githubusercontent.com/1972441/78027010-4a14f500-7365-11ea-9ad3-817dff02dc50.png)

Normal time to sync (for full node) is about 1.5 hrs now for a decent laptop. If it is much slower, please send logs and information about environment (operating system, Java version). You can use #support channel in the discord chat : https://discordapp.com/invite/kj7s7nb

**Comment by travek** [comment]
Hello!
I see that the node is not syncing - it may work more than 5 hours without getting sunc.
I'm on Win 10.
Java SE 12.0.1
Last log attached.
[ergo.log](https://github.com/ergoplatform/ergo/files/4409426/ergo.log)

**Comment by travek** [comment]
Thanks for help!
I missed some previous node versions and that was the reason of inconsistency in the data that is already stored.
I removed /history and /state completely and also some forlders in the /wallet folder.

Looking forward for some guidelines for the future!
