### ISSUE TITLE
Pass min box value to TransactionBuilder as a parameter

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo#1079]
instead of hard-coded BoxSelector.MinBoxValue

Extracted from #1071

**Comment by jozanek** [comment]
I cannot find any reference of MinBoxValue in TransactionBuilder, is this still relevant @greenhat ?

**Comment by greenhat** [comment]
> I cannot find any reference of MinBoxValue in TransactionBuilder, is this still relevant @greenhat ?

I've glanced through the rewritten version by @pragmaxim and I did not find it. Seems like it's no longer relevant.
