### ISSUE TITLE
Unexpected script execution failures due to exceptions during evaluation

### ISSUE THREAD

**Issue by jasondavies** [ergoplatform/ergo#1097]
This is an example of a real-world script deployed on mainnet as part of an ErgoMix implementation, where as far as I can tell, it does not work as the authors intended due to problems with exceptions that occur in branches of a conditional expression.

It's unclear to me (and presumably to the authors) whether the failure is due to a bug in the script, which would indicate insufficient understanding of ErgoScript's semantics, or if this is a bug in the interpreter.

The following script protects the "half-mix" boxes, and the final branch of the conditional, `proveDlog(gX)`, is intended to let Alice withdraw their funds using their one-time secret `x`.

However, in testing (with the executeWithContext API), this fails with an exception that looks like `None.get`.  After much tweaking of the script, I was finally able to work around the issue using `if (c1.isDefined) {} else {}` (also removing `.get` from the definition of `c1`).  I suspect the problem might be references to "undefined values" (that is, values that are undefined due to exceptions) in the crypto nodes proveDHTuple and proveDlog.  Another workaround would be to spend the box to outputs that have GroupElement registers to prevent the exceptions, but that seems like an ugly hack.

Exactly why `if {} else {}` fixes the issue and not adjusting the conditional e.g. `c1.isDefined &&` is also unclear to me.

I do think that we need to have:

(a) Much clearer documentation/specification of ErgoScript/ErgoTree and how exceptions should be handled.
(b) Ideally, a well-documented reference interpreter (doesn't matter if it's slow) that's easy to understand.

My feeling is that if a script has a conditional expression `A || B`, and either branch reduces to `true`, then `A || B` should reduce to `true` even if the other branch tries to access some undefined value. In the current implementation it seems that perhaps this is not the case.

```scala
  val halfMixContract = ctx.compileContract(
    ConstantsBuilder.create().item(
     "fullMixScriptHash", fullMixScriptHash
    ).build(),
    """{
      |  val g = groupGenerator
      |  val gX = SELF.R4[GroupElement].get
      |
      |  val c1 = OUTPUTS(0).R4[GroupElement].get
      |  val c2 = OUTPUTS(0).R5[GroupElement].get
      |  val u1 = OUTPUTS(0).R6[GroupElement].get
      |  val u2 = OUTPUTS(1).R6[GroupElement].get
      |
      |  (sigmaProp(
      |    OUTPUTS(0).value == SELF.value &&
      |    OUTPUTS(1).value == SELF.value &&
      |    u1 == gX && u2 == gX &&
      |    blake2b256(OUTPUTS(0).propositionBytes) == fullMixScriptHash &&
      |    blake2b256(OUTPUTS(1).propositionBytes) == fullMixScriptHash &&
      |    OUTPUTS(1).R4[GroupElement].get == c2 &&
      |    OUTPUTS(1).R5[GroupElement].get == c1 &&
      |    SELF.id == INPUTS(0).id
      |  ) && {
      |    proveDHTuple(g, gX, c1, c2) ||
      |    proveDHTuple(g, gX, c2, c1)
      |  }) || (proveDlog(gX))
      |}""".stripMargin
  )
```

**Comment by scalahub** [comment]
Can you give concrete example using `if` and not using `.get`, for the sample snippet below (for example)
     
      {   proveDlog(SELF.R4[GroupElement].get || (1 < 2) }

**Comment by jasondavies** [comment]
A concrete example of using if to prevent execution failure?

```
{
  val c = SELF.R4[GroupElement]
  if (c.isDefined) {
    proveDlog(c.get)
  } else {
    sigmaProp(1 < 2)
  }
}
```

**Comment by mehranagh20** [comment]
@jasondavies 
this also fails:
```
{
  val g = groupGenerator
  val gX = SELF.R4[GroupElement].get

  val c1 = OUTPUTS(0).R4[GroupElement]
  val c2 = OUTPUTS(0).R5[GroupElement].get
  val u1 = OUTPUTS(0).R6[GroupElement].get
  val u2 = OUTPUTS(1).R6[GroupElement].get

  (sigmaProp(
    OUTPUTS(0).value == SELF.value &&
    OUTPUTS(1).value == SELF.value &&
    u1 == gX && u2 == gX &&
    blake2b256(OUTPUTS(0).propositionBytes) == fullMixScriptHash &&
    blake2b256(OUTPUTS(1).propositionBytes) == fullMixScriptHash &&
    OUTPUTS(1).R4[GroupElement].get == c2 &&
    OUTPUTS(1).R5[GroupElement].get == c1.get &&
    SELF.id == INPUTS(0).id
  ) && {
    if (c1.isDefined) {
      proveDHTuple(g, gX, c1.get, c2) || proveDHTuple(g, gX, c2, c1.get)
    } else {
      sigmaProp(false)
    }
  }) || (proveDlog(gX))
}```
Can you share the full fixed script?

**Comment by jasondavies** [comment]
@mehranagh20 I'll post a more complete, tested version of that script soon, but the problem in your version is that you have a potential `IndexOutOfBoundsException` when accessing `OUTPUTS(1)`, as well as `c2` being used without checking it is non-empty.  If you move `if (c1.isDefined) {} else {}` conditional to protect the big `sigmaProp` it should be closer to what I have in mind for a complete fix.

**Comment by mehranagh20** [comment]
@jasondavies  We can safely assume the existence of `OUTPUTS(1)` because of fee box.
Also, as I've been testing, the `IndexOutOfBoundsException` happens in `proveDHTuple` and moving if doesn't do any good in my experience.

**Comment by mehranagh20** [comment]
I've not been able to fix `IndexOutOfBoundsException` exception by using `if` and other types of conditioning in this case. My workaround until now is to use a dummy default value:
`val c1 = OUTPUTS(0).R4[GroupElement].getOrElse(g)`
Which generally is not a good solution in my opinion and not always possible.

**Comment by jasondavies** [comment]
@mehranagh20 Fair point about there usually being two outputs (in theory a miner could agree to mine a transaction with no fee, but in practice this is going to be rare).  However, I still think moving the conditional is clearer, and in this particular case I believe it actually fixes the issue.  Remember that `c2` may be empty, so `c2.get` needs to be inside the conditional.  The trick is to think a bit more imperatively about evaluation errors.

This is my fixed version of the script, but it includes some other optimisations and I've only tested the `proveDlog(gX)` case just now:

```
{
  val fullMixScript = fromBase64("EADYAdYB5ManBQfrAs1yAc7bagHd5ManBAfkxqcGB3IB")
  val g = groupGenerator
  val gX = SELF.R4[GroupElement].get

  val c1 = OUTPUTS(0).R4[GroupElement]
  val c2 = OUTPUTS(0).R5[GroupElement]

  if (c1.isDefined) {
    val u1 = OUTPUTS(0).R6[GroupElement].get
    val u2 = OUTPUTS(1).R6[GroupElement].get
  
    sigmaProp(
      OUTPUTS(0).value == SELF.value &&
      OUTPUTS(1).value == SELF.value &&
      u1 == gX && u2 == gX &&
      OUTPUTS(0).propositionBytes == fullMixScript &&
      OUTPUTS(1).propositionBytes == fullMixScript &&
      OUTPUTS(1).R4[GroupElement] == c2 &&
      OUTPUTS(1).R5[GroupElement] == c1 &&
      CONTEXT.selfBoxIndex == 0
    ) && (
      proveDHTuple(g, gX, c1.get, c2.get) ||
      proveDHTuple(g, gX, c2.get, c1.get)
    )
  } else {
    sigmaProp(false)
  } || proveDlog(gX)
}
```

**Comment by jasondavies** [comment]
Note that `u1` and `u2` have also been moved inside the conditional.  Any `Option[A].get` call might fail if the value is empty.  The only one that we don't care about is `gX` as we always expect this to be non-empty.

**Comment by jasondavies** [comment]
Additional thoughts: what if we expect the withdrawal to pay to a contract that *does* require R4/R5/R6 registers?  We would need better defensive checks to handle this case e.g. `c1.isDefined && c2.isDefined && u1.isDefined && u2.isDefined`.

**Comment by scalahub** [comment]
@jasondavies in this particular context, we can assume that withdraw will be to a simple box, but your point is valid that there may be other cases, when c1 is defined in both branches and c2 in one branch only, etc. Also, what is the benefit of `CONTEXT.selfBoxIndex == 0`?

**Comment by jasondavies** [comment]
`CONTEXT.selfBoxIndex == 0` should be cheaper both in terms of ErgoTree serialisation and costing (I haven't actually checked this).
