### ISSUE TITLE
Handle DB issues explicitly 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1120]
Currently LDBKVStore.update() just prints error messages into the log (since 3.3.0). It is better to not to swallow the DB errors and process them on higher levels.

**Comment by pragmaxim** [comment]
@kushti  https://github.com/ergoplatform/ergo/pull/1414

I'm also worried about this possible "silent failure" https://github.com/ergoplatform/ergo/blob/e6086e23ecd45f1e01a3e4c0344f003cec1a5b11/src/main/scala/org/ergoplatform/nodeView/state/ErgoStateReader.scala#L32

If the deserialization was failing for some reason, there would be empty state context used everywhere. Impossible to troubleshoot.

**Comment by pragmaxim** [comment]
Got fixed at https://github.com/ergoplatform/ergo/pull/1414
