### ISSUE TITLE
Make a test for ErgoWalletActor.generateTransactionWithOutputs

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1121]
generateTransactionWithOutputs is big and logic is not trivial, so a test for it would be very helpful

**Comment by pragmaxim** [comment]
:wave: I'm taking this one ... I'm gonna have to turn it into state machine, extracting the business logic from the actor which should be fairly easy.

While reading it I noticed of few bugs that I can fix on the way : 
https://github.com/ergoplatform/ergo/blob/6ad1132ffd1278403d51504cf818f1d660699b3d/src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletActor.scala#L787
this should be : 
```
    if (selectionResult.changeBoxes.nonEmpty) {
      require(changeAddressOpt.isDefined, "Does not have change address to send change to")
    }
```
Another strange thing is that when creating output boxes , we use `stateContext.currentHeight` height for the box but `registry.fetchDigest().height` for `change` box, so one `UnsignedErgoTransaction` then contains output boxes of different height ... I guess it should be unified to either one of these.
