### ISSUE TITLE
Question: check of seed phrase

### ISSUE THREAD

**Issue by travek** [ergoplatform/ergo#1138]
Hello Team!
 
Currently I'm loggin into my wallet with API key. I want to check that the seed phrase I have for this wallet is correct and corresponds to the API key. How I can do such check ? In other words, how I can check the mapping seed_phrase -> API key ?

**Comment by kushti** [comment]
@travek seed has no correspondence with an API key. API key is needed to protect sensitive API methods from unauthorized access (e.g. if API port is open to external world accidentally or not). Seed is used to derive private keys from (but phrase is forgotten after wallet initialization, where phrase converted into seed bytes).

**Comment by travek** [comment]
@kushti,
1) how I can check that the seed phrase that I have recorded is correct and the private keys are derived from this seed phrase ? For instance, there's a feature in a Deadulus wallet to check the correctness of wallet seed phrase. Can I somehow check that my seed phrase is OK ?
2) There's an API method to restore a wallet. How it can be used if I don't want to restore but just to check correctness of seed phrase ?
3) There's a .json file in the .\wallet\keystore\ folder. Does this file store the private key ? For example I can backup it, use an API for wallet restoration and compare existing .json and the new one. But if they will be different will it be enought just to copy back the old .json file ? No other wallet files will be changed during wallet restoration API ?

**Comment by kushti** [comment]
@travek ,

Thanks for the suggestion on API method to check mnemonic, made an issue on that: https://github.com/ergoplatform/ergo/issues/1150 .

A .json file in the .\wallet\keystore\ is storing your private key in encrypted form. You don't need to use wallet restoration with it, just put into the folder and unlock. Two .json files encrypting the same seed would be different as the encryption is randomized.

/wallet/restore doing the same as  /wallet/init but for the mnemonic provided (in case of /init, the mnemonic is being generated by the wallet).

**Comment by travek** [comment]
Thanks, clear.
Waiting for #1150 implementation
