### ISSUE TITLE
Memory leak in ErgoWalletActor 

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo#1189]
Originally posted here https://github.com/ScorexFoundation/sigmastate-interpreter/issues/687

The root cause is that the same ErgoProvingInterpreter stored in WalletVars and reused during the whole lifecycle of the actor. It should be recycled, from time to time.

Alternatively, the IRContext stored in the prover (and which accumulates all compiled expressions) should be recycled, for example a fresh IRContext can be used for each new block.

IRContext should never be part of the global state, it should instead always have temporary lifetime (like a local variable)

**Comment by kushti** [comment]
As signing operations are not synced with blocks or other blockchain events in general case, the only solution is to reset the context on each sign() call it seems.

**Comment by kushti** [comment]
Fixed in #1193
