### ISSUE TITLE
Release binaries for Windows and MacOS

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1194]
native-packager plugin for SBT should do the job

**Comment by deadit** [comment]
How do you see the result of this task?
I've release binaries for MacOS, but node don't work.
![image](https://user-images.githubusercontent.com/26635501/94369584-4a633280-00f3-11eb-818a-46d54fe9971c.png)

**Comment by abebeos** [comment]
@kushti , @glasgowm148 , could you separate this into 2 bounties, one for Win, one for MAC?
