### ISSUE TITLE
Mnemonic phrase appears only briefly on wallet initialization

### ISSUE THREAD

**Issue by jclarkv** [ergoplatform/ergo#1212]
Ergo version: 3.3.4
Platform: MacOS 10.15.17
Browsers: Brave 1.15.72 **and** Safari 14.0

What I expected: on wallet initialization I would see mnemonic phrase long enough to be able to copy the phrase needed to restore wallet on different machine.

What happened: 
Brave: wallet mnemonic appears only **briefly** (< 1 second). See video: https://cln.sh/6RWPAq
Safari: wallet mnemonic does **not appear at all.** See video https://cln.sh/Kxypny (this is the case even with pop-up blocker OFF for 127.0.0.1)

**Comment by kushti** [comment]
@jclarkv thanks! @deadit please take a look

**Comment by kushti** [comment]
@jclarkv confirmed! We're working on a fix!

**Comment by kushti** [comment]
@jclarkv fix is going into 3.3.5 ! Please provide your Ergo address to get rewarded for proper testing (PM me in TG: @kushti_ru , or email EF: team@ergoplatform.org )

**Comment by jclarkv** [comment]
I can confirm this now works as expected.
