### ISSUE TITLE
/block/lastHeaders/{count} doesn't work

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#124]
![screenshot](https://user-images.githubusercontent.com/1972441/35452053-5f15a0c8-02d6-11e8-889e-40cc02868362.png)

**Comment by catena2w** [comment]
API route works correct, openAPI description is fixed here -https://github.com/ergoplatform/ergo/pull/122/commits/0fdaa49945d6721ddd216305bdc2800539ac8162
