### ISSUE TITLE
Alternative approaches to forks comparison 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#125]
Currently, two peers are exchanging lists of block ids of certain size and try to find a common block. Then a peer which decides that it is younger tries to upload blocks from another peer. 

Maybe it is better to exchange with some number of headers, not ids. for example, we can adopt interactive KLS16 protocol, or non-interactive KMZ17 (with reasonable m&k parameters).

**Comment by catena2w** [comment]
I propose to leave current comparison, but allow gaps in syncInfo like in Bitcoin

**Comment by catena2w** [comment]
Looks like this update may be done without any breaking changes, so lowered the priority

**Comment by kushti** [comment]
done in syncv2 message
