### ISSUE TITLE
Introduce MaxTransactionCost parameter (in v4.0)

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo#1250]
1) Proposed parameter `maxTransactionCost: Long` which limits the cost of single transaction.

2) The motivation is described in [EIP-0008 proposal](https://github.com/ergoplatform/eips/pull/11/files#diff-9b602c1e78634baac081e62dfa8fdc366fdc0fcfe30a5d02c5f2afeea03b431aR154)

3) This is in addition to [MaxBlockCost](https://github.com/ergoplatform/ergo/blob/ef6bdcc61c46a23a8c7c2e45a5bd007ca605d35d/src/main/scala/org/ergoplatform/settings/Parameters.scala#L65). 

4) In particular it can be used to more accurately [assign cost for transactions which fail verification](https://github.com/ergoplatform/ergo/blob/919bcd41c78a92b42945f5b637291b4e4dc92df5/src/main/scala/org/ergoplatform/modifiers/mempool/ErgoTransaction.scala#L210)

5) The current implementation essentially invalidated the whole collection of transaction in `ErgoState.execTransactions` where as a more flexible implementation using maxTransactionCost can invalidate (and filter out) only one transaction.

6) So this parameter CAN be used in block candidate preparation. In addition, mined block validation MUST be changed to also respect this parameter and forbid transactions whose cost > MaxTransactionCost.

7) This parameter will be particularly important in v5.0 with JIT based costing where MaxBlockCost can be 10x increased due to much more efficient and scalable ErgoTree interpreter. This will allow us to potentially scale blocks to 1000 of transactions. At this scale, having single cost limit is too rigid and is subject to _verifier's dilemma_ (see description in EIP-0008 proposal).

**Comment by kushti** [comment]
There's no need in protocol-level parameter. Please rework the issue towards client-side parameter (used in mining only).
