### ISSUE TITLE
Wallet rescan from a given height rather than from beginning

### ISSUE THREAD

**Issue by scalahub** [ergoplatform/ergo#1256]
It will be preferable if we can ask the node to rescan blockchain and the wallet from some given height instead of from the beginning.
Many dApps rely on recently issued transactions so it is often wasteful to rescan the entire blockchain

**Comment by greenhat** [comment]
Oracle-core would very much appreciate this feature implemented. It'd minimize pool downtime on update significantly. See

**Comment by kushti** [comment]
> Oracle-core would very much appreciate this feature implemented. It'd minimize pool downtime on update significantly. See [ergoplatform/oracle-core#242](https://github.com/ergoplatform/oracle-core/issues/242) for details.

It is implemented long time ago, anything needed?

**Comment by greenhat** [comment]
> > Oracle-core would very much appreciate this feature implemented. It'd minimize pool downtime on update significantly. See [ergoplatform/oracle-core#242](https://github.com/ergoplatform/oracle-core/issues/242) for details.
> 
> It is implemented long time ago, anything needed?

Oh, right. My bad. I forgot that this feature exists. We even used it initially but we had to disable it because the wallet does not see anything below the given height, including the user's coins. Is it intended to work this way?

**Comment by pragmaxim** [comment]
There is a related PR https://github.com/ergoplatform/ergo/pull/1723
