### ISSUE TITLE
Hard fork mining

### ISSUE THREAD

**Issue by neal-zhu** [ergoplatform/ergo#1268]
Hi, guys:

  I'm developing a mining pool for ergo(after hard fork) and I'd like to know how to set the node up in testnet? It seems /mining/candidate still returns old response before hard fork.

**Comment by kushti** [comment]
@neal-zhu please provide details, I do not quite understand. Testnet passed hard-fork already.

For working with testnet, the simplest option is to run 4.0.2 with:

```
java -jar -Xmx3G -Dlogback.stdout.level=DEBUG ergo-4.0.2.jar --testnet -c testnet.conf
```

where testnet.conf like:

```
ergo {
  networkType = "testnet"
  
  node {
    mining = true
  }

}

scorex {

 network {
    bindAddress = "0.0.0.0:9020"
    nodeName = "ergo-testnet-4.0.0"
  }

 restApi {
    # Hex-encoded Blake2b256 hash of an API key. Should be 64-chars long Base16 string.
    # Below is hash corresponding to API_KEY = "hello" (with no quotes)
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
```

**Comment by neal-zhu** [comment]
response of /mining/candidate:
`{
  "msg" : "603a92d9031a1c00287c658b789d8c1ff75c1cbd29a39d137b33182048155bd6",
  "b" : 115792089237316195423570985008687907852837564279074904382605163141518161494337,
  "pk" : "02390d6f8a70f0d1ff02e2a8cd1ae0af63b4da55bf6abaad3e053ad149bca1f58e"
}`

while the CandidateBlock in src is like:
````
object CandidateBlock {

  implicit val jsonEncoder: Encoder[CandidateBlock] = (c: CandidateBlock) =>
    Map(
      "parentId" -> c.parentOpt.map(p => Algos.encode(p.id)).getOrElse("None").asJson,
      "version" -> c.version.asJson,
      "nBits" -> c.nBits.asJson,
      "stateRoot" -> Algos.encode(c.stateRoot).asJson,
      "adProofBytes" -> Algos.encode(c.adProofBytes).asJson,
      "timestamp" -> c.timestamp.asJson,
      "transactions" -> c.transactions.map(_.asJson).asJson,
      "transactionsNumber" -> c.transactions.length.asJson,
      "votes" -> Algos.encode(c.votes).asJson,
      "extensionHash" -> Algos.encode(c.extension.digest).asJson
    ).asJson
}
````

How can I get a candidate block like that?

**Comment by kushti** [comment]
@neal-zhu /mining/candidate returns data a reference external miner is working on, "msg" is hash of  block candidate fields.

If needed, I can do API method to obtain candidate json, but then you need to do header fields (from the candidate) serialization on your side

**Comment by neal-zhu** [comment]
We are developing a mining pool for ergo. Can you guys provide a C version of solution verify code? Thanks a lot

**Comment by neal-zhu** [comment]
Could you please to tell me how to convert response of /mining/candidate to a mining stratum result like:
   
```
var res = JSON.stringify({
            coinb1: "xx",
            nbits: "yy",
            prevHash: "zz",
            extraNonce1: "I got this",
            extraNonce2Size: 4,
        });
```

It would be really nice if you can help me with this. And a simple C version of solution verify codes will be great!

**Comment by kushti** [comment]
@neal-zhu there's stratum proxy already done https://github.com/mhssamadani/ErgoStratumProxy , may it help you ? C verification can be found in miners I guess

AMD miner https://github.com/mhssamadani/Autolykos2_AMD_Miner
Nvidia miner: https://github.com/mhssamadani/Autolykos2_NV_Miner

**Comment by neal-zhu** [comment]
emm, as I see, ErgoStratumProxy is more like an adaptor to me. It connects to a stratum pool and provides the same http interface as the ergo node to miner?
Am I right? I want to develop a mining pool like which ErgoStratumProxy connects to.

**Comment by kushti** [comment]
@neal-zhu then you need for Stratum Server too I guess https://github.com/mhssamadani/ErgoStratumServer

**Comment by neal-zhu** [comment]
Thank you very much, there is still a minor problem that I am not sure why. In our test, our pool get some low diff shares from miner, could you please do me a favor take a look at this [issue](https://github.com/mhssamadani/Autolykos2_NV_Miner/issues/9 )

**Comment by kushti** [comment]
@neal-zhu pinged miner devs, that's all I can do
