### ISSUE TITLE
Default value for inclusionHeight

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1294]
"I think I found a bug in the reference node implementation.  When looking at a specific transaction using the swagger UI provided on my locally running full node (be8eda4d01d86f7b9879d19dec749154691d4ab68bd8aab34053009bfac088ff) the number of confirmations is showing a negative number.  Specifically, it is -264366 which just looks like the negative of the "inclusion height".  When I view that transaction via the explorer website it showed something more normal (at the time of writing this the number of Confirmations shows "163082").  Could it be an overflow of of the type used to hold numConfirmations?"

"it seems fullHeight which is set to 0 by default is only updated when the NodeView is updated
https://github.com/ergoplatform/ergo/blob/bdab15f651aaf0a1b9d7271a9347f696da57c474/src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletActor.scala#L256"

So fullHeight update in some better way is needed.

**Comment by l15k4** [comment]
Could this cause a regression? I switched from 4.0.4 to 4.0.7 and the blockchain is in `synced` state but `current height` is behind and logs always show `0 persistent blocks to be downloaded` ... no matter how much time and peers is connected.
