### ISSUE TITLE
FR : Disabling Log file generation

### ISSUE THREAD

**Issue by benda95280** [ergoplatform/ergo#1299]
Could it be possible to disable Log file generation ?

Thanks.

**Comment by kardall** [comment]
Disable would be nice, but another nice one would be to just capture errors only instead of getting gigs of log entries that mean nothing and have to be parse.

Perhaps Swagger could even have a log API entry where it could log to the API and store it to be accessed via the node page.

**Comment by joshp23** [comment]
being able to control the logfile output would be great. only running this afternoon and I have almost 2G logfile size. That's more than I care to even try to load.

**Comment by glasgowm148** [comment]
Will add to documentation

`java -jar -Xmx3G -Dlogback.stdout.level=WARN -Dlogback.file.level=ERR ergo.jar --mainnet -c mainnet.conf`
