### ISSUE TITLE
node start errors

### ISSUE THREAD

**Issue by fragilegirl** [ergoplatform/ergo#1302]
19:08:48.239 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(.\ergo.conf),Some(MainNet))
19:08:48.264 INFO  [main] o.e.settings.ErgoSettings$ - Running in mainnet network mode
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: API key hash must be set
        at scala.Predef$.require(Predef.scala:281)
        at org.ergoplatform.ErgoApp.<init>(ErgoApp.scala:38)
        at org.ergoplatform.ErgoApp$.main(ErgoApp.scala:203)
        at org.ergoplatform.ErgoApp.main(ErgoApp.scala)

**Comment by tetero** [comment]
I have this issue as well following the official tutorial. Windows 10 / JDK 11 LTS (also tried JDK 15, same issue)

**Comment by zena1** [comment]
have you tried it with older version of JDK

**Comment by zena1** [comment]
oh you cant just noticed that wtf i cant figure it out this is frustrating

**Comment by zena1** [comment]
try this it worked for me to start node 
ergo {
  node {
    mining = false
  }
}

scorex {
 restApi {
    # Hex-encoded Blake2b256 hash of an API key. 
    # Should be 64-chars long Base16 string.
    # below is the hash of the string 'hello'
    # replace with your actual hash 
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}

**Comment by petabyteHD** [comment]
Same error for me.

zena1, with that code your secret password is "hello" your node will not be safe
