### ISSUE TITLE
Implement SigVerify function on ergo scripts

### ISSUE THREAD

**Issue by vorujack** [ergoplatform/ergo#1306]
In ErgoScript we need to check sign verification function. this function must verify digital signature
 see [Curve25519](https://en.wikipedia.org/wiki/Curve25519)

**Comment by kushti** [comment]
@vorujack there's no dedicated function in ErgoTree/Script for that, but as there's access for group operations, you can implement signature validation in a script. ErgoTree example is providing in signed oracle data context in https://github.com/ScorexFoundation/sigmastate-interpreter/blob/79a661081bd38ded4c9888c93a78b7e9ab6b7d7f/sigmastate/src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala#L42 .

We can provide ErgoScript alternative for you
