### ISSUE TITLE
Java Heap Size Error

### ISSUE THREAD

**Issue by mehran-njz** [ergoplatform/ergo#1321]
Hi
I have configured .conf  file and started to sync the full node. but suddenly the process stopped by an error. the log is attached by this comment.
this is the second time that I'm facing this error in the last week. I have installed openjdk 11 lts on a fresh windows installation but I got the error again.
[hs_err_pid3344.log](https://github.com/ergoplatform/ergo/files/6216169/hs_err_pid3344.log)

**Comment by kushti** [comment]
@mehran-njz please run with -Xmx flag, e.g. java -jar -Xmx3G ergo-4.0.8.jar  --mainnet -c mainnet.conf
