### ISSUE TITLE
Missing modifiers cache rework

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#134]
Currently, toDownload structure in DeliveryTracker is used to store modifiers to download, and the structure is initially populated with missedModifiersForFullChain(). There are many problems with this approach, in particular, we need to store modifiers in (potentially, big) cache for limited time, and no chance to restore a modifier after removal from the cache.

As a solution, it is reasonable to have persistent cache of modifiers to download in History, and a method to get limited number of records in the cache.

**Comment by catena2w** [comment]
Already fix + more rework in https://github.com/ergoplatform/ergo/issues/342
