### ISSUE TITLE
HELP!!!! Submit  to node got error

### ISSUE THREAD

**Issue by neal-zhu** [ergoplatform/ergo#1346]
When we submit to our node , we got error like:

```
{\n  \"error\" : 500,\n  \"reason\" : \"internal.error\",\n  \"detail\" : \"Invalid miner state\"\n}
The server was not able to produce a timely response to your request.\r\nPlease try again in a short while!
```
and it timeout twice(timeout is set to 500ms)

**Comment by kushti** [comment]
@neal-zhu what version ? Any details? Can you share your node's logs?

**Comment by neal-zhu** [comment]
We updated our node from 4.08 to 4.10 and it looks all good now.

**Comment by kushti** [comment]
@neal-zhu I guess maybe related to /wallet/transactions being called in parallel
