### ISSUE TITLE
[Maybe Solved] Java Heap Size and Full Node Crashing on Low RAM Devices (<=4GB)

### ISSUE THREAD

**Issue by jhbarros** [ergoplatform/ergo#1358]
Setup:
1) Headless Debian 10 Buster (Stable), Core i5 and 4GB Ram;
2) Deployment from scratch based on "wiki/Set-up-a-full-node";
3) Uptime estimated in 4-6h before crashing;

It appears that the default maximum allocation of memory in Java is about 25% of the system's memory, and after some time, it crashes the node.

Checking Java heap size limits:

`java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"`

The default command to start the node:
`java -jar ergo-4.0.10.jar --mainnet -c ergo.conf`

Trying to change maximum heap size:
`java -jar -Xmx2G ergo-4.0.10.jar --mainnet -c ergo.conf`

It appears to solve the problem (more testing needed). Sorry if misused terms related to Java, as it is unexplored territory for me.

**Comment by kushti** [comment]
-Xmx flag is needed for some JVM versions at least at the moment. Newer build maybe will solve the issue
