### ISSUE TITLE
testnet network does not work

### ISSUE THREAD

**Issue by podvodnik** [ergoplatform/ergo#1359]
4.0.10 version cannot find any peer to connect to in testnet.
This node has problems with 
213.239.193.208:9020
Wrong magic bytes, expected 2001, got -49-124-104-118

**Comment by kushti** [comment]
The testnet got relaunched , please use non-default config or 4.0.11 candidate https://www.ergoforum.org/t/testnet-relaunched-may-23rd-2021/1395 . For solving wrong magic bytes, the latter is recommended, as the issue is fixed there: https://github.com/hyperledger-labs/Scorex/pull/396

**Comment by nevata** [comment]
4.0.11 cannot sync, at height 400

**Comment by kushti** [comment]
@nevata confirmed, investigating

**Comment by kushti** [comment]
@nevata found an issue, fixing, will be done tomorrow hopefully

**Comment by nevata** [comment]
Okay

**Comment by nevata** [comment]
Yes, thank you.
