### ISSUE TITLE
Bootstrapping via UTXO set snapshot

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1366]
Ergo block header has a commitment to current UTXO set, thus it is possible to bootstrap new nodes with UTXO set snapshot (which is similar to "fast" mode in geth client for Ethereum). Implementation in client is needed. 

Maybe something can be imported from this very old attempt https://github.com/ergoplatform/ergo/pull/550

**Comment by kushti** [comment]
Implementation in https://github.com/ergoplatform/ergo/pull/1444, I am extracting code from it part by part to merge with master

**Comment by abebeos** [comment]
> Implementation in #1444, I am extracting code from it part by part to merge with master

I assume it is not possible to split this into multiple PRs?

**Comment by kushti** [comment]
> > Implementation in #1444, I am extracting code from it part by part to merge with master
> 
> I assume it is not possible to split this into multiple PRs?

it is what I am doing to ease reviewing process , extracting PRs one by one

**Comment by abebeos** [comment]
> it is what I am doing to ease reviewing process , extracting PRs one by one

Ok, nice! It's just not visible, as you've not linked the PR's (assuming part 1,2,3) back to the issue (via the usual 're #1366').

Alternatively add a list of prs manually to the issue text, like

- [ ] #1947
- [ ] #1444

This is more or less standard-procedure and ensures everyone sees what's happening
