### ISSUE TITLE
Too many orphan blocks

### ISSUE THREAD

**Issue by neal-zhu** [ergoplatform/ergo#1379]
Our pool recently is getting many orphan blocks(5%). and I think there is some problem with block propagation.
For example: block of height of 501261:
our pool submit soltuion first(about 2 seconds earier  according to explore), here is log of node:
`05:38:36.538 INFO  [tor.default-dispatcher-13] o.e.mining.ErgoMiner - New block mined, header: Header({"extensionId":"acbce6c3478e521bc967f11ac3d925de6028bfa6f5482b4a31f031c9ae85f27c","difficulty":"2262769160159232","votes":"000000","timestamp":1622497043830,"size":220,"stateRoot":"2770d052e5a746b5855f80b749593b99d1b2d35cf935bd95b95ec3cb5c0cced515","height":501621,"nBits":117967354,"version":2,"id":"e483b173aa4a8ab597822d89e30a2e81318f55b006c88048d7ddd3abb0c789ce","adProofsRoot":"d4ddadf00fa9ae9892e9d0285dc3d952b0e0c37a8fc1423ec11a251055596c9a","transactionsRoot":"ef3b1780f47ac579b4690724e36fd4c7de3f8c98b9e397f5c852b909413e5232","extensionHash":"ffd7028fefcb3df779e274b06e7564b9d5feda11857d466152765458b9d31f0d","powSolutions":{"pk":"030d6e8fabf1fbddba33b51e6822e3927a31528b4287e5a0f11760c7cad3ee8b18","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"00cb0002a3f7bfba","d":0},"adProofsId":"e39da55390f76a7dca04c9c47b90b72a09efd8866d518a0ad9fee87e7ede58df","transactionsId":"ae94b6392ad6638285daa10c1c7198cd3aa153b26104a83b2c6b22fc0f3b4950","parentId":"bf270db8f65a93ff5f89fddf8a02d2181724376572aa2319048f01fc07c5e2bf"})` 
But after 3 seconds, got a log:
`05:38:39.330 INFO  [tor.default-dispatcher-17] o.e.n.h.ErgoHistory$$anon$3 - New orphaned header c5dc3f752b399d45ece967d11dd3a278eec64b4db3f2884f6e5c8abe5fd038d1 at height 501621 with score 351390268496868802560`
And we have three nodes connected, even our connected nodes have not received the propagation of our block.
Please help us, it costs us a lot!
@mmahut @jasondavies @knizhnik @greenhat @polarker sorry for the ping but we really need your help.

**Comment by neal-zhu** [comment]
Guys we really need help!

**Comment by neal-zhu** [comment]
@jasondavies @mmahut @knizhnik @greenhat please help us out

**Comment by neal-zhu** [comment]
@jasondavies @mmahut @knizhnik @greenhat Please take a look at this

**Comment by polarker** [comment]
@neal-zhu did you try the following two tricks:
1. query for blocks template every 500 milliseconds
2. increase the number of incoming and outgoing connections of your full node

**Comment by neal-zhu** [comment]
1. we query block template every 200ms, and I will change to 500ms as you said
2. how ?

**Comment by polarker** [comment]
> 1. we query block template every 200ms, and I will change to 500ms as you said
> 2. how ? @polarker

1. 200ms should be even better
2. try the following and see
```
scorex. network. maxConnections = 100
scorex. network. syncIntervalStable = 1s
```

**Comment by neal-zhu** [comment]
thanks, I will try it out soon. Could you please take a look at this issue https://github.com/ergoplatform/ergo/issues/1376 .
It seems our node has some problem with broadcasting our block. We has three nodes(two in china and one in US), but they cannot connect to each other enven if we add them in peers

**Comment by neal-zhu** [comment]
Add 
`scorex. network. maxConnections = 100
scorex. network. syncIntervalStable = 1s`
into our conf, and it made 10% of our share become stale.

**Comment by polarker** [comment]
What is your previous stale rate ?

**Comment by neal-zhu** [comment]
1%, our node consume too much bandwidth at 14:00. We fixed it by  deleting the conf and restarting node

**Comment by polarker** [comment]
try only `scorex. network. maxConnections = 100` then. `syncIntervalStable` might consume too much bandwidth

**Comment by neal-zhu** [comment]
Not working, still get a 2% of orphan rate. Any plans on optimizing your block broadcasting?

**Comment by neal-zhu** [comment]
@polarker @jasondavies @knizhnik please help us. We are losing ergo every day because of this. I think 2% orphan rate is way too high for 2min block time

**Comment by neal-zhu** [comment]
@kushti

**Comment by neal-zhu** [comment]
@kushti

**Comment by neal-zhu** [comment]
@kushti @polarker @mmahut @knizhnik @greenhat 
Could any one please take a look at this

**Comment by neal-zhu** [comment]
@kushti @polarker @mmahut @knizhnik @greenhat 
Guys we need your help

**Comment by polarker** [comment]
> @kushti @polarker @mmahut @knizhnik @greenhat
> Guys we need your help

Maybe your could ask in the discord channel

**Comment by CoFix** [comment]
@neal-zhu 
Which node version are you using? 

And what is your ergo.conf setting?

**Comment by neal-zhu** [comment]
@CoFix 4.013 with three nodes (two in chian and one in usa)

**Comment by neal-zhu** [comment]
> > @kushti @polarker @mmahut @knizhnik @greenhat
> > Guys we need your help
> 
> Maybe your could ask in the discord channel
I did concat to sam but there is no progress

**Comment by neal-zhu** [comment]
Our blocks sometimes turned out to be orphan blocks even if we submit our solution 1-2 seconds before other node @kushti @CoFix @mmahut @polarker please help us

**Comment by glasgowm148** [comment]
Please join the ergo discord for support if this issue persists.

https://linktr.ee/ergoplatform

Closing for historic. I believe this was due to the Chinese firewall?
