### ISSUE TITLE
Basic mining issues - sorry am a noob

### ISSUE THREAD

**Issue by BountyHAHC** [ergoplatform/ergo#1388]
ey guys if u could help me that would be great

I followed the guidelines and I started to mine Ergo

[autolykos]

wallet=

coin=ERGO

rigName=alexi

email=alexi@monicoin.io

Then I tried to do dual mining – here is the info

[autolykos]

wallet=

coin=ERGO

rigName=Alexi Ergo

email=alexi@monicoin.io

sortPools=true

pool1 = ergo-eu1.nanopool.org: 11433

pool2 = ergo-eu2.nanopool.org:14433

pool3 = ergo-us-east1.nanopool.org:14433

pool4 = ergo-us-west1.nanopool.org 14433

pool5 = ergo-jp1.nanopool.org:14433

pool6 = ergo-asia1.nanopool.org:14433

pool7 = ergo-jp1.nanopool.org:14433

pool8 = ergo-au1.nanopool.org:14433

[RandomX]

wallet =

rigName = Alexi Monero

email = alexi@monicoin.io

sortPools=true

pool1 = xmr-eu1.nanopool.org:14433

pool2 = xmr-eu2.nanopool.org:14433

pool3 = xmr-us-east1.nanopool.org:14433

pool4 = xmr-us-west1.nanopool.org:14433

pool5 = xmr-asia1.nanopool.org:14433

But then I messed up something – here is the log file – I don’t know what I did wrong

Ergo: trying to use “stratum” mining protocol… to disable this behavior, specify: protocol=JSON-RPC

When I went back to the old set up things were the same. I couldn’t fix the issue - not sure what to do next

Would appreciate the help.

**Comment by glasgowm148** [comment]
Please join the [support chats](https://linktr.ee/ergoplatform) if the issue persists
