### ISSUE TITLE
Bad API

### ISSUE THREAD

**Issue by neo4uo** [ergoplatform/ergo#1389]
I have checked several times and my api in my config is being copied and pasted to open wallet and I keep getting bad api...I wrote down the string I used to create the API when setting up the wallet. Is there a way to use the string to get the api and make sure it's the right api in my configuration and it did not get changed...?
Thanks

**Comment by glasgowm148** [comment]
Can happen during database corruption on unexpected shutdown. Please join the [support chats](https://linktr.ee/ergoplatform) if the issue persists
