### ISSUE TITLE
REST API doesn't work with scorex configuration at 4.0.12 version

### ISSUE THREAD

**Issue by 0stein** [ergoplatform/ergo#1399]
I was runnig ergo node with ergo.json config file below and rest api was enabled at 4.0.11.
After I upgrade ergo node 4.0.12, there is no established api address.

`
{
    "ergo": {
        "directory": "/my/ergo/directory"
    },
    "scorex": {
        "network": {
            "bindAddress": "0.0.0.0:4445"
        }
        "restApi": {
            "bindAddress": "0.0.0.0:3000"
        }
    }
}
`
4.0.11 version
![image](https://user-images.githubusercontent.com/69712107/123718146-5fa30280-d8b9-11eb-96f1-5e6a14e37778.png)

4.0.12 version
![image](https://user-images.githubusercontent.com/69712107/123718171-70ec0f00-d8b9-11eb-91b4-6fcec7654918.png)

**Comment by glasgowm148** [comment]
Please open an issue if the issue persists on the new version. Closing for historic
