### ISSUE TITLE
Determining whether the node is still syncing and calculating sync progress

### ISSUE THREAD

**Issue by oliverw** [ergoplatform/ergo#1401]
I'm trying to determining whether the node (testnet) is still syncing and if it is, calculate the current sync progress using the REST API but I can't find the datapoints in the Swagger Spec. Any pointers?

**Comment by pragmaxim** [comment]
You can compare `headersHeight` with `fullHeight` from `http://127.0.0.1:9053/info` ... if `headersHeight` is ahead it means it is still syncing

or `headersHeight` with `walletHeight` from `http://127.0.0.1:9053/wallet/status` if you want even wallet to be synced

**Comment by kushti** [comment]
Calculating progress will be possible after #1441 being merged

**Comment by glasgowm148** [comment]
> Calculating progress will be possible after #1441 being merged

How does this help calculate progress for the local node sync?
