### ISSUE TITLE
Not identifying Conf and API wont work

### ISSUE THREAD

**Issue by boothjj123** [ergoplatform/ergo#1404]
I'm going off the tutorial. I'm executing it exactly... trying to be part of the team and have very little experience. I would love to get a node up and be part of an oracle pool. I'm willing to pay someone for help

**Comment by boothjj123** [comment]
Willing to pay for the education/help

**Comment by kushti** [comment]
What is a problem you have with the node?

**Comment by boothjj123** [comment]
Alex,
  I figured it out. I should have gone back on and closed out the request. Sorry about that.
Thank you for the response.
Jon Booth
    On Wednesday, September 22, 2021, 05:07:32 AM EDT, Alexander Chepurnoy ***@***.***> wrote:  
 
 


What is a problem you have with the node?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by def670** [comment]
> Alex,   I figured it out. I should have gone back on and closed out the request. Sorry about that. Thank you for the response. Jon Booth On Wednesday, September 22, 2021, 05:07:32 AM EDT, Alexander Chepurnoy ***@***.***> wrote: What is a problem you have with the node? 

What issue were you running into?  I am trying to get a node functional - running off the tutorials as well installing on linux (tried 18.04 an 20.04).  
- with the installer script and the vanilla ergo.conf suggested:

  ergo {
    directory = ${ergo.directory}"/.ergo"
    node {
        mining = false
    }
    wallet.secretStorage.secretDir = ${ergo.directory}"/wallet/keystore"
}

the terminal says its starting but it seems to stall there (i know thats the develop branch - i get same results with the main:

def@ergo:~/ergo$ curl -s https://raw.githubusercontent.com/ergoplatform/ergo/develop/ergo-installer.sh | sh -s -- --mode=full --app-dir=/home/def/ergo --api-key=passwordhere
Ergo node with config file will be installed into '/home/def/ergo' directory and will be named as 'def-ergo' and has API key 'passwordhere'.
Ergo directory '/home/def/ergo' already exists.
Latest known Ergo release: v4.0.13, downloading it to /home/def/ergo/ergo.jar with overwrite...
Ergo was downloaded to /home/def/ergo/ergo.jar
Executing ergo node to obtain API key hash.......................................................................................................................................................................................

the ... just go on forever - nmap and lsof show that api ports not open.

I have been able to get the docker image to start and produce the proper open ports and access to the API, but i have zero experience with docker and I dont know how to modify the image's ergo.conf with the API key....im working on that aspect as well and will figure it out eventually but any tips are welcome!

**Comment by glasgowm148** [comment]
Please join the ergo [support spaces](https://linktr.ee/ergoplatform) if the issue persists.
