### ISSUE TITLE
huge txn cost or trojan or bug?

### ISSUE THREAD

**Issue by smash-necros** [ergoplatform/ergo#1418]
Hi
Today I tried send my mined ERGO to a market and got some unknown "extra fee" using official desktop wallet 4.0.12
1 ergo - 3,1 total winthdraw txn id  04d7b417c981d7d363d698f9325a6df1391d2b4784bbd17b951bb069631d9d69
2 ergo - 3.2 total winthdraw txn id 75f1bdf39c82590babd291308dd832d6419b884861c8d57bbaa947649e3180b3
3 ergo - 3.44 total winthdraw txn id ba34241e3f835dae2790e6aae7f29bab8d42507e06f097406e4c1ece6cc10d02
there are strange 3rd address appeared, where from? 
the 3rd address in txn is unknown and created newly, it has only 3 txn from me today.

in total ~4 ergo missed from wallet

then i installed android app and send 4 ergo - 7a03e8f87ae13ba5be86afef97f0e7acd12edb68e84be4d8ca41d6d56eaa7b7a
again 3rd address appeared but now its mine

Can anyone help?

**Comment by smash-necros** [comment]
there was some issue with node wallet, didnt show second address.

**Comment by jkrauss82** [comment]
hi, I seem to have a similar issue, how did you solve the issue with the node wallet?
