### ISSUE TITLE
Node stuck, consume a lot of CPU & Memory

### ISSUE THREAD

**Issue by rlinxy** [ergoplatform/ergo#1424]
One of our nodes was dozens of heights behind the mainnet, so we had to delete the entire chain data and ran a new sync. This node is in US and was running smoothly for several months. I have no idea what caused this issue.
![ergo02](https://user-images.githubusercontent.com/39939703/128808667-9e1f6add-ccce-4d08-aa6c-e13ff01a5cdc.png)

After more than 1 day syncing, this node stuck again at height 426288, and never move forward again. I have tried kill & restart the node several times, even reboot the server, but didn’t work. We found that the node consume a lot of CPU & memory after stuck there for several hours. Seems there might be memory leak.

![ergo01](https://user-images.githubusercontent.com/39939703/128808660-a8f687bc-79d0-4355-9a7f-4855ff62c8e2.png)

We coundn't find anything useful in the log
[ergo810.tar.gz](https://github.com/ergoplatform/ergo/files/6958973/ergo810.tar.gz)

**Comment by pragmaxim** [comment]
This looks like a problem in the networking layer, there is a suspicious overflow of `Received message MessageSpec(55: Inv)` right before the crash... I will take a look at it

**Comment by Ergonaumics** [comment]
Hmm this may be the root cause of my issues as well. Anyone have further input?

**Comment by glasgowm148** [comment]
Any updates @pragmaxim or a better issue that describes this?
