### ISSUE TITLE
Sync states never change t sync

### ISSUE THREAD

**Issue by fatlover360** [ergoplatform/ergo#1434]
![image](https://user-images.githubusercontent.com/17522094/130537157-8d9489ae-00e5-495e-8a25-5f4e2d2b0f8a.png)

and my conf file: 

ergo {
  node {
    mining = true
  }
}

scorex {
 restApi {
    # Hex-encoded Blake2b256 hash of an API key.
    # Should be 64-chars long Base16 string.
    # below is the hash of the string 'hello'
    # replace with your actual hash
    apiKeyHash = "MYKEYHASH"
  }

java version: 
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)

Also tried with 11.0.11 and 9.04
I was trying to set this under my Windows 10 machine, and changed to my centOS 8 and issue still the same.

thanks

**Comment by pragmaxim** [comment]
It is like this for the first ~ hour of syncing ... patience
