### ISSUE TITLE
Problems with ERGO Node local Mining !!!

### ISSUE THREAD

**Issue by mucsav1977** [ergoplatform/ergo#1447]
Hello, 

i configure all that the how to Youtube Video: 

[https://www.youtube.com/watch?v=ubov4oweA20](https://www.youtube.com/watch?v=ubov4oweA20)

i start the Ergo Node interface with java `ergo-4.0.13.jar`.
then i open the Node cmd and type: `node start.js`
And i mine wioth NBMiner and it was working.
it found new Jobs. but now accepted.

in the Node cmd i see one message every time:

```
debug: [No new blocks for 55 seconds - updating transactions & rebroadcasting work] undefined
Authorize MY-ERGO-WALLETADDRESS-IS-HERE:@::ffff:192.168.178.3
debug: [Unknown stratum method from MY-ERGO-WALLETADDRESS-IS-HERE: [::ffff:192.168.178.3]: mining.extranonce.subscribe] undefined
debug: [Block notification via RPC polling] undefined
debug: [No new blocks for 55 seconds - updating transactions & rebroadcasting work] undefined
debug: [Block notification via RPC polling] undefined
debug: [No new blocks for 55 seconds - updating transactions & rebroadcasting work] undefined
debug: [Block notification via RPC polling] undefined
debug: [Block notification via RPC polling] undefined
debug: [No new blocks for 55 seconds - updating transactions & rebroadcasting work] undefined
debug: [Block notification via RPC polling] undefined
debug: [No new blocks for 55 seconds - updating transactions & rebroadcasting work] undefined

```

in the Folder "ErgoStratumServer" i configure at the Configuration Time the file `start.js`

I edit the place:

```
    "coin": myCoin,
    "extraNonce1Size": 1,

    "address": "MY-ERGO-WALLETADDRESS-IS-HERE", //Address to where block rewards are given

    /* Block rewards go to the configured pool wallet address to later be paid out to miners,
       except for a percentage that can go to, for examples, pool operator(s) as pool fees or
       or to donations address. Addresses or hashed public keys can be used. Here is an example
       of rewards going to the main pool op, a pool co-owner, and NOMP donation. */
    "rewardRecipients": {
       "n37vuNFkXfk15uFnGoVyHZ6PYQxppD3QqK": 1.5, //1.5% goes to pool op
       "mirj3LtZxbSTharhtXvotqtJXUY7ki5qfx": 0.5, //0.5% goes to a pool co-owner
        /* 0.1% donation to NOMP. This pubkey can accept any type of coin, please leave this in
          your config to help support NOMP development. */
        `"22851477d63a085dbc2398c8430af1c09e7343f6":` 0.1

    "blockRefreshInterval": 1000, //How often to poll RPC daemons for new blocks, in milliseconds
```

and here i put my local IP Addresss: `192.168.178.3` and i put my workername

```
'data' object contains:
job: 4, //stratum work job ID
ip: '192.168.178.3', //ip address of client
port: 3333, //port of the client
worker: 'worker', //stratum worker name
```

amd the rest is all stay the same as before.

in the Ergo folder the file: `ergo.conf` i edit:

```
ergo {
    directory = "C:/ergo"
    node `{`
        mining = true
    }
    wallet.secretStorage.secretDir = "C:/ergo"
}

 scorex {
 restApi {
    # Hex-encoded Blake2b256 hash of an API key. 
    # Should be 64-chars long Base16 string.
    # below is the hash of the string 'hello'
    # replace with your actual hash 
    apiKeyHash = `"My-API-KEY"`
  }
}
```

is this all so correct??

in the `start.js file` :
IF I delete the pool and developer address then the start.js file not start in Node cmd `node start.js`

but now start with problems like what i post on the top !!

<img width="675" alt="ergo-mine-local-at-192-168-178-3-port-3256" src="https://user-images.githubusercontent.com/83464783/133290523-023e7472-6ec1-4cdb-bf77-f310b8a7cfda.png">

** please help me.**

**Thanks**

**Comment by kushti** [comment]
Any node-related issue to take look at ?

**Comment by mucsav1977** [comment]
What do you mean "node-related issue" ?

I become the message:

Authorize MY-ERGO-WALLETADDRESS-IS-HERE:@::ffff:192.168.178.3
debug: [Unknown stratum method from MY-ERGO-WALLETADDRESS-IS-HERE:
[::ffff:192.168.178.3]: mining.extranonce.subscribe] undefined
debug: [Block notification via RPC polling] undefined

in NBMiner look normal. But the DEBUG message makes me think and messes me up.

This is my First Local Mining with an own node.

Do you have experience with Local Ergo Node Mining?

Is this Message in the Node cmd a Problem or is this normal??

I think that not accept my Wallet. But i not sure.


Am Mi., 15. Sept. 2021 um 11:48 Uhr schrieb Alexander Chepurnoy <
***@***.***>:

**Comment by mucsav1977** [comment]
What do you mean "node-related issue" ?

I become the message:

`Authorize MY-ERGO-WALLETADDRESS-IS-HERE:@::ffff:192.168.178.3
debug: [Unknown stratum method from MY-ERGO-WALLETADDRESS-IS-HERE:
[::ffff:192.168.178.3]: mining.extranonce.subscribe] undefined
debug: [Block notification via RPC polling] undefined`

in NBMiner look normal. But the DEBUG message makes me think and messes me up.
This is my First Local Mining with an own node.
Do you have experience with Local Ergo Node Mining?
Is this Message in the Node cmd a Problem or is this normal??
I think that not accept my Wallet. But i not sure.

**Comment by glasgowm148** [comment]
Please use the Discord/support chats for mining setup support. This space is for technical fixes to the node.
