### ISSUE TITLE
Nginx proxy_pass | unable to authenticate API key

### ISSUE THREAD

**Issue by joshp23** [ergoplatform/ergo#1451]
The issue occurs when running Ergo Node Interface behind NGINX, essential for securing transmitted data such as "unlock wallet", or securing with OIDC to prevent a brute force attack. In this setup when "Set API Key" is sent, "Bad Api Key" is returned because the relevant header `api_key` has an underscore in it and is therefore dropped by NGINX. 

To resolve this:

## In Ergo's application.conf file:

1.  set `scorex.restApi.bindAddress = 127.0.0.1"9053`
    note that 127.0.0.0/8 works here
2. set `network.bindAddress = 0.0.0.0:9030`  
3. set `network,declaredAddress = X.X.X,X`
     where X.X.X.X is the external, public IP

## In NGINX's config for the Ergo Node Interface

```
server {
    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;
    server_name ergo.example.com;

    ## Here is the bug fixing line
    underscores_in_headers on;

    ## SSL settings
    ssl_certificate /etc/letsencrypt/live/ergo.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ergo.example.com/privkey.pem;

    location / {
         proxy_pass http://127.0.0.3:9053/;
    }

    access_log /var/log/nginx/ergo.access.log combined;
    error_log /var/log/nginx/ergo.error.log;
}
```

Perhaps this could be added to the wiki?

**Comment by kushti** [comment]
Done https://github.com/ergoplatform/ergo/wiki/Running-Ergo-behind-Nginx !

**Comment by joshp23** [comment]
Thank you!

**Comment by lcsvcn** [comment]
Helped me a lot. Thank you!
