### ISSUE TITLE
Remember recently included transactions 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1461]
It could be the case a transaction asked from a peer got included into a block and processed before delivery. For avoiding banning peers for sending invalid transactions, we need to store included transactions for last 2-3 blocks (into a Bloom filter?) and check on tx delivery that the tx is not included. I guess bitcoind is doing that.

**Comment by pragmaxim** [comment]
I think I'd have to introduce a new Event that would transfer transactions from applied blocks from `ErgoNodeViewHolder` to `ErgoNodeViewSynchronizer` where it would become part of bloom filters .... I did not think of other place to keep the bloom filters in ...

**Comment by pragmaxim** [comment]
@kushti I don't get the point of bloom filter here since the amount of transactions in a few last blocks is very low
