### ISSUE TITLE
how i can Export Seeds words from Ergo Node

### ISSUE THREAD

**Issue by mucsav1977** [ergoplatform/ergo#1473]
Hello,
i have a Ergo Node and i want add the wallet on my mobilephone.
but if i use the seed words which i have, then i get another wallet address and the coins was not there.

I not sure that the right seed words but i have only this seeds which i add in the andorid ergo wallet.

Did anybody know what i must do at my Ergo Node to export my currently seed words and get then the same wallet address?

Thanks for all answers.

**Comment by mucsav1977** [comment]
sorry but I don't understand what you mean.
Can you explain it to me it pls?
I have exported the folder in a usb stick and now if I start it I have the
same address.
but if i add the seed word(i don't know if that is the same) in an ergo
wallet app then i have another.
I want to export from the current ergo node the "secret seed words"  and I
want to use the same ergo wallet address.

Can you explain to me step by step what I must do then?
I searched in the Swagger ui  but there is nothing that gives me the secret
seed words.



Am So., 17. Okt. 2021 um 20:17 Uhr schrieb Alexander Chepurnoy <
***@***.***>:

**Comment by kushti** [comment]
@mucsav1977 for ErgoWallet and Yoroi seed should be the same. 

Are you using Oracle Java 8 maybe ?

**Comment by mucsav1977** [comment]
Hello,
i use the last version of Oracle Java.
But i can not export my memory seed words  to recovery my wallet  example
in a Android Wallet or other Wallets.

If anybody help me to get the memory seed words,   and i recovery my Ergo
Wallet in Android Wallet.
Did i get then the same Ergo Adress??



Am Do., 11. Nov. 2021 um 09:43 Uhr schrieb Alexander Chepurnoy <
***@***.***>:

**Comment by glasgowm148** [comment]
Please join support channels if the issue persists.

https://linktr.ee/ergoplatform
