### ISSUE TITLE
declaredAddress not a valid option for ergo.conf

### ISSUE THREAD

**Issue by vinnielima** [ergoplatform/ergo#1491]
When starting a node with ergo-4.0.15.jar, it complains:

 WARN  [tor.default-dispatcher-16] s.c.n.NetworkController - Unable to define external address. Specify it manually in `scorex.network.declaredAddress`.

When defining it in ergo.conf, the node is stuck at the following logging:

21:30:01.056 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))
21:30:01.076 INFO  [main] o.e.settings.ErgoSettings$ - Running in mainnet network mode

**Comment by kushti** [comment]
@vinnielima this is very soft warning, no need to provide external address if you not sure about that. 

What was your config with address (you can strip IP from it)

**Comment by vinnielima** [comment]
@kushti understood, here's my config that is working today, but always looking for opportunities to improve it. This was driven by our attempt to minimize the below error when submitting found blocks. We've increased the max concurrent connections per some of the other community recommendations.

Also FYI the NTP below isn't working, will open a separate ticket.

```
ergo {
    directory = "/opt/ergo_node"
    node {
        mining = true
    }
    wallet.secretStorage.secretDir = "/opt/ergo_node/wallet/keystore"
}

scorex {
    restApi {
        # Hex-encoded Blake2b256 hash of an API key.
        # Should be 64-chars long Base16 string.
        # below is the hash of the string 'hello'
        # replace with your actual hash
        apiKeyHash = "<API HASH>"
    },
    network {
        maxConnections = 100
        nodeName = "<NODENAME>"
    }

    ntp {
        # NTP server address
        server = "pool.ntp.org"

        # update time rate
        updateEvery = 30m

        # server answer timeout
        timeout = 30s
  }
}

```
```
06:59:20.308 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/93.123.180.164:9030, local=/10.1.2.4:43966, direction=Outgoing)
06:59:20.365 INFO  [tor.default-dispatcher-14] o.e.m.CandidateGenerator - New block mined, header: Header({"extensionId":"f24752386c96881c6177dd21eb6334041fcb9817ecf0d8004887165bf53d8beb","difficulty":"2076938810163200","votes":"000000","timestamp":1636459156974,"size":220,"stateRoot":"e3eb8495652d771314767d130855933b7e1b31107012399eacc35fcc86d0422617","height":615929,"nBits":117924087,"version":2,"id":"82484bb06abe5eb8edba97f887be953e20a2f35ac192cab294f060afcb73bcb9","adProofsRoot":"fd66557beeac91a49d7ee8aae253bd6946e1542223e23986c352f6d097ce903d","transactionsRoot":"89bfe51466e5172383c39a2fd913cea30794a94d9686d38abe0a8bc07398032b","extensionHash":"eb715ad70c258b497aaa007c920b20b22fd766a4681e3162fc04ef44cd63af29","powSolutions":{"pk":"0302122c332fd4e3c901f045ac18f559dcecf8dc61f6f94fbb34d0c7c3aac71fb7","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"a0b3655c998b6444","d":0},"adProofsId":"e8d0b10e86af6e9b8218d9b2fb8a4e79cdd5dede70d3a02f7405f1f2f6135324","transactionsId":"787727cb8dfda03a2467b31e13b86eba1e7a89b7cc33f1c384f68c1f6ba42db2","parentId":"d92695d75e26644c4dee1f3fe7eb98dc56799b850223f1107f470545660845bc"})
```

**Comment by kushti** [comment]
> @kushti understood, here's my config that is working today, but always looking for opportunities to improve it. This was driven by our attempt to minimize the below error when submitting found blocks. We've increased the max concurrent connections per some of the other community recommendations.
> 
> Also FYI the NTP below isn't working, will open a separate ticket.
> 
> ```
> ergo {
>     directory = "/opt/ergo_node"
>     node {
>         mining = true
>     }
>     wallet.secretStorage.secretDir = "/opt/ergo_node/wallet/keystore"
> }
> 
> scorex {
>     restApi {
>         # Hex-encoded Blake2b256 hash of an API key.
>         # Should be 64-chars long Base16 string.
>         # below is the hash of the string 'hello'
>         # replace with your actual hash
>         apiKeyHash = "<API HASH>"
>     },
>     network {
>         maxConnections = 100
>         nodeName = "<NODENAME>"
>     }
> 
>     ntp {
>         # NTP server address
>         server = "pool.ntp.org"
> 
>         # update time rate
>         updateEvery = 30m
> 
>         # server answer timeout
>         timeout = 30s
>   }
> }
> ```
> 
> ```
> 06:59:20.308 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/93.123.180.164:9030, local=/10.1.2.4:43966, direction=Outgoing)
> 06:59:20.365 INFO  [tor.default-dispatcher-14] o.e.m.CandidateGenerator - New block mined, header: Header({"extensionId":"f24752386c96881c6177dd21eb6334041fcb9817ecf0d8004887165bf53d8beb","difficulty":"2076938810163200","votes":"000000","timestamp":1636459156974,"size":220,"stateRoot":"e3eb8495652d771314767d130855933b7e1b31107012399eacc35fcc86d0422617","height":615929,"nBits":117924087,"version":2,"id":"82484bb06abe5eb8edba97f887be953e20a2f35ac192cab294f060afcb73bcb9","adProofsRoot":"fd66557beeac91a49d7ee8aae253bd6946e1542223e23986c352f6d097ce903d","transactionsRoot":"89bfe51466e5172383c39a2fd913cea30794a94d9686d38abe0a8bc07398032b","extensionHash":"eb715ad70c258b497aaa007c920b20b22fd766a4681e3162fc04ef44cd63af29","powSolutions":{"pk":"0302122c332fd4e3c901f045ac18f559dcecf8dc61f6f94fbb34d0c7c3aac71fb7","w":"0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","n":"a0b3655c998b6444","d":0},"adProofsId":"e8d0b10e86af6e9b8218d9b2fb8a4e79cdd5dede70d3a02f7405f1f2f6135324","transactionsId":"787727cb8dfda03a2467b31e13b86eba1e7a89b7cc33f1c384f68c1f6ba42db2","parentId":"d92695d75e26644c4dee1f3fe7eb98dc56799b850223f1107f470545660845bc"})
> ```

what's bad with NTP? simplest testing code (for default config) works fine:

```
object NtpTester extends App {
  val settings = ErgoSettings.read()
  implicit val ec = scala.concurrent.ExecutionContext.global

  val ntp = new NetworkTimeProvider(settings.scorexSettings.ntp)(ec)
  println(settings.scorexSettings.ntp)
  println(ntp.time())
}
```

on settings, if you're pool then makes sense to switch block generation when the node does not know whether it is synced yet, to avoid losing time after node restart: 

```
ergo {
  node {
     ...
     offlineGeneration = true
     ...
  }
}     
```

**Comment by vinnielima** [comment]
> what's bad with NTP? simplest testing code (for default config) works fine:

On version .16, this is now working (same config), so irrelevant now.
