### ISSUE TITLE
Ergo Stratum Proxy EXE perhaps contains trojan?

### ISSUE THREAD

**Issue by kneeil** [ergoplatform/ergo#1495]
In the mining guide, it lists Ergo Stratum Proxy as a prereq: https://github.com/ergoplatform/ergo/wiki/Mining-Ergo-after-The-Hardening-Upgrade.

When I went to download the EXE for version 1.2.1, my anti-virus flagged it as containing a Trojan. Details in this issue on the stratum proxy repo: https://github.com/mhssamadani/ErgoStratumProxy/issues/23

If someone is able to repro, then probably worth adding a warning to the mining guide?

**Comment by glasgowm148** [comment]
Pinged the dev but not related to the node.
