### ISSUE TITLE
Do not generate block candidate when sync is not done 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1496]
I guess that before recent miner code refactoring, no candidate generation happened when the node is not synced yet, but now it happens and results in a lot of errors. Should be fixed in next releases.

**Comment by pragmaxim** [comment]
This is very weird, candidate is generated only if : 
```
    def chainSynced =
      h.bestFullBlockOpt.map(_.id) == s.stateContext.lastHeaderOpt.map(_.id)
```

**Comment by pragmaxim** [comment]
Fixed here https://github.com/ergoplatform/ergo/pull/1412/commits/ec322ea7a941776fd27ba3525547d12974fb4e3b
