### ISSUE TITLE
Mining node generate new reward address after update to 4.0.16

### ISSUE THREAD

**Issue by solopool** [ergoplatform/ergo#1513]
We have generated one address in wallet. It is `9fmNUkBZfh8NUrA4MYrYZEFv4yikPqMP1yVvFTMHmb9gdBuEV8F` with pubkey `02a43026065c4ab3cddd34a7be704107690ebed34499b7b2187564da0847d335be` and **/mining/rewardAddress** return `88dhgzEuTXaRzFRZwM3jEryB2ouwDpjj7CVk2z4rStSDhAkEij4SR7FUCtHVrc5u3DU5pKtQQGx98p1E`.

This worked fine and mined blocks before update to 4.0.16.

After the update in the wallet also has the ony address `9fmNUkBZfh8NUrA4MYrYZEFv4yikPqMP1yVvFTMHmb9gdBuEV8F` and **/wallet/addresses** return only old address `9fmNUkBZfh8NUrA4MYrYZEFv4yikPqMP1yVvFTMHmb9gdBuEV8F`.

But **/mining/rewardPublicKey** return another pubkey `027c81634e461f843c436bc4267416eb60d42baf17910ad239296f38bc22afe372` (address `9fTtqcMuSfURB658n68UhKwDVwW3FkepR3pJQ2eNde6uxM66G97`) and **/mining/rewardAddress** return another address `88dhgzEuTXaRVtdXFwQFLD9NrGKjCP49pYiVAbptRRx9r4GbTmVZZYNDJGQ54AG4YjPpP5YkvvDUxBSd` .

Where did `9fTtqcMuSfURB658n68UhKwDVwW3FkepR3pJQ2eNde6uxM66G97` address come from? Why is it not in the address list?

Despite this, transactions with new found blocks are in the wallet and are checked through **/wallet/transactionById**.

**Comment by kushti** [comment]
Before, mining address was corresponding to root secret's key (in 4.0.13-4.0.16). Now, it is corresponding to change address key (m/44'/429'/0'/0/0 path by default). However, wallet scans for all the keys, even if root secret's key is now hidden in the UI.
