### ISSUE TITLE
Can't run node - PC failed while node synching

### ISSUE THREAD

**Issue by travek** [ergoplatform/ergo#1519]
Hi!
I was running node ergo-4.0.16 and while the node was synching my PC was rebooted due to some internal error. After this reboot the node can't start. I have an issue:

14:01:03.948 WARN  [ctor.default-dispatcher-7] o.e.settings.ErgoSettings$ - Running without network config
14:01:04.025 INFO  [ctor.default-dispatcher-6] o.e.n.UtxoNodeViewHolder - History database read
14:01:04.432 ERROR [ctor.default-dispatcher-6] scorex.db.StoreRegistry - Failed to initialize storage: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: 4 missing files; e.g.: C:\Users\home\Documents\Ergo\state\ldb_main/370026.ldb. Please check that directory C:\Users\home\Documents\Ergo\state\ldb_main exists and is not used by some other active node

What I should do to fix this ?

**Comment by glasgowm148** [comment]
Delete the hidden folder (.ergo) and resync - database corruption during unexpected shutdown. 

Please see the community chats for technical support: https://github.com/ergoplatform/awesome-ergo/blob/master/pages/community.md

**Comment by travek** [comment]
@glasgowm148 ,
can't find this folder. Where is is located ? I have history, peers, state, wallet folders in ERGO main folder.

**Comment by travek** [comment]
I deleted folders /history, /peers, /state and start to synch from genesis. While synching the node stopped man-many times, I always manually restarted it. I attached logs after one os node stop. Could you please help why it is happening 
[ergo_2.zip](https://github.com/ergoplatform/ergo/files/7698756/ergo_2.zip)
?

**Comment by travek** [comment]
And the logs after new node stop
[ergo_3.zip](https://github.com/ergoplatform/ergo/files/7698764/ergo_3.zip)

**Comment by travek** [comment]
and one more
[ergo_4.zip](https://github.com/ergoplatform/ergo/files/7698783/ergo_4.zip)

**Comment by kushti** [comment]
@travek Can it be killed from outside? Maybe due to logging out of shell. On Linux, please use something like nohup

**Comment by travek** [comment]
@kushti 
I don't think so. I'm runnin it on a dedicated Win 10 machine and there's no additional software installed on this PC.

**Comment by FidgetyRat** [comment]
I'm not sure if it is related or not, but I tried to set up a new node today on a Debian 12 system with OpenJDK-11. I had the node shut itself down (without error) multiple times during sync from genesis. Each time I had to restart the node, and it would get a few thousand height more then "shutdown" again.

I just deleted the .ergo folder and am starting again to see if there is any change.

**Comment by FidgetyRat** [comment]
No go for me. Still gets to the point of around 100k height or so then shuts itself down at a random time thereafter. Again, not sure if this is related but I can't sync a new node and that's troubling.

```
06:59:06.636 INFO  [tor.default-dispatcher-11] o.e.n.h.ErgoHistory$$anon$3 - Full block 8c7eabc558cd64fc76118d55f0edb2a3aa8478dc01d83cd92fa6862f7b0292a9 appended, going to apply 1 modifiers. New best block is 8c7eabc558cd64fc76118d55f0edb2a3aa8478dc01d83cd92fa6862f7b0292a9 with height 264061 updates block 9925d07c8216ef35ed190d0ed03defd3a8e01331586123bb2a70db4979813e75 with height 264060
06:59:06.637 DEBUG [tor.default-dispatcher-11] o.e.n.UtxoNodeViewHolder - Going to apply modifications to the state: ProgressInfo(BranchPoint: None,  to remove: Vector(), to apply: Vector(8c7eabc558cd64fc76118d55f0edb2a3aa8478dc01d83cd92fa6862f7b0292a9))
06:59:06.637 DEBUG [tor.default-dispatcher-11] o.e.n.state.UtxoState - Trying to apply full block with header 8c7eabc558cd64fc76118d55f0edb2a3aa8478dc01d83cd92fa6862f7b0292a9 at height 264061
06:59:06.648 INFO  [tor.default-dispatcher-11] o.e.n.state.UtxoState - Valid modifier with header 8c7eabc558cd64fc76118d55f0edb2a3aa8478dc01d83cd92fa6862f7b0292a9 and emission box Some(583ec795b8135b4c0ecfa95871e580476c4e73c36ba01a67a709f45c867bd96a) applied to UtxoState at height 264061
06:59:06.648 DEBUG [tor.default-dispatcher-11] o.e.n.h.ErgoHistory$$anon$3 - Modifier 8c7eabc558cd64fc76118d55f0edb2a3aa8478dc01d83cd92fa6862f7b0292a9 of type -127 is marked as valid 
06:59:06.648 INFO  [tor.default-dispatcher-11] o.e.n.UtxoNodeViewHolder - Persistent modifier fb76d79437d1b33da625b906875a83f3b49f8a94048965fba6c687231fab7573 applied successfully
06:59:06.652 DEBUG [tor.default-dispatcher-11] o.e.n.UtxoNodeViewHolder - Cache size after: 0
06:59:06.652 WARN  [tor.default-dispatcher-11] o.e.n.UtxoNodeViewHolder - Stopping ErgoNodeViewHolder
06:59:06.652 WARN  [tor.default-dispatcher-11] o.e.n.h.s.HistoryStorage - Closing history storage...
06:59:06.667 WARN  [tor.default-dispatcher-11] o.e.n.state.UtxoState - Closing state's store.
```

**Comment by travek** [comment]
@FidgetyRat 
I have exactly the same as you but on Win 10.
So, guessing there somethig in the node, not because of my PC

**Comment by travek** [comment]
I finally synched with the node 4.0.19
