### ISSUE TITLE
​/mining​/candidate returns "Miner has not started yet"

### ISSUE THREAD

**Issue by oliverw** [ergoplatform/ergo#1523]
Running the node like this:

`java -jar -Xmx3G ergo-4.0.16.1.jar --testnet -c testnet.conf`

and using the following config:

```
ergo {
  networkType = "testnet"

  directory = data

  node {
    mining = true
    useExternalMiner = true
  }

  network {
  }
}

scorex {
 restApi {
    apiKeyHash = xxxxxx
  }
}

```

When I invoke the ​`/mining​/candidate` RPC either programatically or using the Swagger UI, I always get the following response:

```
{
  "error": 500,
  "reason": "internal.error",
  "detail": "Miner has not started yet"
}
```

I'm pretty sure this worked differently in 4.0.13. What am I missing here?

**Comment by kushti** [comment]
Do you have "Miner is waiting for wallet initialization" message in your log? If so, or if wallet is not initialized, please do it

**Comment by oliverw** [comment]
I already did but it looks like I underestimated the time it takes from the time of wallet initialization to the point where `/mining​/candidate` starts working.

**Comment by cesar-v** [comment]
@oliverw mind if I ask how long it took before the miner started? - I was going into 16 hours and I think I made the mistake of restarting it.

**Comment by oliverw** [comment]
> @oliverw mind if I ask how long it took before the miner started? - I was going into 16 hours and I think I made the mistake of restarting it.

Pretty quickly. But the next time it happened again and this time it did not recover so I scrapped the coin.

**Comment by cesar-v** [comment]
@oliverw Thank you for sharing

**Comment by cesar-v** [comment]
@kushti Any advice? - I've been trying to mine on testnet, but I can't get a block candidate to generate.  It's been saying "Miner has not started yet" for almost 24 hours now.   Both my node and wallet are synced.
