### ISSUE TITLE
OpenApi Spec is currently invalid

### ISSUE THREAD

**Issue by oliverw** [ergoplatform/ergo#1527]
The Ergo OpenApi spec at [src/main/resources/api/openapi.yaml](https://github.com/ergoplatform/ergo/blob/master/src/main/resources/api/openapi.yaml) is currently invalid since it contains multiple references to an element that is not defined in the spec: `$ref: '#/components/schemas/PeersInfo'`

**Comment by kushti** [comment]
Thanks! fixed in https://github.com/ergoplatform/ergo/pull/1490/commits/9f63fea48e473f644ea76305ed62afb64360a69a
