### ISSUE TITLE
Node bootstrapping can get stuck with negative number of modifiers to download

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1529]
log example:

10:54:00.436 DEBUG [or.default-dispatcher-719] o.e.n.ErgoNodeViewSynchronizer - Going to download -393 non-header modifiers

**Comment by kushti** [comment]
@pragmaxim cant' find "Illegal status transition" in the logs

**Comment by pragmaxim** [comment]
Fixed https://github.com/ergoplatform/ergo/pull/1530
