### ISSUE TITLE
Optimized hardware CPU/GPU miners support

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#153]
Adopt some EquiHash (probably ZCash) GPU miner to be able to mine ERGO. 
Should get block candidate from API of ergo node and publish block via API when corresponding nonce is found.

**Comment by gurinderu** [comment]
Maybe better to use directly calling of c lib with jni?

**Comment by gurinderu** [comment]
And also, Should we care about cross-platform support?

**Comment by catena2w** [comment]
https://github.com/zawawawa/gatelessgate

**Comment by gurinderu** [comment]
I have forked a xpmclient repo (https://github.com/gurinderu/xpmclient) and I am going to fix a build for MacOs and with a new version of a czmq library.

**Comment by gurinderu** [comment]
@catena2w are you sure that you want using http instead of zmq?

**Comment by andyceo** [comment]
#259 should be fixed first.

**Comment by catena2w** [comment]
Will have own implementation soon
