### ISSUE TITLE
Peer database is full of obsolete addresses after a while which slows startup

### ISSUE THREAD

**Issue by pragmaxim** [ergoplatform/ergo#1539]
@knizhnik @kushti The node was offline for a few days and after startup node failed to connect to 226 peers :
```
 $ cat nohup.out | grep "Failed to connect to" | wc -l
226
```
I think that persistent peer database makes sense only for "node restarts", so we should maybe check when it was used last time and clean it if it is too old, to not slow startup down.

**Comment by knizhnik** [comment]
I have added one more parameter to NetworkSettings: peerOblivionTIme
Default value is 10 days.
I  peer was last contacted more than 10 days ago, then information about it is removed from the database.
If node was inactive for a long time, then information about all peers is deteriorated and predefined list of peers will be used.
Right now peerOblivionTIme is checked only during node initialization: where peer's database is loaded.
If it is desirable I can perform this check always before establishing connection to the peer.

**Comment by pragmaxim** [comment]
@knizhnik Imho 10 days is way too much time, the sweet spot might be somewhere ~ 12 hours from my experience ... IP addresses are constantly changing ...

**Comment by knizhnik** [comment]
> @knizhnik Imho 10 days is way too much time, the sweet spot might be ~ 6 hours from my experience ... IP addresses are constantly changing ... there might be someone with static IP occasionally, but imho rarely

Changed to 12 hours.

**Comment by kushti** [comment]
> Right now peerOblivionTIme is checked only during node initialization: where peer's database is loaded. If it is desirable I can perform this check always before establishing connection to the peer.

I think better to go with the dynamic option, and make following actions:
* do not propagate peers not seen in e.g. one week
* connect periodically to peers not seen or seen long time ago in order to just check their liveness (so drop connection after handshake), peers which do not respond or are sending misproper handshake should be removed from the db (already done)

**Comment by knizhnik** [comment]
> > Right now peerOblivionTIme is checked only during node initialization: where peer's database is loaded. If it is desirable I can perform this check always before establishing connection to the peer.
> 
> I think better to go with the dynamic option, and make following actions:
> 
>     * do not propagate peers not seen in e.g. one week
> 
>     * connect periodically to peers not seen or seen long time ago in order to just check their liveness (so drop connection after handshake), peers which do not respond or are sending misproper handshake should be removed from the db (already done)

I have already implemented peer eviction policy when we periodically drop connection with existed peer and try to establish connection from random peer. If it is not responding, then it is removed from the database.
Do we need something more?

**Comment by pragmaxim** [comment]
@knizhnik Thanks, it works nicely past months :+1:
