### ISSUE TITLE
Node is not really starting, endless "Running with args" loop in the log

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1541]
"10:39:38.195 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))
10:39:39.353 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))
10:39:40.321 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))
10:39:41.350 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))
10:39:42.332 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))
10:42:05.398 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(/opt/ergo_node/ergo.conf),Some(MainNet))"

**Comment by vinnielima** [comment]
Node originally synchronized, then stuck with "miner not ready" status being reported from stratum.  Upon restart, the node log shows the above and does not proceed.
