### ISSUE TITLE
Initialize wallet fails on node v4.0.18

### ISSUE THREAD

**Issue by chriswill** [ergoplatform/ergo#1545]
Steps to repro:

1. Deploy a new node
2. In the Initialize Wallet field group, enter a wallet password, leave mnenomic password field blank.  Click 'Send'.

Result: Receive error toast message in top right corner:
`class org.ergoplatform.wallet.interface4j.SecretString cannot be cast to class java.lang.String (org.ergoplatform.wallet.interface4j.SecretString is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')`

Expected:

Steps should initialize a new wallet.  Version 4.0.16 was previously successful.

**Comment by kushti** [comment]
Thanks, checking

**Comment by kushti** [comment]
Fixed in https://github.com/ergoplatform/ergo/pull/1548
