### ISSUE TITLE
Mempool syncing issues

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1565]
Seems mempools of known nodes of different versions are different: 

atm:

4.0.19-20: 10-12 transactions
4.0.4 - 86 transactions (!)
4.0.16 - ~20 transactions (recently restarted though, so maybe just collecting slowly from nodes <= 4.0.16)

So there are some problems with acceptance for recent versions it seems. 

Maybe to help with reproducing, a local devnet with 2 nodes (4.0.4 and 4.0.20) would be helpful

**Comment by pragmaxim** [comment]
Fixed #1567
