### ISSUE TITLE
Check for node being stuck

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1568]
Periodically check in ErgoNodeViewHolder whether last block is e.g. had a timestamp from more than 30 minutes ago (should be configurable I guess). If so, check that database contains continuation marked as invalid (ErgoHistory.repairIfNeeded), and also dump as much info as possible into log (WARN level)

**Comment by pragmaxim** [comment]
Solved https://github.com/ergoplatform/ergo/pull/1573
