### ISSUE TITLE
Missing transaction from 1-12-22

### ISSUE THREAD

**Issue by tbingeman** [ergoplatform/ergo#1578]
I use F2Pool for mining ERGO and use the ERGO Full Node for a wallet.  F2Pool sent a payment to my ERGO payment address on the 12th of January but it has yet to reach my wallet.  Going to the explorer, I am able to see that the payment has over 2000 confirmations on the TXID and the Ecplorer shows the right balance in my receive id but the wallet itself is not showing the balance on my receive id.  What can I do to correct this issue.

**Comment by pragmaxim** [comment]
are both node and the wallet synced 
![Screenshot from 2022-01-16 11-08-07](https://user-images.githubusercontent.com/8983344/149655575-b7e99a22-b96e-4e9a-8da8-d01792c6fc6a.png)

**Comment by tbingeman** [comment]
yes both are saying they are synced.

![image](https://user-images.githubusercontent.com/2460152/149696842-740e46e1-348b-4750-a88d-9c7aefcef36c.png)

**Comment by tbingeman** [comment]
Is there anyone who can help me with this issue?

**Comment by pragmaxim** [comment]
This is really hard to resolve, each block is scanned by wallet, all boxes from all transactions are checked whether they match your address and the wallet Balance is accumulated like this.

I'm on it, be patient pls.

**Comment by kushti** [comment]
> Is there anyone who can help me with this issue?

Please try /wallet/resync 

Did you do wallet update from a version in 4.0.13-15 ?

**Comment by tbingeman** [comment]
No I went form .14 to .20

**Comment by kushti** [comment]
> No I went form .14 to .20

Likely related to https://github.com/ergoplatform/ergo/issues/1513 . Please check, reward address likely changed. /wallet/rescan also needed in this case

**Comment by tbingeman** [comment]
I ended up completely redoing the node and importing the old wallet into the system which corrected the issue.
