### ISSUE TITLE
Sometimes API returns float for difficulty

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/ergo#159]
{'appVersion': '0.2.1', 'stateRoot': 'Po6gJZ5bYZ4amBUxGqt8xz2Sa89gKn1NcE2cqT5h6p9wD', 'peersCount': 3, 'headersHeight': 18316, 'unconfirmedCount': 0, 'bestHeaderId': 'Bzb3kH4V7VeRZErJB5Mp5kGmhxWQQCnY2saF4ZVBSZ9', 'bestFullHeaderId': '2cRWUtya6g41CDcXXhsfGPpeu7tmPQziVNUUj8oTgNj4', **'difficulty': 10.0**, 'fullHeight': 18172, 'isMining': False, 'stateType': 'utxo', 'name': 'UAj1rAf', 'stateVersion': 'QZNGARCoMLV73VfrvuidJFN7AcjnURCUvRJoMPebj1J', 'votes': 'UAj1rAf', 'previousFullHeaderId': '2ho4ZbqCyomNUSHAox7HgccPdk4caADneYVN8ieUPHkq'}

Not sure why this happens. Think we should fix that, difficulty is always represented by integer. Also, write unit tests for that.

**Comment by goral09** [comment]
I can take it :)

**Comment by goral09** [comment]
I don't know why this may happen. `difficulty` is of type `BigInt`. I run small test:
```
(0 to 100000).map(BigInt(_)).forall { bi =>
      !bi.asJson.as[String].contains(".")
    }
```
and it runs successfully every time.

**Comment by onzo-gorski** [comment]
@daron666 when you finish, can you please call me out - I am interested in the reason behind this.

**Comment by daron666** [comment]
@onzo-gorski hey. I found that circe auto derivation works weirdly with some types while using `getOrElse`. So here is an [example](https://scastie.scala-lang.org/DMrJqmdkRquan06tWN2GwQ).

**Comment by goral09** [comment]
@daron666 Thanks! that's weird as types do not change ( still a `BigInt` ). Anyway, good job and sorry for not doing it by myself.

**Comment by andyceo** [comment]
Well from now our monitoring did not work, because difficulty field is sometimes returned with 'e'.

There is some misunderstanding with number with exponent:

> While from a JSON (and JavaScript) perspective these four numerals
> 
> a) 100
> b) 100.0
> c) 1.0E+2
> d) 1E+2
> 
> are just four ways to write the exact same number, in environments where integers and reals are distinct types of numbers they might not all be equivalent.
> 
> And while (a) clearly means an integer, and (b) a real, and (c) a real as well, the case (d) is a bit ambiguous: for example, in C this is a floating point literal (because there's an exponent), but in Ada it is an integer literal (because there's no decimal point).
> 
> And in ISO 6093:1985 "Information processing – Representation of numerical values in character strings for information interchange", the last one is invalid, while the other three correspond to the three distinguishable formats NR1, NR2, and NR3 defined there.
> 
> So in general—in JSON or elsewhere—, I would prefer and recommend to always include a decimal point in a "scientific" decimal string representation with an exponent.
> 
> And to place at least one digit in front of the decimal point (if there is one), as JSON (and Ada, but not C) requires and ISO 6093 recommends (but not requires).
> 
> Just to avoid misunderstandings (among humans) or data exchange hassles (among machines and programs).
> 

In other words, numbers with `e` are always treating as floats, except some cases in JavaScript (where 10.0 is integer) and some very specific langs like Ada.

Here: https://stackoverflow.com/questions/19554972/json-standard-floating-point-numbers

See also: https://spacetelescope.github.io/understanding-json-schema/reference/numeric.html

Before closing this with "we don't care about Python numbers parsing problems" I want to point your attention to:

1. This is not only Python-related
2. We decided to write monitoring tool as strict as possible for early discovering possible bugs and misunderstandings with API, so this job was done well by monitoring tool. For me, it is much more easy to write `int(difficulty)` rather than writing this post.
