### ISSUE TITLE
Introduce transaction size limit for p2p layer

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1591]
1. Add maxTransactionSize setting (near maxTransactionCost), default value is 200 * 1024
2. In `def parseModifiers` inside ErgoNodeViewSynchronizer, if transaction is being parsed, check size before parsing, log warn message and skip the transaction
3. In TransactionsApiRoute.validateTransactionAndProcess , serialize transaction into binary and throw exception if size exceeds the limit

**Comment by knizhnik** [comment]
Do you mean `maxTransactionComplexity` intead of `maxTramsactionCost` ?

**Comment by knizhnik** [comment]
There is no NodeSettings available in TransactionApiRoute.
Should this check be performed in UtxoStateReader.validate instead?

**Comment by kushti** [comment]
> Do you mean `maxTransactionComplexity` instead of `maxTramsactionCost` ?

maxTramsactionCost replaced maxTransactionComplexity in 4.0.21

**Comment by kushti** [comment]
> There is no NodeSettings available in TransactionApiRoute. Should this check be performed in UtxoStateReader.validate instead?

you can get nodeSettings there as ergoSettings.nodeSettings
