### ISSUE TITLE
Tokens whitelist 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1604]
It could be the case for an exchange wallet that it is overload by assets sent to users (airdrops etc). To avoid problems with collecting funds, we need for the following:

* optional whitelist in wallet settings (which contains token ids)
* on transfer, burn tokens which are not in the whitelist (if it is set)

**Comment by glasgowm148** [comment]
Tokens with Value for whitelist. 

- SigUSD: `472c3d4ecaa08fb7392ff041ee2e6af75f4a558810a74b28600549d5392810e8`
- SigRSV
- ergopad
- NETA
- LunaDog
- Erdoge

**Comment by glasgowm148** [comment]
Instead of burning, would an auto-refund be possible? Or maybe some periodic thing that would send everything to a DAO.

**Comment by kushti** [comment]
> Instead of burning, would an auto-refund be possible? Or maybe some periodic thing that would send everything to a DAO.

Auto-refund could be tricky, considering that incoming transaction may have inputs associated with different addresses (or even scripts in general case)
