### ISSUE TITLE
Cache sync message and optimize syncInfoV1 [WIP]

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1609]
We calculate sync message on every request, while for a given height its value is constant (for both V1 and V2 sync).

Cache sync messages (for v1 and v2) for current height.

syncV1 is not efficient at all :

```
def syncInfoV1: ErgoSyncInfo = {
    if (isEmpty) {
      ErgoSyncInfoV1(Nil)
    } else {
      val startingPoints = lastHeaders(ErgoSyncInfo.MaxBlockIds).headers
      if (startingPoints.headOption.exists(_.isGenesis)) {
        ErgoSyncInfoV1((PreGenesisHeader +: startingPoints).map(_.id))
      } else {
        ErgoSyncInfoV1(startingPoints.map(_.id))
      }
    }
  }
```

instead of reading headers (wasting cache on the way), best chain ids can be read immediately

**Comment by pragmaxim** [comment]
It would be more efficient to cache only headerIds (v1) and headers(v2) but due to forking possibility it is hard to implement, caching whole SyncMessages is safe as there might be competing branches
