### ISSUE TITLE
Implement StatsCollector

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#161]
Implement class that uses subscribes to NodeViewHolderEvents and collects them to provide fast response to API /info method. Other metrics may be added later

**Comment by andyceo** [comment]
Please add this to metrics:

1. Internal node timestamp (because it can differ from system one)
2. Node uptime (how much time passed from node boot)

**Comment by andyceo** [comment]
Also need this one:

3. Version (build) number
