### ISSUE TITLE
Can't synch with node v.22 (can synch with node v.19)

### ISSUE THREAD

**Issue by travek** [ergoplatform/ergo#1622]
Hi!

I downloaded latest node v.22. My node dosn't synch with this version - it stuck with the block I synch lat time with the node v.19. I return back to node v.19 and it continued to synch sucessfully. 
What is wrong with v22 ? 
How I should setup node v 22 to continue synch after node v 19 ?

**Comment by pragmaxim** [comment]
@travek what exactly happens? Can you attach or paste your logs, did you run it with enough memory `-Xmx4g` and using OpenJDK 11 ?

**Comment by travek** [comment]
@pragmaxim 
I attached logs of running node v.22.
I have 8Gb RAM and, I underlyne, I can synch sucessfully with the node v.19. 
[ergo.zip](https://github.com/ergoplatform/ergo/files/8026731/ergo.zip)

**Comment by travek** [comment]
@kushti ,
could you help please

**Comment by kushti** [comment]
> @kushti , could you help please

Thanks for the logs!

"Got GetReaders request in state (None,None,None,None)" means database not read. 

So it is the case for 4.0.22(23 also presumably) but not .19 ?

**Comment by travek** [comment]
@kushti ,
yes, correct. I can launch the node v.19 and it will synch, no issues. Once I start with v.22 it doesn't. It seems I tried with v.21 as well earlier and it doesn't synch either.

**Comment by kushti** [comment]
> @kushti , yes, correct. I can launch the node v.19 and it will synch, no issues. Once I start with v.22 it doesn't. It seems I tried with v.21 as well earlier and it doesn't synch either.

weird, this means DB formats somehow got breaking changes, which shouldn't be the case.

Can you somehow upload DB for me? no wallet/ folder, only state/, history/, peers/ ?

**Comment by travek** [comment]
@kushti ,
I started to resynch from genesis with node v23. My PC is slow and I synch slowly day by day. It went smoothly untill. 2 days ago it topped synching and en error I have is - Got GetReaders in state (none, none, ...) and it is not synching any more... I'm upset. Several days of synching is lost.
Do you have any ideas why it spops synching ?
It happend the following way:
Day 1: I start to sync, it is synching, I stopped the node
Day 2: I start to sync, it is synching, I stopped the node
Day 3: I start to sync, it is synching, I stopped the node
....
Day x: I start to sync, got an eeror of none, none, none,....

I start to sync, I stopped the node

**Comment by travek** [comment]
The node can't establish connectiosn. I have connection reset erro in the log. Before it was OK, nothing changed.
How to fix it without starting from the beginning ?
