### ISSUE TITLE
Can't open http://127.0.01:9053/panel since moving to 4.0.23

### ISSUE THREAD

**Issue by arcadiancomp** [ergoplatform/ergo#1629]
Can't open http://127.0.01:9053/panel since moving to 4.0.23

Using latest Firefox on Ubuntu 20.04, all updates applied.

/swagger loads fine, so I know the daemon is there.

Miningcore still connects fine.

**Comment by arcadiancomp** [comment]
[http://127.0.01:9053/panel](http://127.0.0.1:9053/panel) loads fine in Chromium 98, but not in latest Firefox, odd.

**Comment by arcadiancomp** [comment]
Got it working, cleared the history and cache in Firefox, and it loads /panel fine now, sorry for the false alarm!

**Comment by deadit** [comment]
I think the issue was because the panel is updated but cached previous version.
