### ISSUE TITLE
Bootstrapping in "digest" mode with large suffix often stucks on the way

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1632]
For  a config like:

```
ergo {
  directory = ${ergo.directory}"/.ergo"
  node {
    stateType = "digest"
    blocksToKeep = 100000
    mining = false
  }
}
```

sync stucks on the way (during full block application, headers synced), reportedly and also on my machine as well.

**Comment by pragmaxim** [comment]
@kushti I could use more info as I'm new to this. It is not about Nipopow suffix but `suffix: IndexedSeq[ErgoPersistentModifier]` right?

**Comment by kushti** [comment]
> @kushti I could use more info as I'm new to this. It is not about Nipopow suffix but `suffix: IndexedSeq[ErgoPersistentModifier]` right?

Nipopow suffix is different beast. In digest mode, all the headers still downloaded, but instead of building and holding UTXO set proofs of correctness of its transformations (ADProofs) downloaded and checked. Then it is possible to perform full validation for only suffix of the blockchain.

**Comment by pragmaxim** [comment]
Ahh, so when `blocksToKeep` suffix is too large, like `100000` ...ok thanks

**Comment by pragmaxim** [comment]
I reproduced it, stuck at `667613` ... looks like syncing problem.

**Comment by pragmaxim** [comment]
The block is different from others by many more modifiers to apply, see `going to apply 933 modifiers` : 
```
23:54:23.138 INFO  [tor.default-dispatcher-11] o.e.n.h.ErgoHistory$$anon$3 - Full block ada64036803188230c4fbec5d6e0b3e9c2b848dbe09f69ec14bd7f24361021ff appended, going to apply 933 modifiers. New best block is 0983dacbff14c3beb4bb2da242220a3e03e8be40c2260c4b366edfab4bf17f4b with height 667613 updates block 9b17e2a20f911760dc95384a2705f09e51f7a7e8762fb9abaf1070e6a94009c9 with height 666680                                 
```
@kushti Can you see anything suspicious about that block? https://explorer.ergoplatform.com/en/blocks/0983dacbff14c3beb4bb2da242220a3e03e8be40c2260c4b366edfab4bf17f4b

**Comment by kushti** [comment]
The block is applied successfully it seems. I guess the problem is in the next block https://explorer.ergoplatform.com/en/blocks/0f9235c97404c16c3945c64218233159e48cd5945c048d091807bdc79cbfb58c , which caused problems for nodes in  "utxo" mode as well. see https://github.com/ergoplatform/ergo/releases/tag/v4.0.21.1
