### ISSUE TITLE
Wallet can become unresponsive if too many unspent boxes there 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1635]
If too many unspent boxes in the wallet (e.g. more than 100K), it may produce timeouts on generating a transaction. 

Likely caused by ```ErgoWalletState.getBoxesToSpend``` method and underlying DB methods, they do not have limits while box selector has a limit to iterate, which is maxInputs * ScanDepthFactor. We should add the same limit to DB methods and ```getBoxesToSpend```.

**Comment by pragmaxim** [comment]
@kushti `maxInputs * ScanDepthFactor` is `30000`  ... isn't that too many?
