### ISSUE TITLE
Wallet: DefaultBoxSelector ignoring needed boxes when needed for change

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo#1644]
Steps to reproduce:
Call `DefaultBoxSelector.select(inputBoxes, amountToSpend, targetAssets)` with

* inputBoxes: 
 box 1 with amount 1001000000 nanoerg and a token
 box 2 with amount 1000000 nanoerg
* amoundToSpend: 1001000000 (exactly matching box 1)
* targetAssets: empty

Exptected behaviour:
returning both inputboxes (as both are needed for amountToSpent and change box for the token not to be sent)

Actual behaviour:
throwing `NotEnoughCoinsForChangeError`

Related test case: ergoplatform/ergo-appkit#141

**Comment by kushti** [comment]
Fixed in #1645
