### ISSUE TITLE
Transactions with estimated execution cost bigger than 1000000 are rejected since 4.0.23

### ISSUE THREAD

**Issue by Luivatra** [ergoplatform/ergo#1648]
A transaction that can be submitted and executed successfully on 4.0.22 fails with "Failed to sign boxes due to Estimated execution cost 1036435 exceeds the limit 1000000" on 4.0.23

This seems to ignore the maxTransactionCost parameter in the config file.

**Comment by Luivatra** [comment]
Also hitting the same issue on 4.0.22 on a slightly larger transaction. Not really sure what the exact issue is.

**Comment by pragmaxim** [comment]
Problem is that we use the default `MaxBlockCost = 1 000 000` in transaction/send : 
```
epochLength = 1024
MaxBlockCostIncrease -> 16 * 1024 
which basically means 696 160 * 16 = 11 138 560 
so the current MaxBlockCost should be 11 138 560 
```

**Comment by kushti** [comment]
> Problem is that we use the default `MaxBlockCost = 1 000 000` in transaction/send :
> 
> ```
> epochLength = 1024
> MaxBlockCostIncrease -> 16 * 1024 
> which basically means 696 160 * 16 = 11 138 560 
> so the current MaxBlockCost should be 11 138 560 
> ```

Not every epoch cost increased, only if miners are voting for
