### ISSUE TITLE
API reports non-existing block header

### ISSUE THREAD

**Issue by abchrisxyz** [ergoplatform/ergo#1651]
http://213.239.193.208:9053/blocks/at/701440 returns two headers:
```
[
  "492a911101f36fc2b9e335ccff0a90e08d3e92b82d42a17316caac2d636f55e0",
  "52826e74d17dde672899152d27ecfd08e6de3823b58d959d1f6fe8b033b568ce"
]
```
But `52826e` is not retrievable: http://213.239.193.208:9053/blocks/52826e74d17dde672899152d27ecfd08e6de3823b58d959d1f6fe8b033b568ce returns
```
{
  "error": 404,
  "reason": "not-found",
  "detail": null
}
```

**Comment by kushti** [comment]
From blocks/at response, first row is always about best chain header id

It seems that your node has header with id 52826e74d17dde672899152d27ecfd08e6de3823b58d959d1f6fe8b033b568ce, but not corresponding full block

**Comment by abchrisxyz** [comment]
It's not just my node, but I get your point.

So a node will not necessarily fetch a block if it can already infer it's not part of the main chain. That makes sense. Easy enough to check the response anyway.

Only made the issue in case it wasn't expected behaviour. Thanks for chiming in.
