### ISSUE TITLE
Help decentralization: Add an information which peers are open to get requests on HTTP API

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo#1652]
### Background

Light clients like the ergo wallet app need to connect to node's REST API in order to get box information or submit transactions.

### Problem

Ergo is a peer2peer network and nodes can be offline or malfunctioning. This shouldn't be a problem, a client could connect to another node and continue working. However, a client don't know which peers of the network it could connect to. Even when a connection to a perfectly working node is established, clients can't fetch information of other nodes to connect to. There is an existing Peers API that reports all peers the node is connected to. This information is very valuable to help decentralization. However, for applications like SPV wallets, it is important to know if the node is not only open for p2p connection, but also for HTTP REST API requests - and on which port or URL. This information is not available on Rest API.

Currently, peers/connected returns a block like this:
```
{
    "address": "/<ip>:9030",
    "lastMessage": 1646725996336,
    "lastHandshake": 1646719641723,
    "name": "ergo-mainnet-4.0.23",
    "connectionType": "Outgoing"
}
```

It could be guessed and tried if the HTTP API is running on `http://<ip>:9053` for mainnet or `http://<ip>:9052` for testnet, but this is some kind of trial&error. Additionally, some node's HTTP API might be even exposed via a https://domain.name/ergoapi url that could not be found this way.

### Solution

I suggest to extend the node in the following way:

1. Add a config entry for REST API. The node administator can enter here the HTTP address the node's REST API is reachable from outside, it should be able to hold a user-entered http(s) domain address, if available. The entry is an opt-in entry, if not filled by admin the REST API is seen as closed for the public.
2. The information of the REST API should be broadcasted to the connected nodes
3. Add a new property to peers API with the HTTP REST API address.
4. Sorting should be flipped for peers/connected - at the moment, the peers with the oldest lastMessage timestamp come first.
 
This way, a light client can build a database of nodes to connect to from the Peers API and can suggest alternatives to the user in case the node to connect to is not reachable.

Needed for ergoplatform/ergo-wallet-app#20

**Comment by greenhat** [comment]
I concur. We're facing the same problem in the SPV node API (https://github.com/ergoplatform/sigma-rust/issues/544).

**Comment by satsen** [comment]
Maybe programs should use the normal connection instead? I don't see the point of having this other than consuming more bandwidth

**Comment by MrStahlfelge** [comment]
@pragmaxim this idea came a bit late, but I think it would be good if this field is shown in NodeInfoApi as well.

**Comment by pragmaxim** [comment]
@MrStahlfelge you mean that we should call the field `publicUrl` instead of `restApiUrl` ? https://github.com/ergoplatform/ergo/pull/1662/files#diff-6d3c2d15b1cb16a2e1b439d886d778952496061489fae085e2de412d3a886a32R63

**Comment by MrStahlfelge** [comment]
I mean to not only report it in PeersAPI (`peers/all`), but also in NodeInfoApi (`/info`).
At first I thought this is not needed because, when you contact a node on /info, you already know its REST API address. But it is useful to know if the node opted in to be contacted.

**Comment by pragmaxim** [comment]
Done, I just named the fields `restApiUrl` on both places as I found `publicUrl` less expressive :shrug: But I can change that, wdyt ?

**Comment by MrStahlfelge** [comment]
I think restApiUrl is good, the sigma-rust guys were the ones introducing publicUrl name

**Comment by greenhat** [comment]
restApiUrl looks good.

**Comment by HelixEvo** [comment]
Great proposal. 

Can the filtering from the node list also have a flag for whether the node is fully synced also?

As I don't think it would be great if a node is advertising, but it's not up to date with block processing.

**Comment by MrStahlfelge** [comment]
That's not really needed as the block height is returned and can be compared with other nodes :)

**Comment by MrStahlfelge** [comment]
This is resolved, thanks for the work!
