### ISSUE TITLE
Make tests for headers coming out-of-order

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1657]
Reportedly, 4.0.23 may stuck still if headers coming out-of-order (see https://github.com/ergoplatform/ergo/issues/1615 where it was supposedly fixed).

Do tests that out-of-order headers do not cause node being stuck.

**Comment by pragmaxim** [comment]
@kushti I think this is a different problem that I fixed in `4.0.24` ... when `4.0.23` was freshly started then it had a false positive `chain-stuck` with a reset of delivery-tracker which caused a stuck during headers sync ...
