### ISSUE TITLE
Can't sync with testnet

### ISSUE THREAD

**Issue by saturn4er** [ergoplatform/ergo#1659]
I tried to run node with testnet, but sync stopped at block 185121. After some investigation, I found that node started to sync 'uncle' chain:
[dd3ac89c7ee5c34d10b74e6a38d2db13f4a0b8e77aa588bf6f9d59487adc5331](https://testnet.ergoplatform.com/en/blocks/ac9953e0f972a9ea780f1713f5f862d509548c557728c6ec6c9912aad42397da)(#185091) -  this block is a part of synced blockchain(last block is 7feca496e2be164de5cedbb4300031fe1f6189c7029d64eb2f6322707fdf9348(#185121))
[ac9953e0f972a9ea780f1713f5f862d509548c557728c6ec6c9912aad42397da](https://testnet.ergoplatform.com/en/blocks/ac9953e0f972a9ea780f1713f5f862d509548c557728c6ec6c9912aad42397da)(#185091) - this block is a part of blockchain,  which shows in explorer(last block is [b25317b7a0f4bed1c15b9c8f528f395f749613aaaa934b9f8d0e83982e46a4a7](https://testnet.ergoplatform.com/en/blocks/ac9953e0f972a9ea780f1713f5f862d509548c557728c6ec6c9912aad42397da)(#190093))

That's strange behavior, that node do not switch to second chain, even if it length is bigger, and my node have peers with bigger blockchain:
/peers/syncInfo:
```
[...
  {
    "address": "N/A",
    "version": "4.0.23",
    "mode": {
      "state": "utxo",
      "verifyingTransactions": true,
      "fullBlocksSuffix": -1
    },
    "status": "Older",
    "height": 190092
  }, ...
  ]
  ```

**Comment by cesar-v** [comment]
Hello @saturn4er.  I was having the same issue a few weeks ago.  Kushti helped me fix it by downloading a copy of the chain - 176.9.15.237:8000/testnet-back.zip

**Comment by saturn4er** [comment]
@cesar-v I already found a solution in discord, but anyway it's a workaround, and it should be fixed in other way

**Comment by cesar-v** [comment]
I attempted to sync on a different machine to test with and received similar results.  Full log below.

[ergo.tar.gz](https://github.com/ergoplatform/ergo/files/8401431/ergo.tar.gz)
