### ISSUE TITLE
Unconfirmed transactions for scans

### ISSUE THREAD

**Issue by anon-real** [ergoplatform/ergo#1663]
Having an API to get unconfirmed transactions of a registered scan. Currently `/transactions/unconfirmed` exists and works for the node's wallet transactions only.

**Comment by MrStahlfelge** [comment]
The API endpoint to get all mempool's transactions could be used, but it returns too much data. I suggest to add filters to it.

**Comment by pragmaxim** [comment]
@anon-real can you pls link the client code that uses the scans?
