### ISSUE TITLE
Swagger requests 127.0.0.1 instead of the public url (bug)

### ISSUE THREAD

**Issue by pyotrsky** [ergoplatform/ergo#1672]
Hi. In version 4.0.25, the swagger is configured to send requests to the `127.0.0.1`. I think it should be the public IP address of the node instead. The Swagger does not work now if you open it by the public IP address of your node.

https://github.com/ergoplatform/ergo/blob/55af449ace6a7fd605130e8498dc5304f2ccffe4/src/main/resources/api/openapi.yaml#L16

**Comment by pragmaxim** [comment]
@ross-weir I agree https://github.com/ergoplatform/ergo/pull/1655#issuecomment-1083416717

**Comment by cesar-v** [comment]
I'll also note that testnet swagger is inserting mainnet port into sample curl requests

![Screenshot from 2022-03-30 17-44-12](https://user-images.githubusercontent.com/5210627/160954150-9f85b20b-0380-411f-bf91-8f49f233ce18.png)

**Comment by jozanek** [comment]
Can be closed @kushti
