### ISSUE TITLE
ERROR CUDA failed at minning.cu: 310  CUDA error code700

### ISSUE THREAD

**Issue by microsoc163** [ergoplatform/ergo#1677]
The log as following, Please help me, Thanks a Lot: 
D:\Projetcs\Egro\NV_Miner_WIN64_CUDA11_4.2.0\NV_Miner_WIN64_CUDA11_4.2.0>miner.exe
2022-04-05 22:15:56,634 INFO [main thread] Using 1 GPU devices
2022-04-05 22:15:56,634 INFO [main thread] Using configuration file ./config.json
2022-04-05 22:15:56,634 INFO [main thread] Block getting URL:
   http://127.0.0.1:3000/mining/candidate
2022-04-05 22:15:56,634 INFO [main thread] Solution posting URL:
   http://127.0.0.1:3000/mining/solution
2022-04-05 22:15:56,649 INFO [main thread] Got new block in main thread, block data: {"MSG":"F7F2D1E0985C72DDCF943A1C0D29785A1E23DBCD28C439BE75C86F30860A9A27","B":115792089237316195423570985008687907853269984665640564039457584007908834672640,"EXTRANONCE1":"40B9","EXTRANONCE2SIZE":6,"HEIGHT":721367}
2022-04-05 22:15:56,789 INFO [GPU 0 miner] GPU 0 started
ERROR:  CUDA failed at mining.cu: 310
CUDA error code 700
Miner is now terminated
================================================================================

**Comment by microsoc163** [comment]
append more log:
D:\Projetcs\Egro\NV_Miner_WIN64_CUDA11_4.2.0\NV_Miner_WIN64_CUDA11_4.2.0>nvidia-smi
Tue Apr  5 22:21:38 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.15       Driver Version: 512.15       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   44C    P5    13W / 130W |   1320MiB /  8192MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1448    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      1672    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      3372    C+G   ...zilla Firefox\firefox.exe    N/A      |
|    0   N/A  N/A      3960    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      5128    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A      5224    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A      7112    C+G                                   N/A      |
|    0   N/A  N/A      7148    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A      8840    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     11200    C+G   ...zilla Firefox\firefox.exe    N/A      |
|    0   N/A  N/A     11632    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     11664    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by kushti** [comment]
Which miner are you using? For testnet likely ?

**Comment by microsoc163** [comment]
NV_Miner_WIN64_CUDA11_4.2.0 for mining ergo through the pool named f2pool(www.f2pool.com)
