### ISSUE TITLE
Database error on Raspberry Pi

### ISSUE THREAD

**Issue by jellymlg** [ergoplatform/ergo#1678]
Starting up a node (4.0.25) on a raspberry pi causes this error:

`scorex.db.LDBFactory$ - Failed to load database factory org.fusesource.leveldbjni.JniDBFactory due to: {}`
`java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-4.0.25 in java.library.path: [/usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib], no leveldbjni-4.0.25 in java.library.path: [/usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib], no leveldbjni in java.library.path: [/usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib], /tmp/libleveldbjni-64-4-2245338800270757167.0: /tmp/libleveldbjni-64-4-2245338800270757167.0: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]`
        `at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)`
        `at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)`
        `at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)`
`...`
`scorex.db.LDBFactory$ - Using the pure java LevelDB implementation which is still experimental`

After that it just repeats this:

`[ergoref-api-dispatcher-8] o.e.n.ErgoReadersHolder - Readers are not initialized yet : (None,None,None,None)`
`[ergoref-api-dispatcher-8] o.e.n.ErgoReadersHolder - Readers are not initialized yet : (None,None,None,None)`
`[ergoref-api-dispatcher-8] o.e.n.ErgoReadersHolder - Readers are not initialized yet : (None,None,None,None)`

**Comment by kushti** [comment]
The message is okay, says that it is not possible to use LevelDB native libs, so pure Java version will be used.

Are you getting (None,None,None,None) on node restart? So database is already seeded ?

**Comment by jellymlg** [comment]
Yes I'm using the data from my other full node that is already synced.
The problem is that it gets stuck printing this message.

**Comment by Patriciu** [comment]
same problem on my Pi4/4GB. unable to sync.

**Comment by dreams-money** [comment]
@jellymlg @Patriciu join the ErgoPI discord group.  A few people are having the same issues - https://discord.gg/ecmX32yzyS

**Comment by kushti** [comment]
> I have the same issue, a full node running in Kubernetes, after restarting the not (power off) and back the sync status keeps showing this log, and on the dashboard shows "Active synchronization"...

and any error in the log ? Usually there's some message about corruption

**Comment by jadsonlourenco** [comment]
> > I have the same issue, a full node running in Kubernetes, after restarting the not (power off) and back the sync status keeps showing this log, and on the dashboard shows "Active synchronization"...
> 
> and any error in the log ? Usually there's some message about corruption

Yes, I think. I'm running on K3S (Kubernetes). I think the issue is when the server shutdown, down without power, for example. How to handle it to not have file corruption?

**Comment by ccgarant** [comment]
Same here on the pi

I'm having this issue now after trying to do port forwarding and set my down stream router as the primary. My rasp pi picked up a new IP address and now i'm getting No Node Found. I managed to set a Static IP of the pi "headless". But I still am getting this error:

[ergoref-api-dispatcher-7] o.e.n.ErgoReadersHolder - Readers are not initialized yet : (None,None,None,None)

Here's the error in the ergo.log

```
02:38:27.695 INFO  [tor.default-dispatcher-12] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.754 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: requirement failed
03:56:42.758 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.760 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.761 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.763 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.764 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.766 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.768 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.771 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.773 INFO  [tor.default-dispatcher-11] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.874 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.876 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.877 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.879 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.881 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.882 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.884 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.885 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.887 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.888 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.892 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.893 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: addr is of illegal length
03:56:42.895 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Error during parsing a handshake: requirement failed: Not enough bytes in the buffer: 238
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni32-5.0.14 in java.library.path: [/usr/java/packages/lib, /usr/lib/arm-linux-gnueabihf/jni, /lib/arm-linux-gnueabihf, /usr/lib/arm-linux-gnueabihf, /usr/lib/jni, /lib, /usr/lib], no leveldbjni-5.0.14 in java.library.path: [/usr/java/packages/lib, /usr/lib/arm-linux-gnueabihf/jni, /lib/arm-linux-gnueabihf, /usr/lib/arm-linux-gnueabihf, /usr/lib/jni, /lib, /usr/lib], no leveldbjni in java.library.path: [/usr/java/packages/lib, /usr/lib/arm-linux-gnueabihf/jni, /lib/arm-linux-gnueabihf, /usr/lib/arm-linux-gnueabihf, /usr/lib/jni, /lib, /usr/lib], /tmp/libleveldbjni-32-5-6339792071395762838.0: /tmp/libleveldbjni-32-5-6339792071395762838.0: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)]
```
Perhaps also noteworthy I can no longer `ssh pi@headless.local` it needs to be now `ssh pi@<192.168.XXX.XX> to log into it...
