### ISSUE TITLE
Failure in proof production seems to prevent the node from synchronizing with the network

### ISSUE THREAD

**Issue by Ewemek** [ergoplatform/ergo#1724]
Hello,

We maintain several nodes located over the world, and regularily they just stop increasing their height as they should do, almost all of them at the same time.

Here are some logs (running in v4.0.27) that seems related to the problem:
```
java.lang.Exception: Key 000b962dc36a3cb0ffdc3e7315bd4ba2826066fefb5e061c72f5b2d59d4c4090 does not exist
19:39:23.183 ERROR [tor.default-dispatcher-22] o.e.m.CandidateGenerator$ - Failed to produce proofs for transactions, but emission box is found: 
java.lang.Exception: Key da9258b729413ef785d62bc60653acf2b57277f50a9a9141809e9cf103dc6677 does not exist
19:39:23.184 ERROR [tor.default-dispatcher-22] o.e.m.CandidateGenerator - Candidate generation failed
```

Actually we are not 100% sure the logs and the problem are related, but these are the only relevant logs around the time when the problem occurs.
Rebooting the node fixes the issue as the synchronisation process starts, but we believe it sometimes happens during the night and fixes itself at some point.

**Comment by kushti** [comment]
Please update the nodes to 4.0.30+ (better, 4.0.31). There were a couple of bugfixes in 4.0.28 for known cases when node may stuck (see https://github.com/ergoplatform/ergo/releases/tag/v4.0.28 for details). Likely, the issue you have is about  headers coming out-of-order during forks resolution (fixed in 4.0.28).

**Comment by Ewemek** [comment]
Hi Kushti, thanks for the quick answer, we've already planned to update to the latest ASAP

**Comment by Ewemek** [comment]
After updating to v4.0.31 the problem happenned once again, some of our nodes got stuck at some height for 15 minutes or so.

This time I suspect it is due to these nodes being caught in a forked chain that did not make it through because we have this message a lot when the node seems to be back on its feets:
`19:33:26.414 WARN  [tor.default-dispatcher-50] o.e.n.ErgoNodeViewSynchronizer - Extension is empty while comparison is fork`

This log is found on all of our nodes at the same periods though.
Looking back in the past, this log occurs a few minutes after we detected the problem "being solved", even in v4.0.28.

**Comment by kushti** [comment]
So the node is stuck at some height for like 15 minutes then catching up ?

**Comment by Ewemek** [comment]
yes, last week we even detected that we mined a block during the problem, hence the block was stale because 10 minutes late
for the moment didn't notice any log
