### ISSUE TITLE
Ask block sections directly from peer sending us a new header

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1743]
When the node is synced, ask block sections from the peer which delivered a new header (updating our best chain) immediately.

**Comment by pragmaxim** [comment]
@kushti can you please clarify the reasoning behind this? Why would it be faster/better than the current way?

**Comment by kushti** [comment]
@pragmaxim first of all, currently we're asking some random peers (if our peer is not connected to new block miner) for block sections. For new blocks, there's also broadcasting:

```
    case SemanticallySuccessfulModifier(mod) =>
      broadcastInvForNewModifier(mod)
```

which is making quick delivery.

However, as we now can extract a new header from sync (which will be sent immediately after block application), we can ask immediately corresponding block sections, so INV exchange could be avoided at all.
