### ISSUE TITLE
Junk registers data on eUTXO boxes causes "Box id parsed from JSON differs from calculated from box serialized bytes"

### ISSUE THREAD

**Issue by nirvanush** [ergoplatform/ergo#1754]
### Problem
Sometimes dapp developers forget to reset registers when moving boxes from contracts to user's address.
It causes the box being stored with old register values as unspent txs.

When user try to spend that box it causes an error and user can't spend that box:
```
{
    "code": 1,
    "info": "Failed to parse ErgoBox from JSON string: JsValue(Object({\"boxId\":\"4e75f0db4dafbd37cd4fcafa862df48b3ef7cb486cd6e31e3a2033f7ce0eea2a\",\"transactionId\":\"3cf8edcbdadff81c140ce7ba1b610fb199f709ef72a0590cea42838516e269d7\",\"index\":0,\"ergoTree\":\"0008cd035263e8111debc9344571f8a28a319a60e392b57f5440f08208845cbdb317b639\",\"creationHeight\":777139,\"value\":\"1000000\",\"assets\":[{\"tokenId\":\"a49d2c831601b4798363620e0af84891cee8dacf0039694b72d44acc0337bb85\",\"amount\":\"1\"}],\"additionalRegisters\":{},\"confirmed\":true,\"extension\":{}})) \n with error: Box id parsed from JSON differs from calculated from box serialized bytes"
}
```

Here is how the box is stored on users wallet
```
{
        "boxId": "4e75f0db4dafbd37cd4fcafa862df48b3ef7cb486cd6e31e3a2033f7ce0eea2a",
        "transactionId": "3cf8edcbdadff81c140ce7ba1b610fb199f709ef72a0590cea42838516e269d7",
        "index": 0,
        "ergoTree": "0008cd035263e8111debc9344571f8a28a319a60e392b57f5440f08208845cbdb317b639",
        "creationHeight": 777139,
        "value": "1000000",
        "assets": [
            {
                "tokenId": "a49d2c831601b4798363620e0af84891cee8dacf0039694b72d44acc0337bb85",
                "amount": "1"
            }
        ],
        "additionalRegisters": {
            "R5": "0ea6037b22373231223a0a202020207b224e7574486f7573655f32223a0a20202020202020207b22436f6c6c656374696f6e223a20224e757448656164733344222c0a20202020226e616d65223a20224e7574486f7573655f32222c0a20202020226465736372697074696f6e223a20224e7574686561732061667465722066696e64696e67206c6f76652c2074686579206275696c64206120686f75736520746f206c697665206120676f6f64206c6966652e20416c6c204e7574686f757365206172652061637475616c203364206d6f64656c7320616e642063616e206265206465706c6f79656420696e73696465205369676d6156616c6c65792e222c0a20202020224261636b67726f756e64223a202256616c6c6579204261636b67726f756e64222c0a20202020224d61696e20486f757365223a202231204c6576656c2050696e6b20486f757365222c0a2020202022526f6f66223a202252656420526f6f66222c0a20202020225469746c65223a20224e7574686561647320536967682047726179222c0a2020202022526172697479223a2022636f6d6d6f6e227d0a7d0a7d0a0a0a",
            "R6": "0e0130",
            "R8": "0e204d2ea0baa48796d9b31ef3d26c176f0dbe32a570fc36c37fea292b9bf440aabf",
            "R7": "0e020101",
            "R9": "0e42697066733a2f2f62616679626569637573366570356d6f75776b343464636d6e6268757662376f7a717a746b6c6f6767626e636134763762756f7475656c78667934",
            "R4": "0e154e75744865616433443a204e7574486f7573652332"
        },
        "confirmed": true
    },
    ```

It seems like registers' values are not counted in when calculating box serialized bytes.
Ordinary wallet user have no control choosing what boxes to use to sign a tx, it's done automatically by dapp developers. 
So he faces a situation when he don't know why transaction doesn't work and what that error means. 

Consolidating boxes solves it, but maybe registers should be included during serialized bytes calculation or filtered out when sent to users wallet.

**Comment by kushti** [comment]
Registers are serialized, so box id should change when registers are added or removed. Where do you get this error? Can't find such a message in the sigmastate or this repo.

**Comment by anon-br** [comment]
Have you tried sorting the registers? Maybe out of order registers are resulting in wrong boxId.

**Comment by greenhat** [comment]
> Sometimes dapp developers forget to reset registers when moving boxes from contracts to user's address. It causes the box being stored with old register values as unspent txs.
> 
> When user try to spend that box it causes an error and user can't spend that box:
> 
> ```
> {
>     "code": 1,
>     "info": "Failed to parse ErgoBox from JSON string: JsValue(Object({\"boxId\":\"4e75f0db4dafbd37cd4fcafa862df48b3ef7cb486cd6e31e3a2033f7ce0eea2a\",\"transactionId\":\"3cf8edcbdadff81c140ce7ba1b610fb199f709ef72a0590cea42838516e269d7\",\"index\":0,\"ergoTree\":\"0008cd035263e8111debc9344571f8a28a319a60e392b57f5440f08208845cbdb317b639\",\"creationHeight\":777139,\"value\":\"1000000\",\"assets\":[{\"tokenId\":\"a49d2c831601b4798363620e0af84891cee8dacf0039694b72d44acc0337bb85\",\"amount\":\"1\"}],\"additionalRegisters\":{},\"confirmed\":true,\"extension\":{}})) \n with error: Box id parsed from JSON differs from calculated from box serialized bytes"
> }
> ```

This error is from ergo-lib. The registers are serialized as part of the box and the box id (hash of the serialized box) shows it. In the above JSON the registers are missing, but the box id provided in JSON is the same as in the box below with registers. The reason for this error is that the JSON above, from which the ErgoBox is parsed, is missing the registers. 

> 
> Here is how the box is stored on users wallet
> 
> ```
> {
>         "boxId": "4e75f0db4dafbd37cd4fcafa862df48b3ef7cb486cd6e31e3a2033f7ce0eea2a",
>         "transactionId": "3cf8edcbdadff81c140ce7ba1b610fb199f709ef72a0590cea42838516e269d7",
>         "index": 0,
>         "ergoTree": "0008cd035263e8111debc9344571f8a28a319a60e392b57f5440f08208845cbdb317b639",
>         "creationHeight": 777139,
>         "value": "1000000",
>         "assets": [
>             {
>                 "tokenId": "a49d2c831601b4798363620e0af84891cee8dacf0039694b72d44acc0337bb85",
>                 "amount": "1"
>             }
>         ],
>         "additionalRegisters": {
>             "R5": "0ea6037b22373231223a0a202020207b224e7574486f7573655f32223a0a20202020202020207b22436f6c6c656374696f6e223a20224e757448656164733344222c0a20202020226e616d65223a20224e7574486f7573655f32222c0a20202020226465736372697074696f6e223a20224e7574686561732061667465722066696e64696e67206c6f76652c2074686579206275696c64206120686f75736520746f206c697665206120676f6f64206c6966652e20416c6c204e7574686f757365206172652061637475616c203364206d6f64656c7320616e642063616e206265206465706c6f79656420696e73696465205369676d6156616c6c65792e222c0a20202020224261636b67726f756e64223a202256616c6c6579204261636b67726f756e64222c0a20202020224d61696e20486f757365223a202231204c6576656c2050696e6b20486f757365222c0a2020202022526f6f66223a202252656420526f6f66222c0a20202020225469746c65223a20224e7574686561647320536967682047726179222c0a2020202022526172697479223a2022636f6d6d6f6e227d0a7d0a7d0a0a0a",
>             "R6": "0e0130",
>             "R8": "0e204d2ea0baa48796d9b31ef3d26c176f0dbe32a570fc36c37fea292b9bf440aabf",
>             "R7": "0e020101",
>             "R9": "0e42697066733a2f2f62616679626569637573366570356d6f75776b343464636d6e6268757662376f7a717a746b6c6f6767626e636134763762756f7475656c78667934",
>             "R4": "0e154e75744865616433443a204e7574486f7573652332"
>         },
>         "confirmed": true
>     },
>```
 
> It seems like registers' values are not counted in when calculating box serialized bytes.

No, the serialized registers are always included in the serialized box.

**Comment by nirvanush** [comment]
> Registers are serialized, so box id should change when registers are added or removed. Where do you get this error? Can't find such a message in the sigmastate or this repo.

Found this error in the sigma-rust repo
https://github.com/ergoplatform/sigma-rust/blob/481748de7f7b830dfeefe9d6433947e2e04a1179/bindings/ergo-lib-wasm/src/box_coll.rs#L30

It happened when the user tried to sign a transaction with a box above as part of his transaction using nautilus wallet. So I guess it's not related to the wallet, but to sigma-rust.

**Comment by nirvanush** [comment]
> Have you tried sorting the registers? Maybe out-of-order registers are resulting in wrong boxId.
This is a good point, This box was in user's wallet, I guess he pulled it from some smart contract, but how they went out of order in the first place?

**Comment by nirvanush** [comment]
> This error is from ergo-lib. The registers are serialized as part of the box and the box id (hash of the serialized box) shows it. In the above JSON the registers are missing, but the box id provided in JSON is the same as in the box below with registers. The reason for this error is that the JSON above, from which the ErgoBox is parsed, is missing the registers.

The registers are not missing, they are just appear out of order. @greenhat

**Comment by greenhat** [comment]
> > This error is from ergo-lib. The registers are serialized as part of the box and the box id (hash of the serialized box) shows it. In the above JSON the registers are missing, but the box id provided in JSON is the same as in the box below with registers. The reason for this error is that the JSON above, from which the ErgoBox is parsed, is missing the registers.
> 
> The registers are not missing, they are just appear out of order. @greenhat

In the error message, the parsed JSON is included and it does not have registers:
```
{
    "code": 1,
    "info": "Failed to parse ErgoBox from JSON string: JsValue(Object({\"boxId\":\"4e75f0db4dafbd37cd4fcafa862df48b3ef7cb486cd6e31e3a2033f7ce0eea2a\",\"transactionId\":\"3cf8edcbdadff81c140ce7ba1b610fb199f709ef72a0590cea42838516e269d7\",\"index\":0,\"ergoTree\":\"0008cd035263e8111debc9344571f8a28a319a60e392b57f5440f08208845cbdb317b639\",\"creationHeight\":777139,\"value\":\"1000000\",\"assets\":[{\"tokenId\":\"a49d2c831601b4798363620e0af84891cee8dacf0039694b72d44acc0337bb85\",\"amount\":\"1\"}],\"additionalRegisters\":{},\"confirmed\":true,\"extension\":{}})) \n with error: Box id parsed from JSON differs from calculated from box serialized bytes"
}
```

**Comment by greenhat** [comment]
> Have you tried sorting the registers? Maybe out of order registers are resulting in wrong boxId.

No, it's not the case. Registers are always serialized in order (from R4 to R9).
