### ISSUE TITLE
Remove invalid transaction in a block from the mempool and invalidate it in delivery tracker

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1784]
If a transaction in a block turns out to be invalid (see `UtxoState.applyTransactions` ), pass transaction id (via custom exception?) and then invalidate this transaction in memory pool and delivery tracker. Do a test for it!

**Comment by pragmaxim** [comment]
Imho all is needed is removing the TX from mempool at this places : 
https://github.com/ergoplatform/ergo/blob/6a96896b3733882bac7784ab673a90ebe5fca29f/src/main/scala/org/ergoplatform/nodeView/ErgoNodeViewHolder.scala#L252

as `SemanticallyFailedModification` is published and `DeliveryTracker` updated : 
https://github.com/ergoplatform/ergo/blob/6ed3b23c3f22bf0c1deade9955f380b8ad74b061/src/main/scala/org/ergoplatform/network/ErgoNodeViewSynchronizer.scala#L853
