### ISSUE TITLE
Expose NiPoPoW relevant implementations as a dependency

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo#1813]
From ergoplatform/ergo-appkit#187 this is needed to have exposed to Appkit for client applications to adopt Nipopows:

* move NipopowProof, NipopowVerifier, and all dependent types from node code into a lib (ergo-wallet?);
* expose NipopowProof, NipopowVerifier, MerkleProof with mentioned above properties/methods in appkit public API.

Actually, I'm pretty sure that the above NiPoPoW-related types would better be in a dedicated ergo-nipopow lib since they are not directly related to wallet features. However, the bigger challenge will be the dependent more low-level types like Header, etc. Seems like they should be moved to their own separate lib (ergo-core/ergo-chain-types?).

**Comment by greenhat** [comment]
Hey! I missed this issue and made a new one https://github.com/ergoplatform/ergo/issues/1965 for the same task. Do you mind if I close this one?

**Comment by MrStahlfelge** [comment]
Feel free to close this one or the other one, depending on which one has a better description :)

**Comment by greenhat** [comment]
Closed in favor of #1965
