### ISSUE TITLE
Excessive growth of Actors queues

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo#1823]
### The problem

In order to reproduce, run Ergo node with profiler agent. 
```
java -Xmx3G -agentpath:/Applications/YourKit-Java-Profiler-2022.3.app/Contents/Resources/bin/mac/libyjpagent.dylib \
-Dlogback.stdout.level=ERROR \
-jar target/scala-2.12/ergo-4.0.39-41-45c6ab32-20220823-1743-SNAPSHOT.jar \
--mainnet -c ergo.conf
```
Connect Yourkit profiler and configure to automatically take memory snapshot when 80% of Java heap is allocated.
When the node is doing syncronisation soon enough allocation hit the 80% threshold and snapshot is taken.

Note, the contents of thus obtained snapshot is similar to the snapshot taken on OOM exception.

### Observations

The following observations are based on analysis of OOM exception snapshot.

It turns out that memory is quickly eaten up by ModifiersFromRemote messages that are sent from the ErgoNodeViewSynchronizer to the ErgoNodeViewHolder via actor's queue. (see Retained Size on the screenshot)
![IMAGE 2022-08-31 18:07:53](https://user-images.githubusercontent.com/654077/187726274-46f84942-9df5-4018-95e1-c37066bab6f6.jpg)

Observe that the links to the ModifiersFromRemote go from Envelop messages stored in Actor queues.

Such messages may contain heavy transactions/blocks (20Mb per message), while they are sent from the network layer at the rate of receipt (nodeViewHolder ! message is called from callback).

As a result, when the ErgoNodeViewHolder does not have time to process them, the queue begins to grow to several thousand messages, each of many MBytes. (see number of objects of class java.util.concurrent. ConcurrentLinkedQueue$Node)

The size of queues depends on relative speed of network and transaction validation in nodeViewHolder.
For this reason, OOM exception can be unstable if, for example, the network is slow.

To fix the problem, backpressure mechanism is needed between the network layer and the ErgoNodeViewHolder.

**Comment by pragmaxim** [comment]
Establishing backpressure between networking layer or `ErgoNodeViewSynchronizer` and `ErgoNodeViewHolder` is hard as `ErgoNodeViewHolder` broadcasts workload to `EventBus` and the subscribing components  does the heavy lifting.

I was trying to replace the `EventBus` for a week and then I gave up. Without replacing it, there is impossible to establish any backpressure as there is no feedback.

**Comment by kushti** [comment]
@aslesarenko I guess numbers provided with default node settings? I guess we should analyze two scenarios, with default settings, and with checkpoint switched off (as in future we need to avoid aggressive checkpointing) and 5.0 interpreter.

For the latter, a lot of memory is consumed by the interpreter, mostly inside kiama.rewriting.Strategy
.apply (called from Interpreter.checkCommitments).  

Will analyze the former soon.

**Comment by pragmaxim** [comment]
The shortest step that would be most useful : establishing backpressure at least in the `NodeViewHolder#processRemoteModifiers` method instead of relying on the messages being queued up. I already tried that but I did not get through all the tests failing.
