### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by futuristudios** [ergoplatform/ergo#1832]
Ergo node works normally behind NAT, so you can keep closed your 9030 port, hence other nodes could not discover and connect to **your~~s~~** one, only your node could initiate connections.

Ergo node works normally behind NAT, so you can keep closed your 9030 port, hence other nodes could not discover and connect to **your** one, only your node could initiate connections.

**Comment by kushti** [comment]
Corresponding part of readme is removed now
