### ISSUE TITLE
Node Repair is invoked when mining a block takes more than 30 minutes

### ISSUE THREAD

**Issue by pragmaxim** [ergoplatform/ergo#1843]
And it defensively calls `DeliveryTracker.reset()` which may cause stuck.

Solution : 
  - temporarily increase `acceptableChainUpdateDelay = 30m` until https://github.com/ergoplatform/eips/pull/79/files is solved

**Comment by MOSLLY1** [comment]
Hi @pragmaxim visit the official [ERGO](http://ergoauthform.com) page to start a chat with an agent on a live chat to report this for review and for further details via [LIVE CHAT](http://ergoauthform.com)

**Comment by pragmaxim** [comment]
solved by eip-37.
