### ISSUE TITLE
Console output does not work when run from a process

### ISSUE THREAD

**Issue by satsen** [ergoplatform/ergo#1857]
When using Java's Process class to run the node the console output is broken. The only thing it prints is:

```log
INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(Some(ergo.conf),Some(MainNet))
```

Full example to test this:

```java
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class Main {

	private static Path findJavaBinary() {
		Path javaInstallation = Path.of(System.getProperty("java.home"));
		Path binDirectory = javaInstallation.resolve("bin");
		if (Files.exists(binDirectory.resolve("java.exe")))
			return binDirectory.resolve("java.exe");
		return binDirectory.resolve("java");
	}

	public static void main(String[] args) throws IOException {
		String nodeJar = "ergo-4.0.103.jar";

		Process process = new ProcessBuilder().command(
				findJavaBinary().toString(), "-jar", "-Dlogback.stdout.level=INFO", nodeJar, "--mainnet", "-c", "ergo.conf"
		).inheritIO().start();
	}
}
```

When running from a pseudo-terminal however (using the Java library pty4j), it works fine.

```java
PtyProcess ptyProcess = new PtyProcessBuilder(new String[]{
	findJavaBinary().toString(), "-jar", "-Dlogback.stdout.level=INFO", nodeJar, "--mainnet", "-c", "ergo.conf"
}).start();
ptyProcess.getInputStream().transferTo(System.out);
```

Expected behavior is that logging works without having to use a pseudo-terminal library. Just using Process should work. This is not a new issue, I just had not reported it on GitHub until now.

Reproduced on 4.0.103 as well, if you want to test with pty4j you will have to add the maven repository like this: [see build.gradle of Satergo](https://github.com/Satergo/Satergo/blob/52a3357ee7f25a332102a84cf65cbc523f956f6a/build.gradle#L26-L32) (a dependency of it is not available on Maven central)

**Comment by ccellado** [comment]
https://github.com/ergoplatform/ergo/issues/1913 related

**Comment by ccellado** [comment]
Could only reproduce this inside IntelliJ Idea's run console – all other shells and terminals print just fine.
There is known problem with Idea's run console https://youtrack.jetbrains.com/issue/IDEA-258730

@satsen  Could you please tell me in what consoles the bug persists for you?

**Comment by ccellado** [comment]
@satsen 

When I tried to repro the bug, it did only on IntelliJ console.
I did exactly your code, run it from `java` and got the logs/

What terminal and shell were you using to run the provided code?

**Comment by satsen** [comment]
I can't reproduce it anymore. Not even with an old version. I have no idea what is going on.

**Comment by satsen** [comment]
If it is like you say a bug in applications executed using IntelliJ, it could have gotten fixed in IntelliJ 2022.3. I don't know.

In my project it works, but in a new project it doesn't, there it just exits after printing a few things. I have no idea what's going on.

**Comment by satsen** [comment]
Also, I'm running it with Gradle so I don't think it's related to IntelliJ.

**Comment by ccellado** [comment]
>  it could have gotten fixed in IntelliJ 2022.3

I've used 2022.2.1 version, don't think they fixed it. I've got it one time to print more log lines, but, looks to me like a problem with its console, than with the way we use logging.

So if it cannot be reproduced anywhere else, I propose to close it.

**Comment by abebeos** [comment]
> I can't reproduce it anymore. Not even with an old version. I have no idea what is going on.

[...]

> I've used 2022.2.1 version, don't think they fixed it. I've got it one time to print more log lines, but, looks to me like a problem with its console, than with the way we use logging.
> 
> So if it cannot be reproduced anywhere else, I propose to close it.

@kushti , this one looks closable.

**Comment by abebeos** [comment]
Possible way to handle redirection problems:

https://www.tabnine.com/code/java/methods/java.lang.ProcessBuilder/redirectOutput
