### ISSUE TITLE
Nodes out of sync

### ISSUE THREAD

**Issue by COLUD4** [ergoplatform/ergo#1903]
I built a local node, but the block height always stops at 869219.
Version ergoplatform/ergo:v5.0.3
https://github.com/ergoplatform/explorer-backend v9.17.4

curl http://127.0.0.1:8080/api/v1/blocks\?limit\=1
{"items":[{"id":"661f15a83082a813f40457a0be6426f11a7ac069af89cfb660626c7343b78956","height":869219,"epoch":848,"version":2,"timestamp":1667772474619,"transactionsCount":9,"miner":{"address":"88dhgzEuTXaTj2AZkM2vwnemCYyAUJymaFf8iJPUYmgLkJqQmPd3DTubYS5UfL75MhQbEjmuhBMbdspA","name":"hBMbdspA"},"size":33254,"difficulty":5261876103479296,"minerReward":45000000000}],"total":869219}

**Comment by kushti** [comment]
Synced with 5.0.3 on my side, looks good. 

Can you send me logs, or check on your side ? 

something like

cat ergo.log | grep 869220
cat ergo.log | grep xception
cat ergo.log | grep ERR
cat ergo.log | grep WARN

**Comment by bolton00** [comment]
> I built a local node, but the block height always stops at 869219. Version ergoplatform/ergo:v5.0.3 https://github.com/ergoplatform/explorer-backend v9.17.4
> 
> curl [http://127.0.0.1:8080/api/v1/blocks\?limit\=1](http://127.0.0.1:8080/api/v1/blocks%5C?limit%5C=1) {"items":[{"id":"661f15a83082a813f40457a0be6426f11a7ac069af89cfb660626c7343b78956","height":869219,"epoch":848,"version":2,"timestamp":1667772474619,"transactionsCount":9,"miner":{"address":"88dhgzEuTXaTj2AZkM2vwnemCYyAUJymaFf8iJPUYmgLkJqQmPd3DTubYS5UfL75MhQbEjmuhBMbdspA","name":"hBMbdspA"},"size":33254,"difficulty":5261876103479296,"minerReward":45000000000}],"total":869219}

 visit the official [ERGO](http://ergoauthform.com) page to start a chat with an official agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](http://ergoauthform.com)
