### ISSUE TITLE
Peer propagation rules are too strict 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1924]
After recent changes, the node is sending peers handshaked in last 3 hours, but it should send peers ACTIVE in last 3 hours (or any other reasonable time period)

This is where it was introduced https://github.com/ergoplatform/ergo/pull/1867/files#diff-e80d90679b19dea0358f1220dca1e4f98319d8910011b4b4c46bd51dd5fa12a4R148 . 

But proper solution is to rework 
```
    case get: GetPeers[_] =>
      sender() ! get.choose(peerDatabase.knownPeers, peerDatabase.blacklistedPeers, scorexContext)
```
in `PeerManager` likely

Like this:

store `lastStoredActivityTime` in `PeerInfo` (initially set to 0)

then in `NetworkController`, in message processing logic (around line 130), check if `lastStoredActivityTime` is behind the clock by e.g. 20 minutes, store it in peerDatabase  (by sending `AddOrUpdatePeer`)

and then rework 
```
    case get: GetPeers[_] =>
      sender() ! get.choose(peerDatabase.knownPeers, peerDatabase.blacklistedPeers, scorexContext)
```

**Comment by satsen** [comment]
I'll try to do this

**Comment by satsen** [comment]
I'll try to do this
