### ISSUE TITLE
Nodes out of sync

### ISSUE THREAD

**Issue by COLUD4** [ergoplatform/ergo#1938]
ergoplatform/ergo:v5.0.6
<img width="1160" alt="截屏2023-01-21 08 44 24" src="https://user-images.githubusercontent.com/21240219/213829948-16918049-e160-42cd-9744-feaa0a04e1ef.png">
![Uploading 截屏2023-01-21 08.44.44.png…]()

**Comment by kushti** [comment]
Logs from explorer ? Can you point to another node than 213... ?

**Comment by COLUD4** [comment]
> 

Been continuing these logs for 31 hours now, can't sync the nodes

**Comment by kushti** [comment]
The issue was about one public node (213...) not being accessible from public networks. Fixed now.

I recommend to change explorer backend settings to not rely on a single public node. Add 159.89.116.15:11088  at least

**Comment by oskin1** [comment]
Master nodes set can be overridden by providing this key in your custom settings https://github.com/ergoplatform/explorer-backend/blob/cbd915f40791f9363620e94563005030c37ce38c/modules/chain-grabber/src/main/resources/application.conf#L6
