### ISSUE TITLE
Wallet rescan speed up

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo#1967]
Discovered in https://github.com/ergoplatform/oracle-core/issues/242

During the governance testing of oracle-core v2 in the ERG/XAU pool on testnet we experienced a 5+ hours wallet rescan, which caused the pool downtime. 
The initial wallet rescan was unbearably slow on my node, but after a node restart, it finished in 5 minutes. Upon exploring the node process, it seemed that before the restart, the bottleneck was the CPU. This leads me to believe there might be an opportunity to speed up the wallet rescan process.

**Comment by jellymlg** [comment]
@greenhat No matter what I do it only takes 5 minutes on my machine, and most of that time is spent on db lookups.
![image](https://user-images.githubusercontent.com/39315532/229196195-e6c8916f-20c9-44f0-bcd3-14fd1b1ad46b.png)

Could you provide some more details, like logs or the number of boxes in address?

**Comment by greenhat** [comment]
Thanks for looking into this issue! I did the profiling after I triggered rescan (~10 blocks / sec), and here is the dump - https://gist.github.com/greenhat/d7c9462d4b47200b1297f33e496b0d06
and the flamegraph - https://gist.github.com/greenhat/46d4331883cba088b781f843a42427a6

**Comment by reqlez** [comment]
100% confirm DeathScan situation here. 100% CPU core. I been scanning my TESTNET ( NOT JOKING ) wallet for 3+ days now, and it's finally close to being finished. This is my mining wallet, however, I moved all the UTXOs out of there ( most of them ) before I started the scan.

**Comment by jellymlg** [comment]
> 100% confirm DeathScan situation here. 100% CPU core. I been scanning my TESTNET ( NOT JOKING ) wallet for 3+ days now, and it's finally close to being finished. This is my mining wallet, however, I moved all the UTXOs out of there ( most of them ) before I started the scan.
> 
> Near the end of the scan ( last 20% or so ) my wallet is scanning at exactly 1 block per second. 60% into it, it was doing about 2 blocks per second. And first 50% or so, it was a lot faster.
> 
> I'm happy to even share a backup of that wallet with you so you can see for yourself. Maybe it's this VM, or maybe it's the wallet... not sure, but CPU at 100% and doing 1 block per second, just seems something very wrong with it.

Please send a backup then 😃

**Comment by reqlez** [comment]
> 

I will send DM on Discord ;-)
