### ISSUE TITLE
[REPO] Some task re repository here

### ISSUE THREAD

**Issue by abebeos** [ergoplatform/ergo#1969]
(cannot do myself, have no access rights. Thus asking for it)

- [ ] Update/Close Milestones https://github.com/ergoplatform/ergo/milestones
- [ ] Update Issues, especially: ensure that the fulfilled bounties are closed
- [ ] Remove unused labels (e.g. the ergo bounties)
- [ ] link to bount-process (https://github.com/ergoplatform/grow-ergo/)
  - [[ ] Describe the bounty-process] 
  - [x] #1972
- [ ] Ensure transparency of development, example
  - [x] https://github.com/ergoplatform/ergo/issues/1366#issuecomment-1497676004

**Comment by kushti** [comment]
thanks, will reconsiders milestones

**Comment by abebeos** [comment]
@kushti , may I suggest this (to avoid redundant effort on both sides):

- add a bounty to this issue
- provide me with issue-tracker/github access (this should be the "collaborator" invite)
- I polish your project resources a bit, and triage the issues
- I make it easier for newcomers to contribute

(I'll write down all my changes so you can revert if you do not like)
