### ISSUE TITLE
Clarify Bounty-Process, 

### ISSUE THREAD

**Issue by abebeos** [ergoplatform/ergo#1972]
It is not clear how the bounties are payed-out

Example: 

> Yeah, this was merged into [4.0.105](https://github.com/ergoplatform/ergo/releases/tag/v4.0.105) ... Bounty was not paid though.

- https://github.com/ergoplatform/ergo/issues/1854#issuecomment-1494281154

The process should be clarified.

(remember that decentralization is about "transparency" and "lack of centralized power")

---

              > Is there any documentation about the bounty process?

https://github.com/ergoplatform/grow-ergo/

process is not described.

_Originally posted by @abebeos in https://github.com/ergoplatform/ergo/issues/1854#issuecomment-1496665978_

**Comment by kushti** [comment]
For bounties, please reach me over Discord or Telegram

**Comment by abebeos** [comment]
> For bounties, please reach me over Discord or Telegram

I can reach out on those systems, but you have here in public this:

> Yeah, this was merged into [4.0.105](https://github.com/ergoplatform/ergo/releases/tag/v4.0.105) ... Bounty was not paid though.
https://github.com/ergoplatform/ergo/issues/1854#issuecomment-1494281154

You cannot simply leave it uncommented, this is simply not right, and has a negative impact on ERGO (as it looks like the project is out of bounty funds)
