### ISSUE TITLE
ERROR: "Calculated proofHash is not equal to the declared one"

### ISSUE THREAD

**Issue by abebeos** [ergoplatform/ergo#1973]
## Status

Bug is isolated, and quick-fixed. 

```sh
# stress-test run aborted after tmp dir got full
real    524m48.719s
user    817m35.823s
sys     30m50.448s
```

### Confirmation

@kushti , it seems that you are the only member active on this repo.

- [x] I need just a confirmation that those 2 issues are still open, and the bounties available:
  - [ ] #1387
  - [ ] #1023

Confirmed within https://github.com/ergoplatform/ergo/issues/1973#issuecomment-1509298172

### Bounties

Additionally, it would need some clarifications on how the bounties are payed out.

The bounty process is currently unclear.

A dev is complaining publicly about "merged, but bounty not payed out"

You did not comment, despite multiple queries:

- [ ] https://github.com/ergoplatform/ergo/issues/1972

### Blocking

Needs to be fixed first:
- [x] https://github.com/ergoplatform/ergo/issues/1979
  - [ ] Needs to get bounty-budget first

### Duplicates

The bug is 5 years old, there are several duplicates

- #289
- #670
- #682
- #1606

**Comment by kushti** [comment]
Those issues are about the same issue, which is hard to catch.

You need to iterate over the tree thousands of times, catch where proof bytes will be different, do structural diff and find how it appears. 


I suggest to start with something simpler. e.g. https://github.com/ergoplatform/ergo/issues/1976

**Comment by abebeos** [comment]
@kushti , it is highly annoying and unprofessional to ignore a concrete question for days, and to then comment off-topic in a patronizing way. 

I suggest that you simply answer my (very founded) question:

> The bounty process is currently unclear.

> Clarify Bounty-Process,  #1972

And let me pick the issues I choose to pick, difficult or not.

**Comment by abebeos** [comment]
> You need to iterate over the tree thousands of times, catch where proof bytes will be different, do structural diff and find how it appears.

No, I don't. I need to ignore what you say, and hunt the bug based on my experience/intuition.

**Comment by abebeos** [comment]
(12 days. Twelve!!! To get a comment "this is very difficult". I simply cannot believe what is happening here)

**Comment by abebeos** [comment]
> I suggest to start with something simpler. e.g. #1976

I'm not interested in such junior-dev grade tasks.

**Comment by abebeos** [comment]
something tells me that no one in this project is interested that contributors fix bounty issues. Are you out of bounty funds?

Why don't you reply to this: https://github.com/ergoplatform/ergo/issues/1023#issuecomment-1504214878 and instead point me to "code-monkey" tasks?

**Comment by kushti** [comment]
ok ,work #1023 / #1387 since you claim you've reproduced it

**Comment by abebeos** [comment]
k, just please clarify how you process the bounties:

https://github.com/ergoplatform/ergo/issues/1972

I assume: after merge, you make a transaction within 24h?

 (clarify this not only for me, you really need to update your general documentation. I can send a PR in once I have the information)
