### ISSUE TITLE
Cannot conn to OTP 26 node for not handle ["UNLINK_ID"].**

### ISSUE THREAD

**Issue by bighunter513** [ergoplatform/ergo#2006]
one node is OTP 26 server, use ergo node to conn, 
otp server has Error msg:
"Connection attemp from node 'xxx' rejected since it cannot handle ["UNLINK_ID"].**

**Comment by kushti** [comment]
OTP 26 is something Erlang-related it seems, as well as ["UNLINK_ID"]. How can be Ergo node related to Erlang?
