### ISSUE TITLE
API tests

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#203]
Write tests for node API end check, that response corresponds to API documentation in `src/main/resources/api/openapi.yaml`

**Comment by ClockworkOrange605** [comment]
@catena2w what kind of testing you prefer? unit testing with mocks or functional testing with the real request to the running node?

**Comment by ClockworkOrange605** [comment]
duplicate #157

**Comment by andyceo** [comment]
@ClockworkOrange605 hi!

Sorry for long answer. We did fully integrational tests with real requests to running node.

See this utility: https://hub.docker.com/r/andyceo/openapi-checker/

And parameters file: https://github.com/ergoplatform/ansible/blob/master/files/parameters.yaml

I close this as utility is written already and OpenAPI tests are currently integrated in our Jenkins pipeline.
