### ISSUE TITLE
Unspent and Spent Box By Token Id Node Endpoint Request

### ISSUE THREAD

**Issue by mgpai22** [ergoplatform/ergo#2038]
This would be useful for working with contracts which contains singletons!

**Comment by pulsarz** [comment]
I need(ed) this too for hodlcoin.co.in UI. Also needs to take into account mempool for unspent box (or atleast a parameter to enable this).

Current hacky workaround is fetching entire mempool and searching for the unspent output that contains the token, if not found do a call to explorer.

But we want to eliminate any explorer calls.
