### ISSUE TITLE
Release script

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#2083]
Make a shell script `do-release.sh`, which is:

* checking Java version (`java -version` , should be 1.8.x)
* removing /target folder
* calling `sbt clean assembly`
* extracting version from .jar file in `target/scala-2.12/ergo-xxx.jar'
* checking that the version in `src/main/resources/application.conf` (e.g. `appVersion = 5.0.16`) is corresponding to the jar version, if not, remove the jar file and exit with error
* checking that version (`info/version`) in `src/main/resources/api/openapi.yaml` and `src/main/resources/api/openapi-ai.yaml` is  is corresponding to the jar version, if not, remove the jar file and exit with error

**Comment by ross-weir** [comment]
ill work on this
