### ISSUE TITLE
AppendFullBlock fails if (validMKV._1.head == 1)

### ISSUE THREAD

**Issue by stenolog** [ergoplatform/ergo#2117]
- re https://github.com/ergoplatform/ergo/issues/2114

### ErgoStateContextSpec

```scala
    // valid application of correct extension
    sc.appendFullBlock(fbWithFields(validMKV +: oldFields)) shouldBe 'success
```

this fails, when `(validMKV._1.head == 1)`

### Reproducer

- https://github.com/ergoplatform/ergo/pull/2116

### Tasks

process this issue in context of https://github.com/ergoplatform/ergo/issues/2118

- [ ] Identify and document root-cause
- [ ] fix
- [ ] remove the workaround added

**Comment by kushti** [comment]
the cause is described  in the test https://github.com/ergoplatform/ergo/pull/2116/files#diff-170e3797d0ebd558c2bd8b957f41158dc8c306e478cdd2a537469c2e2c166712R87 , I see nothing to fix here (just not using key space with specific semantics is okay for the test of interest)
