### ISSUE TITLE
Local network with two nodes and same wallet have different amount of cryptocurrency

### ISSUE THREAD

**Issue by swag-eag** [ergoplatform/ergo#2175]
I have a local ergo blockchain with two nodes:
- node 1:
```
ergo {
  networkType = "mainnet"
  directory = "/home/emilio/ergo/ergo-mainnet-swa/data"

  node {
    mining = true
    offlineGeneration = true
    useExternalMiner = false
    # To work with SAFEW:
    extraIndex = true
  }

  chain {
    addressPrefix = 96
    epochLength = 30
    oneEpochReduction = 0
    minerRewardDelay = 30
    reemission {
      checkReemissionRules = true
    }
  }

  wallet {
    checkEIP27 = true
    mnemonic = "maximum market scatter fancy sleep begin more awesome defense obscure allow august forget artist solve"
  }
}

scorex {
  network {
    magicBytes = [1, 1, 8, 1]
    bindAddress = "0.0.0.0:9022"
    nodeName = "ergo-mainnet-swa"
    knownPeers = []
  }

  restApi {
    bindAddress = "127.0.0.1:9122"
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
```
- node 2:
```
ergo {
  networkType = "mainnet"
  directory = "/home/emilio/ergo/ergo-mainnet-swa-1/data"

  node {
    mining = true
    offlineGeneration = true
    useExternalMiner = false
    # To work with SAFEW:
    extraIndex = true
  }

  chain {
    addressPrefix = 96
    epochLength = 30
    oneEpochReduction = 0
    minerRewardDelay = 30
    reemission {
      checkReemissionRules = true
    }
  }

  wallet {
    checkEIP27 = true
    mnemonic = "maximum market scatter fancy sleep begin more awesome defense obscure allow august forget artist solve"
  }
}

scorex {
  network {
    magicBytes = [1, 1, 8, 1]
    bindAddress = "0.0.0.0:9023"
    nodeName = "ergo-mainnet-swa-1"
    knownPeers = ["127.0.0.1:9022"]
  }

  restApi {
    bindAddress = "127.0.0.1:9123"
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}

```
I got rewards from mining... But the same wallet has different amounts!:
- node 1
![image](https://github.com/user-attachments/assets/e81ae0e2-0639-467e-b132-bdf759dcbe05)
- node 2:
![image](https://github.com/user-attachments/assets/5de0e4d7-62db-4fe7-b9cd-b28c97d23070)

How is it possible!

and SAFEW does not find the wallet!

I do not understant it is so difficult...

Any help is welcome

**Comment by kushti** [comment]
are the nodes on the same height? were rewards withdrawn to "normal" address? Any derived addresses generated ? 

What does it mean "and SAFEW does not find the wallet!"  ?

**Comment by swag-eag** [comment]
are the nodes on the same height? No (but... why not?)
- node 1
![image](https://github.com/user-attachments/assets/c1e7e114-05d1-40e1-87f0-943a1fcaba53)
- node 2
![image](https://github.com/user-attachments/assets/6fed96c7-01b5-4d12-bbeb-ca09d3bfb477)

Any derived addresses generated ? No, I do not what is that

What does it mean "and SAFEW does not find the wallet!" ?

SAFEW node 1:
![image](https://github.com/user-attachments/assets/1e18144c-65e9-499d-85ac-2fd4fb97162d)
Secret phrase: maximum market scatter fancy sleep begin more awesome defense obscure allow august forget artist solve
![image](https://github.com/user-attachments/assets/c76ff4d6-f4f8-4906-9d33-b2f62ccbce29)
![image](https://github.com/user-attachments/assets/0f62e8c7-9da6-4972-8a10-a350cc84f419)

Forever!!

- node 1 with Ergo Wallet:
![image](https://github.com/user-attachments/assets/68f2fae2-9bfe-44dd-a4de-e9f88f2b515b)
Same wallet:
![image](https://github.com/user-attachments/assets/074d100b-47f4-4cf5-8a87-64e01a8513db)
0 ERG!
![image](https://github.com/user-attachments/assets/f7265830-2180-4bc1-b847-3150380a4743)

I really miss information to make a local blockchain work...

Regards
