### ISSUE TITLE
Mining stopped for few hours

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#245]
no logs in logfile

**Comment by catena2w** [comment]
can not reproduce

**Comment by andyceo** [comment]
Logs from mine01 node from last 2 days: [mine01-fail.tar.gz](https://github.com/ergoplatform/ergo/files/2188221/mine01-fail.tar.gz)

**Comment by andyceo** [comment]
Logs from mine02 node from last 2 days: [mine02-fail-ergo.2018-07-11and12.log.gz](https://github.com/ergoplatform/ergo/files/2188364/mine02-fail-ergo.2018-07-11and12.log.gz)
