### ISSUE TITLE
Integration tests for header, transaction, block application in single node

### ISSUE THREAD

**Issue by mike-aksarin** [ergoplatform/ergo#254]
Add integration tests for single node. Some of them could be similar to what we have in `ErgoNodeViewHolderSpecification`. Implement this for different types of node.

* apply valid block header
* discard invalid block header
* apply valid full block
* discard invalid full block
* add valid transaction to blockchain
* discard invalid transaction
* *discard invalid block that passes history validation but fails state validation and vice versa*
* ...look for more tests

**Comment by greenhat** [comment]
I'm looking into it.
