### ISSUE TITLE
Integration tests. Uniquely name docker resources and clean up on start.

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo#278]
Following our discussion with @mike-aksarin :

Problem.
Running tests for the second time after a crash fails due to docker resources (containers, network) being re-used which is not intended(container name conflicts, network subnet != container.ip, etc.).

Solution
- use unique names for containers and network with `ergo-itest-` prefix;
- delete existing `ergo-itest-*` containers and network on test suite launch;

Note: In case of simultaneously running tests we can further isolate them by including commit hash/branch name/etc. in the name prefix.

**Comment by mike-aksarin** [comment]
We have also related task to cleanup docker images from the disc #270
