### ISSUE TITLE
Block info `not-found` via api

### ISSUE THREAD

**Issue by daron666** [ergoplatform/ergo#322]
There is two block on height 9535 http://88.198.13.202:9052/blocks/at/9535

The first could be obtained through api [here](0075674140dc7360299473f709758ea7cfb189b2ad4fda13a2cc0b81f3c0282a)
The second one will return error message `not-found` instead of block info [here](http://88.198.13.202:9052/blocks/00a5f791e249da164911b98dfcc173cbd88888d27a4e03e6d5d8ca8ca02872bb)

Checked on nodes : `http://88.198.13.202:9052/` and `http://209.97.136.204:9052/`

**Comment by catena2w** [comment]
already fixed

**Comment by catena2w** [comment]
duplicate of https://github.com/ergoplatform/ergo/issues/629
