### ISSUE TITLE
Add core operations to transaction cost

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#340]
Currently, transaction cost reflects only script execution cost. Core efforts to parse transaction and make needed checks are not counted. 

We can add at least assets preservation rules check to the cost function, at least. As a simplest option, we can count preservation rules implemented as a \Sigma script (but that cost could be unreasonably high).

**Comment by catena2w** [comment]
I'd like to add cost validation of tokens here and remove hardcoded limit for number of tokens in a Box and in a Transaction

**Comment by catena2w** [comment]
See `ErgoTransaction.getAssetsMap` and `ErgoBox.MaxTokens` and `ErgoTransaction.MaxTokens`

**Comment by catena2w** [comment]
implemented in v2.0
