### ISSUE TITLE
Assets json encoder

### ISSUE THREAD

**Issue by daron666** [ergoplatform/ergo#349]
I was playing with api and found that assets is being encoded as Array Of Arrays, instead of Array of Objects.

Example could be found [here](http://localhost:9052/blocks/75cefbc2d780c9907668aaaa8ff290a8229ff6cf8fce4dfc786b467971a3b2d8) 

![image](https://user-images.githubusercontent.com/1447374/42501187-376b6ffe-8444-11e8-95f7-336cd4512b29.png)

**Comment by dashengSun** [comment]
Hey, @daron666 could you help review the PR?
