### ISSUE TITLE
Integration test for the long-chain synchronization

### ISSUE THREAD

**Issue by mike-aksarin** [ergoplatform/ergo#352]
Add integration test with the two nodes:
1) First node generates a long blockchain over 500 blocks.
2) Second node synchronises with the first one.

Synchronisation should complete successfully

**Comment by mike-aksarin** [comment]
Here is integration test for the long chain. Currently it's ignored as nodes do not pass it:

https://github.com/ergoplatform/ergo/blob/master/src/it/scala/org/ergoplatform/it/LongChainSpec.scala

**Comment by oskin1** [comment]
Closed #389, #361, #516
