### ISSUE TITLE
Test OpenAPI with openapi-checker in ergo-it

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/ergo#397]
We need to integrate OpenAPI checks in ergo-it.

See this utility: https://hub.docker.com/r/andyceo/openapi-checker/

And parameters file: https://github.com/ergoplatform/ansible/blob/master/files/parameters.yaml

Test must:

1. Generate some chain
2. Did checks it does already
3. Generate parameters.yml file with parameters related to current chain, to check every OpenAPI endpoint with parameter
4. Run tests with command like that:

```
sudo docker run --rm \
    -v /path/to/openapi.yaml:/app/openapi.yaml \
    -v /path/to/parameters.yaml:/app/parameters.yaml \
    andyceo/openapi-checker openapi.yaml --api http://127.0.0.1:81 --parameters parameters.yaml
```

5. Grab tests results from container stdout and stderr and save as logs

**Comment by oskin1** [comment]
Closed #470
