### ISSUE TITLE
Change API errors content type to json

### ISSUE THREAD

**Issue by mike-aksarin** [ergoplatform/ergo#413]
Currently API provide `application/json` content type for successful responses and default `text/plain` for error responses. We need to unify response content type. This task depends on  similar Scorex task: ScorexFoundation/Scorex#304

1) Move Scorex API errors to `application/json` (ScorexFoundation/Scorex#304) and update Scorex version in Ergo
2) Override default akka http error handling.
3) Update application yaml file.

**Comment by oskin1** [comment]
#491
