### ISSUE TITLE
Write failed

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#444]
In case of big blocks (e.g. generated by ChainGenerator with 100Kb size), there are errors like
```
16:45:12.945 WARN  [ctor.default-dispatcher-4] s.c.n.PeerConnectionHandler - CommandFailed(Write(ByteString(0, 0, 0, 17, 18, 52, 86, 120, 2, 0, 0, 0, 4, 17, -38, 109, 31, 0, 0, 0, 0),NoAck(null))) because of akka.io.TcpConnection$$anon$2: Dropping write because queue is full: Failed to write 21 bytes to static.239.93.46.78.clients.your-server.de/78.46.93.239:29003 in state WorkingCycle
```
and connections are closed. Solution may be in increasing buffer size in akka
https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf

**Comment by oskin1** [comment]
Will be fixed with https://github.com/ScorexFoundation/Scorex/pull/331
