### ISSUE TITLE
Asset issue

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#450]
- [x] Create API route to issue an asset
- [x] Issue and transfer assets in tx generator

**Comment by catena2w** [comment]
I think in API asset issue should be similar asset issue in Waves/Ethereum and contain some usual fields, like Amount, Name, Description, Decimals. These fields should be put to registers, simplifying assets identification.

**Comment by oskin1** [comment]
Closed #488, #493, #495
