### ISSUE TITLE
Broken OpenApi methods

### ISSUE THREAD

**Issue by oskin1** [ergoplatform/ergo#464]
`GET /blocks/lastHeaders/{count} -> /blocks/lastHeaders/2
Request errors: [] Response errors: [OpenAPISchemaError('Unsupported base16 format unmarshalling',)]`
`GET /info
Request errors: [] Response errors: [UndefinedSchemaProperty("Undefined properties in schema: {'genesisBlockId'}",)]`

**Comment by catena2w** [comment]
closed by https://github.com/ergoplatform/ergo/pull/466#pullrequestreview-158957136
