### ISSUE TITLE
OpenApi checker is unable to properly validate base16 string

### ISSUE THREAD

**Issue by oskin1** [ergoplatform/ergo#467]

**Comment by catena2w** [comment]
what is the issue?

**Comment by oskin1** [comment]
OpenAPI Spec validator library (used for open api tests) does not support base16 format strings validation and thus marks each base16 encoded value as invalid. This leads to failed tests.

**Comment by andyceo** [comment]
We should wait for new release of https://github.com/p1c2u/openapi-core lib with custom formats validators support, and then I fix this issue.
