### ISSUE TITLE
Port consistency in configs, code, and docs 

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/ergo#485]
Write it-test that read ports in main configuration file and search for port substring in files:

- README.md
- Dockerfile
- ... some other files?

and fails if port substring not found at least in one of the files.

This can help to maintain consistency about used ports with Docker image and documentation and throughout all codebase.

**Comment by catena2w** [comment]
don't think it should be it-test, might be done much simplier

**Comment by catena2w** [comment]
Only one more change left with the mainnet launch, don't think we need any optimization here
