### ISSUE TITLE
Fix asset issue functionality

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#512]
Looks like tx generator is broken after last changes, I expect the problem is with the minimum amount of ergo in a box. Please:
- [x] Fix tx generator
- [x] Write a test for tx generator to ensure, that this situation won't happen in future.

**Comment by oskin1** [comment]
API for asset issuing is broken as well

- [ ] Fix asset issue API

**Comment by oskin1** [comment]
Closed #521
