### ISSUE TITLE
Implement and execute some non-trivial smart contract in Ergo testnet

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#526]
For the beginning take some simple examples, like `if(height < 100) payToPk1 else payToPk2` and execute them in current testnet. Ensure we have everything for this (in Wallet, API, etc.).
If everything will be fine - I think some (possibly video) tutorial would be useful

**Comment by oskin1** [comment]
I locked 2.0012 ERG with this script:
```
{
    val thirdPartyPk = PK("tJPvQhF2s5fFE1DNH8p2gd2Bkk8HAgFVSetvD1xCDVA6MayDCHbj76")
    atLeast(2, Array(thirdPartyPk, myPubKey_1, myPubKey_3))
}
```
And then successfully spent it (https://testnet.ergoplatform.com/en/transactions/0c4a06976a9c2692e407d37466adac7ce703b5aee19c4e63c92be88358370897)
