### ISSUE TITLE
Wallet improvements

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#529]
`ErgoWallet` implementation is incomplete now. Before mainnet we need:
- [x] Disc persistence, see https://github.com/ergoplatform/ergo/issues/460
- [x] Correct seed storage. It should not be stored as a plain text in config file
- [ ] Correct recovery on startup - we should check, that it is consistent with State and History
- [ ] Correct initialization and rollback of state context
- [ ] P2SH support - allow to save custom scripts in a wallet db and start watching these addresses (also checking the possibility of spending)

**Comment by catena2w** [comment]
Splited into https://github.com/ergoplatform/ergo/issues/749, https://github.com/ergoplatform/ergo/issues/748 and https://github.com/ergoplatform/ergo/issues/747

**Comment by oskin1** [comment]
Closed via #705
Tasks left:
https://github.com/ergoplatform/ergo/issues/747
https://github.com/ergoplatform/ergo/issues/748
https://github.com/ergoplatform/ergo/issues/749
