### ISSUE TITLE
Slow transaction verification

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#645]
Transaction with many inputs and outputs (inputs are protected by just TRUE proposition) are slow to verify. This is critical for security. 

Code to reproduce:

```
    val txGen = validErgoTransactionGenTemplate(3, 5, 600, 800)
    forAll(txGen) { case (from, tx) =>
      val t0 = System.currentTimeMillis()
      val initTxCost = tx.statefulValidity(from, emptyStateContext).get
      val t = System.currentTimeMillis()

      println("Tx cost:" + initTxCost)
      println("Tx size: " + tx.bytes.length)
      println("Input tokens: " + from.map(_.additionalTokens.size).sum)
      println("Output tokens: " + tx.outputCandidates.map(_.additionalTokens.size).sum)
      println("tx validation time: " + (t - t0))
      println("================================")
    }
```

Results on a laptop with overall good performance:

Tx cost:701
Tx size: 44859
Input tokens: 0
Output tokens: 0
tx validation time: 6298
================================
Tx cost:628
Tx size: 31956
Input tokens: 0
Output tokens: 0
tx validation time: 3645
================================
Tx cost:744
Tx size: 38205
Input tokens: 0
Output tokens: 0
tx validation time: 4725
================================
Tx cost:58233
Tx size: 37158
Input tokens: 114
Output tokens: 233
tx validation time: 3946
================================
Tx cost:864
Tx size: 33818
Input tokens: 0
Output tokens: 1
tx validation time: 3690
================================
Tx cost:47707
Tx size: 34981
Input tokens: 95
Output tokens: 185
tx validation time: 3082
================================
Tx cost:49025
Tx size: 35950
Input tokens: 96
Output tokens: 196
tx validation time: 3234
================================
Tx cost:783
Tx size: 39828
Input tokens: 0
Output tokens: 0
tx validation time: 4862
================================
Tx cost:26537
Tx size: 43439
Input tokens: 49
Output tokens: 111
tx validation time: 5185
================================
Tx cost:31444
Tx size: 45700
Input tokens: 60
Output tokens: 127
tx validation time: 5045
================================

**Comment by oskin1** [comment]
This security issue could be solved by charging some fixed cost (adjustable via miners voting) for each input/output.
