### ISSUE TITLE
Fail immediately on initial cost of a transaction being too big

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#656]
Currently, a transaction with a lot of inputs still will consume a lot of time. initialCost calculated but not checked, and if the transaction has no expensive to verify inputs, the statefulValidity() result will be Success(...) even. 

There's a failing test for that in the following PR https://github.com/ergoplatform/ergo/pull/655 .

We need to check initialCost immediately and fail fast.

**Comment by catena2w** [comment]
Looks like it's correct to add `currentAccumulatedCost` parameter to stateful validity and fail as soon as we'll reach the limit

**Comment by kushti** [comment]
@catena2w nope, it doesn't solve the problem as it could be the single big transaction taking too much time to be validated, with "statefulValidity" call result being Success(...)

**Comment by kushti** [comment]
@catena2w I will do cost accumulation under this issue as well though

**Comment by catena2w** [comment]
Fixed by https://github.com/ergoplatform/ergo/pull/655
