### ISSUE TITLE
Mempool transaction validation

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#658]
Looks like transaction validation from mempool significantly slows down blocks application. See https://grafana.ergoplatform.com/d/000000001/ergo-testnet?orgId=1&from=1552665523135&to=1552666399326 `catena-serv` & `ergo-hetzner`. `catena-serv` applied blocks with significant delay and was restarted at `19.06`, after that blocks application become to take much less time.

**Comment by oskin1** [comment]
It is proposed to cut maximum Mempool capacity down to the number of transactions in blocks for 1h.
Another improvement will be to avoid filtering Mempool transactions at each state update, invalid transactions will be eliminated during mining instead.
