### ISSUE TITLE
Slow ReadersHolder initialization

### ISSUE THREAD

**Issue by oskin1** [ergoplatform/ergo#759]
`o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)`

**Comment by knizhnik** [comment]
As far as I understand the questing is about the following fragment of code:

`context.system.scheduler.scheduleOnce(2.seconds)(self.tell(GetReaders, msgSender))(context.system.dispatcher)`

What is the reason for using 2 seconds delay and isn't it actually the reason of slowness?

**Comment by oskin1** [comment]
It was caused by delays in BatchAVLProver initialization.
