### ISSUE TITLE
openapi examples

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#763]
check openapi examples and ensure they work correct. For now looks like http://127.0.0.1:9052/swagger#/wallet/walletPaymentTransactionGenerateAndSend example have incorrect registers

**Comment by ponte83** [comment]
hi there!
i tried to remove
`"registers": {
"R4": "0101"
},`
but when i try send some ergo in /wallet/walletPaymentTransactionGenerateAndSend
i receive this error:
`{
  "error": 400,
  "reason": "bad.request",
  "detail": "Bad request List(PaymentRequest(3Wy855fTJeHQiPuTr7qvdNoyoyP4EYGKRrjbqenGRxV7u8KL35WP,1,Some(List(([B@56f935bf,10))),None), PaymentRequest(Bf1X9JgQTUtgntaer91B24n6kP8L2kqEiQqNf1z97BKo9UbnW3WRP9VXu8BXd1LsYCiYbHJEdWKxkF5YNx5n7m31wsDjbEuB3B13ZMDVBWkepGmWfGa71otpFViHDCuvbw1uNicAQnfuWfnj8fbCa4,100000,None,None)). requirement failed: Minimal ERG value not met"
}`

i have to say that i started a node, waited to be fully synced and started mining. i minted some blocks and after the 720 blocks delay the wallet from the swagger showed a "height" as the current chain height and a non 0 "balance" BUT it didn't shows any "assets". Looking for my address in the testnet explorer it showed a 0 ergo balance and 0 transaction.
 Than i tried in "/wallet/walletAssetIssueTransactionGenerateAndSend" to generate an asset and did work. As soon as the next block was found i had that generated asset in my wallet AND looking for my wallet in the explorer it showed like 68 ERGO and 1 transaction...
really don't know what i did wrong, i think after mining some blocks in the swagger wallet it should show the balance with the ergo declared asset id...
I tried than again issuing some other assets with different amounts (100, 1000, 10000 ecc) and the explorer wallet showed one transaction per asset issued but different and random amount of ergo transacted to my wallet..
thanks for the help!

**Comment by catena2w** [comment]
Hi @ponte83 !
Looks like you're trying to create too small amount (1 nanoErg), try to increase amount you're trying to send to some reasonable value, e.g. 1 Erg == 1000000000 nanoErg.

**Comment by ponte83** [comment]
it's the same :(
`[
  {
    "address": "3Wy855fTJeHQiPuTr7qvdNoyoyP4EYGKRrjbqenGRxV7u8KL35WP",
    "value": 1,
    "assets": [
      {
        "tokenId": "89f0e7c2d33f853103e2f59953c7673cfd6f5e0f389deeb44a0f46bc82a26b88",
        "amount": 5000000000
      }
    ],
    
    "fee": 100
  }
]`

`{
  "error": 400,
  "reason": "bad.request",
  "detail": "Bad request List(PaymentRequest(3Wy855fTJeHQiPuTr7qvdNoyoyP4EYGKRrjbqenGRxV7u8KL35WP,1,Some(List(([B@595ff39c,5000000000))),None), PaymentRequest(Bf1X9JgQTUtgntaer91B24n6kP8L2kqEiQqNf1z97BKo9UbnW3WRP9VXu8BXd1LsYCiYbHJEdWKxkF5YNx5n7m31wsDjbEuB3B13ZMDVBWkepGmWfGa71otpFViHDCuvbw1uNicAQnfuWfnj8fbCa4,100000,None,None)). requirement failed: Minimal ERG value not met"
}`

the asset i'm trying to send it has been issued by myself, i can't see any ergo in my wallet (accessing from swagger), i see 472.5 something ergo if i request `https://testnet.ergoplatform.com/en/addresses/3WxcY9HMD251v9PVMEiVSyF6af784eZtVE7GXN4VYSPAMWG9rZ1c`

those ergo seen in the explorer came when i issued some assets. This is my wallet balance:
`{
  "height": 64675,
  "balance": 25380038700000,
  "assets": {
    "ac6ba740f724321bc68103dbc6b4c9a3b5e784f25fed6165f9d4849daae73e3c": 25,
    "bef950d74d71276e22fceab18fa2fce047935eff6197d00f2b4270359e91aa77": 1005,
    "89f0e7c2d33f853103e2f59953c7673cfd6f5e0f389deeb44a0f46bc82a26b88": 100000000,
    "a0ae0ade526e2a1b4344ebedace6354c33c21395d9182e7059432ec6ec80fd9b": 1000,
    "4791e06f6e86d142533fbe5125c3352874434e925328f02a83dce287000bd3da": 1012,
    "531af20105566be139c189eb960498aabef1c8406566834ed7b91d525fbea2f1": 1000,
    "6916da58811900850ffcb76ee4337e0e36562b06a215ddf829caf908bed1b34d": 100,
    "a616a062ef946a6d56ecc12c9dac263e7693a67ce6006a52cd8e40fbf6c1cf1e": 1015,
    "83ec444e653574a3378a753eb7e0ba0aa4998fc20f8435cbbb75d9eaa8e63ed8": 100000,
    "00689bf5ced89824cc16d763a2175c3301a097997306376d8c33ae650b3a84aa": 100,
    "72a3e225260d4361e91de0e86f69378834652e30691c10d2bede3c2486416d7c": 1
  }
}`
all are issued by me. the strange thing is everytime i issue an asset some random ergo shows up in the "/ergotest/addresses/myaddress" for ex: when i generated  "00689bf5ced89824cc16d763a2175c3301a097997306376d8c33ae650b3a84aa": 100, 
67.something ergo were transacted in my address than
"531af20105566be139c189eb960498aabef1c8406566834ed7b91d525fbea2f1": 1000,
0.5 ergo showed up in my address...
etc.
seems random and all the assets in my wallet have no tokenID...

**Comment by oskin1** [comment]
@ponte83, this error is caused by too low value specified: `"value": 1`
