### ISSUE TITLE
Bad `PersistentBatchAVLProver` asymptotics

### ISSUE THREAD

**Issue by oskin1** [ergoplatform/ergo#790]
It takes ~34sec to instantiate `PersistentBatchAVLProver` assuming blockchain length is 60k blocks.

**Comment by knizhnik** [comment]
How can I reproduce it?
I have full node with height 230k and creation of PersistentBatchAVLProver (from UtxoState.create) takes less than second. But if we run this code under debugger then it dumps local variable and call toString method for the prover. Dumping whole tree to the string really takes about half minute. But in normal exeution toString method is not called.

**Comment by kushti** [comment]
I guess performance increased significantly after switching from IODB to LevelDB. 

Going to close this.
