### ISSUE TITLE
GPU Mining CUDA error

### ISSUE THREAD

**Issue by zill256** [ergoplatform/ergo#801]
GPU: Nvidia Quadro M2200 4GB

When running minner.exe, I got this:
![1](https://user-images.githubusercontent.com/52053492/59884260-67865d00-93ea-11e9-93cd-b4d07bb480ca.jpg)

HERE IS MY GPU/DRIVER/CUDA info:
![2](https://user-images.githubusercontent.com/52053492/59884428-df548780-93ea-11e9-860d-d53306a92a6f.jpg)
I also tried newer drivers, they did not work as well.

**Comment by catena2w** [comment]
moved to miner repository https://github.com/ergoplatform/Autolykos-GPU-miner/issues/46
