### ISSUE TITLE
Defragmentation-aware Box Selector

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#841]
Currently, the box selection is unaware about box amounts. This potentially leads to a lot of small-value (dust) boxes in a wallet.

A solution for that is to alter box selection to spend small-value boxes first.

This could be made a part of DefaultBoxSelector, or we can make pluggable architecture for box selectors (should be a separate issue on that if so).

**Comment by catena2w** [comment]
If only 3 inputs are allowed in a single transaction and our wallet has boxes with amounts `[1,2,3,4,5,6,7,8,9,10]`, this algorithm won't be able to generate transaction that sends 8 ERG, as far as it will collect 4 smallest boxes `[1,2,3,4]` and will exceed cost limit, while it is possible to generate a valid transaction spends enough coins. 

Would be nice to collect the following boxes from `[1,2,3,4,5,6,7,8,9,10]` set according to transaction amount:
| Amount to send        | Selected boxes |
| ------------- |:-------------:|
| 1      | [1,2,3] |
| 3      | [1,2,3] |
| 7      | [1,2,4] |
| 14      | [1,3,10] |
| 17      | [8,9,10] |

**Comment by kushti** [comment]
@catena2w actually, vectors are not optimal, as usually box selector should minimize number of inputs if possible before collecting dust, so 14 <= [10,4], 17 <= [8,9]

I've made a box selector which is parameterized by maximum number of inputs a transaction can have, and optimal number of inputs.

1) the selector first picking up boxes in given order (1,2,3,4,...)
2) if number of inputs exceeds the limit, the selector is sorting remaining boxes(actually, only 3*maximum inputs of them)  by value in descending order and replaces small-value boxes in the inputs by big-value from the tail (1,2,3,4 => 10)
3) if the number of inputs still exceeds the limit, the selector is trying to throw away the dust if possible. E.g. if inputs are (100, 200, 1, 2, 1000), target value is 1300 and maximum number of inputs is 3, the selector kicks out (1, 2)
4) if number of inputs after the previous steps is below optimal, the selector is trying to append the dust, by sorting remaining boxes in ascending order and appending them till optimal number of inputs.

Sounds good?

**Comment by kushti** [comment]
Resolved in the ergo-wallet component https://github.com/ergoplatform/ergo-wallet/pull/33
