### ISSUE TITLE
Make Builds Reproducible

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#845]
Reproducible builds allow to verify that JAR file corresponds to the source code

A tutorial on reproducible builds with Java + Gradle
https://dzone.com/articles/reproducible-builds-in-java

We need to investigate how to do them with SBT and make build reproducible.

**Comment by raboof** [comment]
Have a look at https://github.com/raboof/sbt-reproducible-builds - I'd be happy to help!

**Comment by knizhnik** [comment]
I have tried https://github.com/raboof/sbt-reproducible-builds plugin.
In this case stripped version of jar file produced by "package" is stable.
But not-stripped version is not stable).
Also jar file produced by "assembly" command is not stable.

**Comment by raboof** [comment]
That the non-stripped version is not stable is expected - you should ship the stripped one (which, if you use 'publish', should be automatic).

That 'assembly' jars are not stable is probably because we need to do work in sbt-reproducible-builds to make them stable - I filed https://github.com/raboof/sbt-reproducible-builds/issues/127. Help appreciated ;)

**Comment by knizhnik** [comment]
Hmmm, I am not so familar with SBT so it will take me some time to change this plugin to properly  handle "assembly" command. 
By the way I do not completely understand the goal. 
Do we need to be able just to compare two jars files and verify that them are produced from the same sources? 
But it can be easily done by extracting this archives "jar xf" and recursive comparison of directories (diff -r).
jar has no option to override timestamp of created files. But tar has such option:

tar cf -  --mtime='1970-01-01' . | md5sum

**Comment by raboof** [comment]
> Hmmm, I am not so familar with SBT so it will take me some time to change this plugin to properly handle "assembly" command.

Makes sense - I've put it on my own todo list as well, but I have a lot of other things to do in my free time as well ;), so it might be a while before I get to it.

> Do we need to be able just to compare two jars files and verify that them are produced from the same sources?

If you want to claim you support 'reproducible builds' then this is typically understood to mean really bit-by-bit reproducible, yes (https://reproducible-builds.org/)

> But it can be easily done by extracting this archives "jar xf" and recursive comparison of directories

Indeed by comparing *some* but not *all* bits of your deliverables you can get *some* (but not *all*) of the benefits of reproducible builds ;). Doing any operations before comparing the outputs always introduces a risk of opening up an opportunity to sneak in malicious content. For example, it might be possible to craft a 'technically invalid' jar file that contains a file that is invisible to "tar cf" but _is_ loaded by the JVM. Perhaps this seems far-fetched, but by having your artifact bit-by-bit reproducible you clearly avoid any such issues - and make it much easier to verify.
