### ISSUE TITLE
Possible double-scanning of a postponed block

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#850]
A user is claiming that his node is showing 135 Erg while another node as well as the explorer shows 67.5. From logs, it seems the mined block was postponed. Is double-scanning somehow possible for a postponed block?

**Comment by oskin1** [comment]
Unlikely -- all postponed blocks are deleted right after final processing. The only thing which could break this protocol is unexpected node shutdown (when the blocks are already scanned, but not yet deleted).

**Comment by oskin1** [comment]
I think, the problem could probably also arise in case of non-clean migration from 3.0.2 to 3.0.3.

**Comment by reb0rn21** [comment]
I have migrated from 3.0.2 to 3.0.3 to regain right balance show, did not delete old chain at first 3.0.3 show right balance only today it show more then i real

**Comment by oskin1** [comment]
@reb0rn21, try performing clean migration.

**Comment by reb0rn21** [comment]
sure new node I use for transaction is fine (right balance), but that node is only online when I do TX
