### ISSUE TITLE
Update Node Configuration Tutorial

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#874]
This tutorial is outdated and should be updated 

https://github.com/ergoplatform/ergo/wiki/Node-Configuration-File

Bonus: 100 Ergs (provide Ergo address in the PR)

**Comment by marncz** [comment]
@kushti - is this work still available to be picked up?

**Comment by glasgowm148** [comment]
Closed by https://docs.ergoplatform.com/node/
