### ISSUE TITLE
API: /script/execute or /script/executeWithContext

### ISSUE THREAD

**Issue by jasondavies** [ergoplatform/ergo#902]
From morphic on Slack:

> Not exactly, the script has to be executed in the target context and the resulting SigmaProp (which is tree data structure in general) should be investigated. Then existing keys should be matched with those in the tree. If there are AND, OR or THRESHOLD connectives in the tree, corresponding sigma protocol operations have to be executed to generate signatures. (proofs in Sigma terminology)

I think along with #901, we also need the ability to execute a script in a given target context so that we can generate proofs for the resulting SigmaProp.

**Comment by aslesarenko** [comment]
Implementation steps:

- [ ] On the client side, create a context (in the form of Json) for script execution.
      The context is used to execute script given by string + environment. 
      Environment should be passed as the following Json, where each value is encoded 
      using `DataJsonEncoder` from Sigma.
      ```
      { name1: value; ... nameN: value }
      ```
- [ ] send (ctx, scriptString, env) as POST request to the API address `/script/executeToSigmaTree`
- [ ] on the server, read ctx using `ergoLikeContextEncoder` into the `ErgoLikeContext` object.
- [ ] on the server, compile (scriptString, env) to `ErgoTree` using `ScriptApiRoute.compileSource` 
- [ ] create `ErgoProvingInterpreter` (from ergo-wallet) and call `reduceToCrypto` method.
- [ ] serialize the result of the call in Json and return it as the result of the request.
      The result in general contains `SigmaBoolean` value, for which we don't have Json encoder.
      This have to be implemented as subtask
      
  - [ ] Implement Json Encoder/Decoder pair for SigmaBoolean values (aka sigma tree)

In general, this involves many subsystems, so you may need to dig along these steps.
Ping me with questions in comments below if necessary.

To understand which Json to send, for example, you can make ErgoLikeContext and serialize 
it to Json via ergoLikeContextEncoder.

NOTE: The work should be done using `v3.0.3` branch of Sigma.
