### ISSUE TITLE
CPU and memory consumption when many miners are connected

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#914]
It is reported that when there are many miners (like 100) connected, a protocol client consumes a lot of CPU (400%) and memory. We need to do profiling to find possible resource leaks.

**Comment by pragmaxim** [comment]
I think I know why this happens, we use unbounded mailboxes and 100 miners querying 20 reqs/s might produce 200 reqs/s and I believe that at time of `PrepareCandidate` which takes quite a while, the requests queue up ... The solution might be in introducing some sort of backpressure to slow miners down.

I guess in general this might be resolved by internal `retries` in combination with some Bounded mailbox to avoid DDOS attack.

**Comment by pragmaxim** [comment]
@kushti I think I found the real cause of this. Miners compete for block candidate and we have CPU heavy operation in `onComplete` https://github.com/ergoplatform/ergo/blob/04c1424066255cfc4aa6bbe0917686b860065d49/src/main/scala/org/ergoplatform/mining/ErgoMiner.scala#L318

I believe that we sohuld eliminate the `ask` pattern ` (readersHolderRef ? GetReaders).mapTo[Readers]` and simply subscribe for the NodeView changes and keep it as local state.
