### ISSUE TITLE
Spending of a confirmed box

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#921]
Sometimes wallet tries to spend a confirmed box.

See an attached log for example. 

Transaction 4bf526f06489a72b7a6f02bba3f220492ba39d1afa6063011ff2118cb3ccd468 spends input 01086ac771bd936d66a7804bf5facceccf3bc9f1136c6f9f64ceda558fdee7f5 and got soon into a block. Then two minutes after transaction 01629e48f4cbaef0e1ced8853b6f42a79ca0dcab675ba457caf07ed7ec64c9b3 is trying to spend the same box. 

[ergo.log](https://github.com/ergoplatform/ergo/files/3672615/ergo.log)

**Comment by oskin1** [comment]
@kushti, any ideas how could it be reproduced?

**Comment by kushti** [comment]
> @kushti, any ideas how could it be reproduced?

@oskin1 not quite really, but there are two examples in the log, tx ids are following:

01629e48f4cbaef0e1ced8853b6f42a79ca0dcab675ba457caf07ed7ec64c9b3

9b00f7ecf2dc42789839a07268afdacefe638a23881c1d8cc74a0be038bea260

**Comment by oskin1** [comment]
The direct reason of such behavior is that block containing `4bf526f06489a72b7a6f02bba3f220492ba39d1afa6063011ff2118cb3ccd468 ` was actually scanned by the wallet afterwards the `01086ac771bd936d66a7804bf5facceccf3bc9f1136c6f9f64ceda558fdee7f5` was created:
```
05:50:39.600 DEBUG [or.default-dispatcher-187] o.e.local.CleanupWorker - Transaction 01629e48f4cbaef0e1ced8853b6f42a79ca0dcab675ba457caf07ed7ec64c9b3 invalidated: Every input of the transaction should be in UTXO. 01629e48f4cbaef0e1ced8853b6f42a79ca0dcab675ba457caf07ed7ec64c9b3: 0 == 1
05:50:39.600 INFO  [or.default-dispatcher-187] o.e.local.CleanupWorker - 1 transactions from mempool were invalidated
...
05:50:39.803 INFO  [or.default-dispatcher-185] o.e.n.w.ErgoWalletActor - Processing block at height 56117 with 1 wallet transactions <-- here is 4bf526f06489a72b7a6f02bba3f220492ba39d1afa6063011ff2118cb3ccd468
```
