### ISSUE TITLE
Test a new version of ergo + sigma on the Mainnet

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo#924]
### Motivation
Our test suites relying on a "synthetic" data in a "synthetic" environment don't give enough information on how the code will behave on the Mainnet. Thus, testing the new ergo and underlying dependencies versions on the Mainnet during the development process will give us early feedback. 

### Scenario:
- build the node;
- run it on the Mainnet inside a docker container;
- wait for "all green" status (or timeout);
- shutdown the node

### Implementation details
Requirements:
- run as a lengthy CI job;
- it should not interfere with other CI job (queues, etc.);
- cannot be a part of it:test suite;
- due to a potential complexity of "all green" status analysis and a potential need of existing ergo and sigma test code, the whole test should be implemented in Scala;
- in case of failure relevant artifacts (logs, etc.) can be stored for X days.

Ideally, I see this implemented as `it2` test config. Similar to existing integration tests (`it` config). It would allow these tests to be run separately (`sbt it2:test`) and implement all the test orchestration and node status analysis in Scala.

### Optional (future) optimizations:
- Since waiting for full sync should take significant time, to speed up the process, we can use a daily snapshot of local data from a working node from Mainnet. This would eliminate network-related delays.
- "Read-only" mode to test the code with a high risk of generating data that could potentially "upset" current mainnet nodes.

**Comment by aslesarenko** [comment]
Questions:
1) you suggest this to be console Scala application? Why Scala?
2) "daily snapshot of local data from a working node from Mainnet" sounds like a subtask?
3) On the other hand, snapshot can be used only until full re-sync is required (due to database changes)?
4) Can the snapshot be optional parameter?

**Comment by greenhat** [comment]
@aslesarenko 
I've updated the description to answer some of the questions.

1. No, a separate test suite.
2. Yes, I've included it just as a future optimization and not a part of the current scope.
3. Yes. If we introduce such a change, the "optimized" version of the test will be broken. So, we would probably need to fall back to full network sync in this case. 
4. Sure.

**Comment by greenhat** [comment]
@oskin1 Do you think that the idea of this test makes any sense? Is it possible to implement this test similar to existing "it:test" architecture and check the node's status after the full sync is completed?

**Comment by greenhat** [comment]
@andyceo Do you think our CI infrastructure can handle such long-running job? It should require resources similar to our existing `ergo-it` job but it would run significantly longer.

**Comment by andyceo** [comment]
> @andyceo Do you think our CI infrastructure can handle such long-running job? It should require resources similar to our existing `ergo-it` job but it would run significantly longer.

Sure, it can not. Currently only one job at a time can execute. I hope you remember the reasons why we did this.

We definitely need one more server dedicated to your proposed job. You said that this job can execute long time, let imagine, that this time so long that new commits will come during that job. So when the job ends, it is time to start next one, so we can say with high probability that this would be a forever-executing job.

As for your example with database, I think it is not the case for your proposal, because DB performance can be separated to unit-test and performance must be measured in it, with much more accuracy with many kinds of stored data and load profiles.

And last, I propose to do all the scenario you described, manually first. Just run the node on your laptop in Mainnet. Do what you want for testing (this part I did not understand, what kind of tests do you plan to do with executing node? Profiling? API queries? What? What the results should look like?) and share it with the team in this issue, to illustrate all the details.

And the very last, we should concern about security, if plan to do such testing automatically, to not harm Mainnet with many hazardous nodes.

**Comment by aslesarenko** [comment]
@greenhat I agree with @andyceo, this require dedicated server. 
@andyceo do we need a second jenkins instance? 
I mean maybe existing jenkins can run specific jobs on the dedicated server?

I'm not sure we need this job to run on every commit, so we need some way of controlling it:
1) we can have some branch naming convention (like `feature-branch-name:test-mainnet`)
2) we can have a bot living in PR comments
3) we can manually start jobs on the server
4) ...

This is about how to start/stop/run this jobs.

Another question is how this job is to be implemented.
For obvious reasons I like the idea to copy it:test SBT setup and adapt it for this specific scenario.
We will have both reuse of existing test infrastructure and a lot of flexibility to extend the scenario in future. 
@greenhat How much time it will take to implement this SBT part and manually check if it works on your laptop (or if you need this can be done on one of our servers)?

**Comment by andyceo** [comment]
> @andyceo do we need a second jenkins instance?

Nope.

> I mean maybe existing jenkins can run specific jobs on the dedicated server?

Yes this is true.

> I'm not sure we need this job to run on every commit, so we need some way of controlling it:
> 
>     1. we can have some branch naming convention (like `feature-branch-name:test-mainnet`)
> 
>     2. we can have a bot living in PR comments
> 
>     3. we can manually start jobs on the server
> 
>     4. ...
> 
> 
> This is about how to start/stop/run this jobs.

If you want manually start/stop job, it can be done via Jenkins using it's job workflow. No need to write extra letters to any bots. And as I [mentioned here](https://github.com/ergoplatform/ansible/issues/5#issuecomment-537964938), there are enough severities even for experiments with bots, not to mention speak about them as production-ready solution.

> Another question is how this job is to be implemented.
> For obvious reasons I like the idea to copy it:test SBT setup and adapt it for this specific scenario.
> We will have both reuse of existing test infrastructure and a lot of flexibility to extend the scenario in future.

As I can see, it is simple copy of ergo-it job, without any extras that exists for ergo-it, like auto deploying to testnet-mainnet, trigger other jobs and so on. To implement this, we simply add new worker server into Jenkins, copy ergo-it job and tie the copy to new server. This can be done relatively fast.

**Comment by greenhat** [comment]
@andyceo 
> > @andyceo Do you think our CI infrastructure can handle such long-running job? It should require resources similar to our existing `ergo-it` job but it would run significantly longer.
> 
> Sure, it can not. Currently only one job at a time can execute. I hope you remember the reasons why we did this.

Apologies for the incorrect question. :) I'm aware of the reasons. Actually, I meant to ask what additional resources do we need to run such a task. Thanks for the answer.

> And last, I propose to do all the scenario you described, manually first. Just run the node on your laptop in Mainnet. Do what you want for testing (this part I did not understand, what kind of tests do you plan to do with executing node? Profiling? API queries? What? What the results should look like?) and share it with the team in this issue, to illustrate all the details.

I'm planning to launch a node, let it fully sync and then check it's status via JSON API. I'm not sure what fields to check exactly though (compare its height vs explorer, etc.). The result should be a binary green/red, similar to what we have in `it:test`. Then shut down and destroy the node, archiving any logs, other artifacts (if needed). 

> And the very last, we should concern about security, if plan to do such testing automatically, to not harm Mainnet with many hazardous nodes.

This is a very good point! For now, we can just limit it on our CI to be a serial queue (e.g. 1 simultaneously running task). Also, we can make some kind of read-only mode and use it to test the code with a high risk of generating data that could potentially "upset" current mainnet nodes. Added to the description.

**Comment by greenhat** [comment]
@aslesarenko 
> @greenhat How much time it will take to implement this SBT part and manually check if it works on your laptop (or if you need this can be done on one of our servers)?

I'm thinking of two days to clone/reuse existing `it:test` code infrastructure and a simple test on top of it. However, due to the long sync process, iterating on it might be quite slow.

**Comment by kushti** [comment]
@greenhat is this issue  resolved?

**Comment by greenhat** [comment]
@kushti Yes, but the PR is not merged. The PR https://github.com/ergoplatform/ergo/pull/925 is ready and waiting. @andyceo took care of Jenkins infra. The only thing left is to set up when `ergo-it2` jenkins job should be triggered. @aslesarenko suggested for every commit to `develop` branch. I agree it's a good starting point.
