### ISSUE TITLE
[API] Allow specifying index of output boxes in transaction generation

### ISSUE THREAD

**Issue by scalahub** [ergoplatform/ergo#932]
https://explorer.ergoplatform.com/en/addresses/5p1BnDBxe5KENAspbNnVzZEkvohygjPibgbnTHCB4QPp1dx9Y3ts96bSmhZ3E6ZAUhTebXeh5UaH

This was created using the call /wallet/transaction/send

Two boxes were specified of value 123456 each. The behavior is that the first two output boxes are change and fee respectively and the boxes in requests are created after that. This might cause some scripts to break if they require the first output to be of a certain form (as in most of our examples). 

So there are three solutions:
1. Provide an API where we can specify box index
2. Add fee and change to the end rather than the beginning
3. Ensure that our scripts don't use index 0 and 1 in code

**Comment by aslesarenko** [comment]
@scalahub  The point 3) is brittle. I think we better off without it.
The first two ideally be implemented both. 
The 1) will give exact control of the input and output positions, but it is harder to use.
the 2) is easier to use, but might be not suitable for some scripts.

**Comment by kushti** [comment]
Order is preserved by the Ergo client actually, that was explorer showing outputs in improper order (fixed now)
