### ISSUE TITLE
EIP-0001: Recognizing Boxes And Correct Their Status Externally

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#942]
Implement scanning.

The wallet is collecting boxes according to scanning rules. However, a box which is passing a simple test not necessarily belongs to an application. An application then needs to inform the wallet on whether a box is certainly belongs to it or not. The following two methods are informing the wallet about that, and the both methods have "applicationId" and "boxId" as inputs:

    /application/makeCertain/{applicationId}/{boxId} - to inform the wallet that a box indeed belongs to an application
    /application/stopTracking/{applicationId}/{boxId} - to inform the wallet that a box does not belong to an application and so should not be tracked anymore

**Comment by scalahub** [comment]
Can we ask the wallet to track an arbitrary box? (i.e., one that is not matched by any rules.)

**Comment by robkorn** [comment]
I presume given the endpoints above you can use `/application/makeCertain/{applicationId}/{boxId}` to track an arbitrary box. If not then I agree with scalahub that it should be possible to do track an arbitrary box for a given applicationID.

**Comment by kushti** [comment]
done in 3.3.0
