### ISSUE TITLE
Wallet: generate keys according to EIP3

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#959]
[EIP3](https://github.com/ergoplatform/eips/blob/master/eip-0003.md) is accepted, now it's time to use it inside a build-in node wallet.
To keep backward compatibility, I propose to add a new flag to config `wallet.legacyMode=false`. It is false by default and generate private keys according to EIP3. If it is set to true - it generates private keys according to old style.

**Comment by aslesarenko** [comment]
@catena2w I suggest to provide migration from old wallets to the new ones if possible. Thus simplify the reference implementation code.

**Comment by catena2w** [comment]
We should keep in mind, that there are external applications that already relies on this code:
- GPU miner generate keys according to the old scheme.
- Exchanges generate batches of addresses for their users. I don't think that it is possible to requeist from all the exchanges to change deposit addresses for all their users.

**Comment by kushti** [comment]
@catena2w it is unlikely that users will change default values in the settings. 

More, there's the need to support primitive secrets (just dlogs or dlog-equality secret keys), see e.g. https://github.com/ergoplatform/ergo/issues/940

Thus I propose to think how can different schemes co-exist.

**Comment by catena2w** [comment]
Well, that was my idea - new users won't change the default values, and thus will create wallets according to EIP3. 
Existing users will migrate from the current version using a guide and thus will change their config. If their addresses will change after updating to some release, it should not too difficult yo determine how they should change the config to keep their old wallet working. So with time old-style wallets will be replaced with the new one, and all users will have EIP3 keys

**Comment by kushti** [comment]
The problem is that users do not read any guides when updating, also not updating from one version to next one, so there will be need to put this guide in bold for many releases ahead. 

Just personal observations from supporting tens of users during last months.

**Comment by kushti** [comment]
Done  in #1199, @aslesarenko @catena2w please check how
