### ISSUE TITLE
It is possible to run more than one ergo node instance

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/ergo#975]
## Actual behaviour

It is possible to run more than one ergo node instance on the same jar file and data dir and ports.

## Steps to reproduce

1. Open first terminal and run `java -jar ergo.jar --mainnet` Node starts ok and start syncing, writing to it's data dir and open ports

2. Open second terminal and run `java -jar ergo.jar --mainnet` again Node starts, but that looks strange, because at least it can not occupy the same ports and must fail to run. But second node instance is running, also produce heavy CPU load 

## Expected behaviour

Trying to execute second instance of node on same ports, data dir must fail.

**Comment by knizhnik** [comment]
is my understanding correct that we need to handle java.net.BindException as fatal error and shutdown application in this case?

I am not familiar with akko, but after some googling I find out that akka actors can be configured like this (https://doc.akka.io/docs/akka/current/fault-tolerance.html):

```
override val supervisorStrategy =
    OneForOneStrategy(maxNrOfRetries = 1) {
      case _: java.net.BindException => Stop
      case _: Exception              => Escalate
    }
```

I am not sure if it is enough to properly shutdown ergo node.
But looks like this code should be added to scorex.core.network.NetworkController
which is not part of ergo project. Should I change this library (if so, how to get it?) or may be I should look for some other way of configuring error handling policies for Akka?

**Comment by andyceo** [comment]
For the note: it is easy to stop second node instance if you add empty `.lock` file (and/or `ergo.pid` containing first instance pid) to data directory. This how Bitcoin handle this (node is running):

```
# cd .bitcoin
# ls -lah
total 71M
drwxr-xr-x 5 root root 4.0K Nov 25 19:36 .
drwx------ 1 root root 4.0K Nov 16 15:17 ..
-rw------- 1 root root   75 Nov 16 15:17 .cookie
-rw------- 1 root root    0 Mar 18  2019 .lock
-rw------- 1 root root    0 Mar 18  2019 .walletlock
-rw------- 1 root root  739 Nov 25 18:21 banlist.dat
-rw------- 1 root root    2 Nov 16 15:17 bitcoind.pid
drwx------ 3 root root 120K Nov 24 19:39 blocks
drwx------ 2 root root  92K Nov 25 19:26 chainstate
drwx------ 2 root root 4.0K Nov 16 15:17 database
-rw------- 1 root root    0 Mar 18  2019 db.log
-rw------- 1 root root  11M Nov 25 19:42 debug.log
-rw------- 1 root root 243K Nov 16 15:16 fee_estimates.dat
-rw------- 1 root root  53M Nov 16 15:16 mempool.dat
-rw------- 1 root root 4.7M Nov 25 19:36 peers.dat
-rw------- 1 root root 1.4M Nov 25 15:17 wallet.dat
# cat .lock
#
# cat bitcoind.pid
1
```

**Comment by knizhnik** [comment]
Creating lock file with PID is standard solution for protecting data directory (used not only in Bitcoin, but also in Postgres and many other systems).
But as far as I understand we also what to protect spawning node from different data directories but using the same port which cause second node to waste CPU cycles and write a lot of message to log file. Also as far as I know, LevelDB also protects concurrent access the storage directory itself. So may be maintaining lock file by Ergo application is not needed at all.

So, is it necessary to treat "port already in use" error as fatal and terminate node in this case?
Or it is enough to lock data directory from concurrent access?

**Comment by andyceo** [comment]
I vote for fatal error for both cases: ports and/or directory. If even one matched, node should exit with sane error message.

**Comment by knizhnik** [comment]
I failed to make supervisorStrategy worked properly.
I handled "port in use" problem in other way - using  bindingLogic method.
Proposed PR is 
   https://github.com/ScorexFoundation/Scorex/pull/355

If it is not desired to change scorex.core, I can add check for availability of port to ErgoApp: just try to open socket on this port and immediately close it. It is not so good solution: first of all we have to open socket twice. Also it suffers from race condition: port can be occupied after our check. Also there is some OS timeout for pinning port, so even if we immediately close it, it doesn't mean that subsequent bind request to the same port will be successful.

Proposed fix for preventing access to the same data directory by more then one node is here:
  https://github.com/ergoplatform/ergo/pull/977
In branch  iodb_repplacement it can be done better: there is RegisteredDB wrapper for database where this check can be done for all databases opened by node.

**Comment by knizhnik** [comment]
Also committed patch in branch  iodb_replacement:
https://github.com/ergoplatform/ergo/commit/4846196930a7a1db7b1fa5c4181d1a5063181928

I am not sure if java.lang.System.exit is right way of node termination. If there is better alternative please let me know.
