### ISSUE TITLE
Error on setup new blockchain

### ISSUE THREAD

**Issue by vorujack** [ergoplatform/ergo#979]
flag `offlineGeneration` set to start a new testnet. When miner found a solution and submit it node returned 500 internal error. error is displayed below:

    {
      "error" : 500,
      "reason" : "internal.error",
      "detail" : "requirement failed: Incorrect points"
    }

**Comment by mhssamadani** [comment]
It occurs using the old and buggy miners. With the last versions of AMD and NV miner this issue is fixed.

**Comment by kushti** [comment]
closing as not related to the node
