### ISSUE TITLE
Support backward scanning of transactions by the wallet

### ISSUE THREAD

**Issue by mhssamadani** [ergoplatform/ergo#983]
Currently you should initialize or restore wallet before the retrieval since the node is only scanning forward. The only way for backward scanning is deleting `.ergo` folder. Deleting the /wallet and /state folders results in freezing the node and stucking to Null in /info.
There should be an api to force the node to scan from a certain height.

**Comment by kushti** [comment]
/wallet/rescan is doing (full) rescan since 3.3.1
